<?php

namespace App\Filament\Resources\SalesReturns\Schemas;

use App\Filament\Forms\Components\NumberInput;
use App\Filament\Forms\Components\RoundedIntegerMoneyInput;
use App\Forms\Components\SelectWithModal;
use App\Traits\HasAutoGeneratedCode;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\Repeater;
use Filament\Forms\Components\Repeater\TableColumn;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Hidden;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Filament\Support\Enums\Alignment;


class SalesReturnForm
{
    use HasAutoGeneratedCode;

    /**
     * Get the document type for code generation
     *
     * @return string
     */
    protected function getDocumentType(): string
    {
        return 'sales_return';
    }

    /**
     * Get code field name
     *
     * @return string
     */
    protected function getCodeFieldName(): string
    {
        return 'return_number';
    }

    protected static function resolveCompanyId(callable $get): ?int
    {
        $companyId = $get('company_id');
        if ($companyId && $companyId !== 'all') {
            return (int) $companyId;
        }
        $selectedCompanyId = session('selected_company_id');
        if ($selectedCompanyId && $selectedCompanyId !== 'all') {
            return (int) $selectedCompanyId;
        }
        return null;
    }

    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make()
                    ->schema([
                        Select::make('company_id')
                            ->relationship(
                                name: 'company',
                                titleAttribute: 'name',
                                modifyQueryUsing: function ($query) {
                                    $user = auth()->user();
                                    if ($user) {
                                        $userCompanyIds = $user->companies()->pluck('companies.id');
                                        if ($userCompanyIds->isNotEmpty()) {
                                            $query->whereIn('companies.id', $userCompanyIds);
                                        } else {
                                            // If user has no assigned companies, return no results
                                            $query->whereRaw('1 = 0');
                                        }
                                    }
                                }
                            )
                            ->default(function () {
                                $selectedCompanyId = session('selected_company_id');
                                return $selectedCompanyId && $selectedCompanyId !== 'all'
                                    ? $selectedCompanyId
                                    : null;
                            })
                            ->hidden(function () {
                                $selectedCompanyId = session('selected_company_id');
                                return $selectedCompanyId && $selectedCompanyId !== 'all';
                            })
                            ->searchable()
                            ->preload()
                            ->nullable()
                            ->reactive()
                            ->afterStateUpdated(function ($state, callable $set) {
                                // Clear customer and delivery document when company changes
                                $set('customer_id', null);
                                $set('delivery_document_id', null);
                            })
                            ->columnSpanFull(),
                        Select::make('customer_id')
                            ->label('Customer')
                            ->disabled(fn ($record) => (bool) ($record?->is_locked))
                            ->relationship(
                                name: 'customer',
                                titleAttribute: 'name',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $companyId = self::resolveCompanyId($get);
                                    if ($companyId) {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    return $query->where('is_customer', true)->orderBy('name');
                                }
                            )
                            ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->name} ({$record->contact_code})")
                            ->searchable(['name', 'contact_code'])
                            ->preload()
                            ->required()
                            ->live(onBlur: true)
                            ->afterStateUpdated(function ($state, callable $set) {
                                // Clear delivery document and items when customer changes
                                $set('delivery_document_id', null);
                                $set('items', []);
                            })
                            ->createOptionForm([
                                TextInput::make('name')
                                    ->label('Name')
                                    ->required(),
                                (new \App\Filament\Resources\Contacts\Schemas\ContactForm)->getCodeField('contact_code', 'Contact Code')
                                    ->unique(\App\Models\Contact::class, 'contact_code', ignoreRecord: true,
                                        modifyRuleUsing: function ($rule) {
                                            // Get the company_id from the session
                                            $companyId = session('selected_company_id');

                                            // If there's a selected company, scope the uniqueness check to that company
                                            if ($companyId && $companyId !== 'all') {
                                                $rule->where('company_id', $companyId);
                                            }
                                            // If no company is selected, the uniqueness check will apply to all records
                                            // This ensures records are unique within their company
                                            return $rule;
                                        },
                                    ),
                                TextInput::make('email')
                                    ->label('Email')
                                    ->email(),
                                TextInput::make('phone')
                                    ->label('Phone')
                                    ->tel(),
                                Hidden::make('is_customer')
                                    ->default(true),
                                Hidden::make('company_id')
                                    ->default(function (callable $get) {
                                        $companyId = $get('company_id') ?: session('selected_company_id');
                                        return ($companyId && $companyId !== 'all') ? $companyId : null;
                                    }),
                                Hidden::make('created_by_user_id')
                                    ->default(function () {
                                        return auth()->id();
                                    }),
                            ])
                            ->createOptionUsing(function (array $data) {
                                $contact = \App\Models\Contact::create($data);
                                return $contact->id;
                            }),
                        SelectWithModal::make('delivery_document_id')
                            ->label('Delivery Document')
                            ->disabled(fn ($record) => (bool) ($record?->is_locked))
                            ->relationship(
                                name: 'deliveryDocument',
                                titleAttribute: 'delivery_number',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $companyId = self::resolveCompanyId($get);
                                    if ($companyId) {
                                        $query->where('company_id', $companyId);
                                    }

                                    $customerId = $get('customer_id');
                                    if ($customerId) {
                                        $query->where('customer_id', $customerId);
                                    }

                                    // Only include delivery documents with 'posted' status
                                    $query->where('status', 'posted');

                                    // Only exclude delivery documents that already have locked sales returns when creating a new record
                                    // Delivery document menu creates locked returns automatically, so this prevents manual creation
                                    // if any return was created from delivery document menu
                                    $currentRecordId = $get('../../record')?->id ?? null;
                                    if (!$currentRecordId) {
                                        $query->whereDoesntHave('salesReturns', function ($returnQuery) {
                                            $returnQuery->where('is_locked', true)
                                                        ->whereNull('sales_returns.deleted_at');
                                        });
                                    }

                                    return $query->orderBy('delivery_number');
                                }
                            )
                            ->getOptionLabelFromRecordUsing(fn ($record) => $record->delivery_number)
                            ->searchable()
                            ->preload()
                            ->placeholder('Select Delivery Document')
                            ->reactive()
                            ->live(onBlur: true)
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                // Load delivery items when delivery is selected
                                if ($state) {
                                    $delivery = \App\Models\DeliveryDocument::with('items.product')->find($state);
                                    if ($delivery) {
                                        // Set job_id from delivery
                                        $set('job_id', $delivery->job_id);

                                        // Load delivery items as return items
                                        $items = [];
                                        foreach ($delivery->items as $deliveryItem) {
                                            $items[] = [
                                                'product_id' => $deliveryItem->product_id,
                                                'quantity' => $deliveryItem->quantity,
                                                'quantity_display' => NumberInput::formatRoundedIntegerDisplay($deliveryItem->quantity),
                                                'unit_id' => $deliveryItem->unit_id,
                                                'return_reason' => '',
                                                'description' => $deliveryItem->description,
                                                'conversion_factor' => $deliveryItem->conversion_factor ?? 1,
                                                'base_quantity' => $deliveryItem->base_quantity ?? $deliveryItem->quantity,
                                            ];
                                        }
                                        $set('items', $items);
                                    }
                                } else {
                                    // Clear job_id and items when no delivery selected
                                    $set('job_id', null);
                                    $set('items', []);
                                }
                            }),
                        DatePicker::make('date')
                            ->required()
                            ->default(now())
                            ->columnSpan(1),
                        TextInput::make('reference_no')
                            ->maxLength(255)
                            ->label('Reference No.')
                            ->columnSpan(1),
                        (new static)->getCodeField()
                            ->unique('sales_returns', 'return_number', ignoreRecord: true,
                                modifyRuleUsing: fn ($rule) => $rule->where(function ($query) {
                                    $companyId = session('selected_company_id');
                                    if ($companyId && $companyId !== 'all') {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    $query->whereNull('deleted_at');
                                    return $query;
                                })
                            ),
                        Hidden::make('job_id'),
                        Textarea::make('description')
                            ->rows(1)
                            ->maxLength(65535)
                            ->label('Description'),
                        Select::make('status')
                            ->label('Status')
                            ->options([
                                'draft' => 'Draft',
                                'posted' => 'Posted',
                            ])
                            ->default('posted')
                            ->required()
                            ->native(false)
                            ->live(),
                    ])
                    ->columns(3)
                    ->columnSpanFull(),

                // Return Items
                Repeater::make('items')
                    ->relationship()
                    ->hiddenLabel()
                    ->addActionLabel('Add New Item')
                    ->required()
                    ->table([
                        TableColumn::make('Product')->width('35%')->alignment(Alignment::Start),
                        TableColumn::make('Quantity')->width('12%')->alignment(Alignment::End),
                        TableColumn::make('Unit')->width('13%')->alignment(Alignment::Start),
                        TableColumn::make('Return Reason')->width('30%')->alignment(Alignment::Start),
                        TableColumn::make('Description')->width('10%')->alignment(Alignment::Start),
                    ])
                    ->schema([
                        Hidden::make('delivery_document_item_id'),
                        Select::make('product_id')
                            ->required()
                            ->searchable(['name', 'code'])
                            ->label('Product')
                            ->disabled(fn (callable $get) => (bool) $get('../../is_locked'))
                            ->relationship(
                                name: 'product',
                                titleAttribute: 'name',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $companyId = self::resolveCompanyId($get);
                                    if ($companyId) {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    return $query->orderBy('name');
                                }
                            )
                            ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->name} ({$record->code})")
                            ->preload()
                            ->live()
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                $product = \App\Models\Product::find($state);
                                if ($product) {
                                    if ($product->unit_id) {
                                        $set('unit_id', $product->unit_id);
                                        $set('conversion_factor', 1);
                                        $set('base_quantity', \App\Filament\Forms\Components\RoundedIntegerMoneyInput::parseToFloat($get('quantity') ?? 0));
                                    }
                                }
                            })
                            ->createOptionForm([
                                TextInput::make('name')
                                    ->label('Name')
                                    ->required(),
                                (new \App\Filament\Resources\Products\Schemas\ProductForm)->getCodeField('code', 'Product Code')
                                    ->unique(
                                        \App\Models\Product::class,
                                        'code',
                                        ignoreRecord: true,
                                        modifyRuleUsing: function ($rule) {
                                            // Get the company_id from the session
                                            $companyId = session('selected_company_id');

                                            // If there's a selected company, scope the uniqueness check to that company
                                            if ($companyId && $companyId !== 'all') {
                                                $rule->where('company_id', $companyId);
                                            }
                                            // If no company is selected, the uniqueness check will apply to all records
                                            // This ensures records are unique within their company
                                            return $rule;
                                        },
                                    ),
                                Select::make('product_group_id')
                                    ->label('Product Group')
                                    ->relationship(
                                        "productGroup",
                                        "name",
                                        modifyQueryUsing: function ($query) {
                                            $selectedCompanyId = session('selected_company_id');
                                            if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                                                $query->where('company_id', $selectedCompanyId);
                                            }
                                            return $query;
                                        }
                                    )
                                    ->searchable()
                                    ->preload()
                                    ->required(),
                                ...RoundedIntegerMoneyInput::schema(
                                    name: 'selling_price',
                                    label: 'Selling Price',
                                    required: false,
                                    defaultDecimal: '0.00',
                                ),
                                Select::make('unit_id')
                                    ->label('Unit')
                                    ->searchable()
                                    ->options(function () {
                                        $selectedCompanyId = session('selected_company_id');
                                        $q = \App\Models\Unit::query();
                                        if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                                            $q->where('company_id', $selectedCompanyId);
                                        } else {
                                            $q->whereNull('company_id');
                                        }
                                        return $q->orderBy('name')->pluck('name', 'id')->toArray();
                                    }),
                                Textarea::make('description')
                                    ->label('Description')
                                    ->rows(2),
                                Hidden::make('company_id')
                                    ->default(function () {
                                        $selectedCompanyId = session('selected_company_id');
                                        return ($selectedCompanyId && $selectedCompanyId !== 'all') ? $selectedCompanyId : null;
                                    }),
                                Hidden::make('created_by_user_id')
                                    ->default(function () {
                                        return auth()->id();
                                    }),
                            ])
                            ->createOptionUsing(function (array $data) {
                                $product = \App\Models\Product::create($data);
                                return $product->id;
                            }),
                        ...RoundedIntegerMoneyInput::schema(
                            name: 'quantity',
                            label: 'Quantity',
                            required: true,
                            scale: 2,
                            defaultDecimal: '1',
                        ),
                        Select::make('unit_id')
                            ->searchable()
                            ->label('Unit')
                            ->disabled(fn (callable $get) => (bool) $get('../../is_locked'))
                            ->options(function (callable $get) {
                                $productId = $get('product_id');
                                if (!$productId) {
                                    return [];
                                }
                                $product = \App\Models\Product::find($productId);
                                if (!$product) {
                                    return [];
                                }
                                return app(\App\Services\UnitConversionService::class)->getUnitOptions($product, 'sales');
                            })
                            ->live()
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                $productId = $get('product_id');
                                $quantity = \App\Filament\Forms\Components\RoundedIntegerMoneyInput::parseToFloat($get('quantity') ?? 0);
                                if ($productId && $state) {
                                    $product = \App\Models\Product::find($productId);
                                    if ($product) {
                                        $factor = app(\App\Services\UnitConversionService::class)->getConversionFactor($product, (int) $state);
                                        $set('conversion_factor', $factor);
                                        $set('base_quantity', $quantity * $factor);
                                    }
                                }
                            }),
                        TextInput::make('return_reason')
                            ->required()
                            ->label('Return Reason')
                            ->placeholder('e.g. Damaged, Wrong item, Not needed'),
                        Textarea::make('description')
                            ->label('Description')
                            ->disabled(fn (callable $get) => (bool) $get('../../is_locked'))
                            ->rows(1)
                            ->maxLength(255),
                        Hidden::make('base_quantity')
                            ->default(0),
                        Hidden::make('conversion_factor')
                            ->default(1),
                    ])
                    ->defaultItems(0)
                    ->addable(fn (callable $get) => !(bool) $get('is_locked'))
                    ->live()
                    ->reorderable()
                    ->collapsible()
                    ->compact()
                    ->columnSpan('full'),

            ]);
    }
}
