<?php

namespace App\Filament\Resources\SalesInvoices\Schemas;

use App\Filament\Forms\Components\AdditionalChargesSection;
use App\Filament\Forms\Components\NumberInput;
use App\Filament\Forms\Components\RoundedIntegerMoneyInput;
use App\Services\AdditionalChargesHelper;
use App\Forms\Components\SelectWithModal;
use App\Traits\HasAutoGeneratedCode;
use Filament\Actions\Action;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\Placeholder;
use Filament\Forms\Components\Repeater;
use Filament\Forms\Components\Repeater\TableColumn;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Hidden;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Filament\Support\Enums\Alignment;


class SalesInvoiceForm
{
    use HasAutoGeneratedCode;

    /**
     * Get the document type for sales invoices
     */
    protected function getDocumentType(): string
    {
        return 'sales_invoice';
    }

    /**
     * Get the code field name for sales invoices
     */
    protected function getCodeFieldName(): string
    {
        return 'invoice_number';
    }

    protected static function resolveCompanyId(callable $get): ?int
    {
        $companyId = $get('company_id');
        if ($companyId && $companyId !== 'all') {
            return (int) $companyId;
        }
        $selectedCompanyId = session('selected_company_id');
        if ($selectedCompanyId && $selectedCompanyId !== 'all') {
            return (int) $selectedCompanyId;
        }
        return null;
    }

    protected static function calculateTotals(callable $get): array
    {
        $items = $get('items') ?? [];
        $discountPercentage = (float) ($get('discount_percentage') ?? 0);
        $otherCharges = AdditionalChargesHelper::resolveAmount(
            $get('otherCharges'),
            $get('other_charges') ?? 0,
        );
        $subtotal = 0.0;
        $taxTotal = 0.0;

        foreach ($items as $item) {
            $qty = NumberInput::parseToFloat($item['quantity'] ?? 0);
            $price = NumberInput::parseToFloat($item['unit_price'] ?? 0);
            $line = $qty * $price;
            $subtotal += $line;
            $taxId = $item['tax_id'] ?? null;
            if ($taxId) {
                $tax = \App\Models\Tax::find($taxId);
                if ($tax && $tax->tax_percentage) {
                    $lineDiscount = $line * ($discountPercentage / 100);
                    $taxBase = $line - $lineDiscount;
                    $taxTotal += $taxBase * ((float) $tax->tax_percentage) / 100;
                }
            }
        }

        $discountAmount = $subtotal * ($discountPercentage / 100);
        $total = $subtotal - $discountAmount + $otherCharges + $taxTotal;
        $paidAmount = NumberInput::parseToFloat($get('paid_amount') ?? 0);
        $outstanding = $total - $paidAmount;
        return [
            'subtotal' => $subtotal,
            'discount' => $discountAmount,
            'tax' => $taxTotal,
            'total' => $total,
            'outstanding' => $outstanding,
        ];
    }

    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make()
                    ->schema([
                        Select::make('company_id')
                            ->relationship(
                                name: 'company',
                                titleAttribute: 'name',
                                modifyQueryUsing: function ($query) {
                                    $user = auth()->user();
                                    if ($user) {
                                        $userCompanyIds = $user->companies()->pluck('companies.id');
                                        if ($userCompanyIds->isNotEmpty()) {
                                            $query->whereIn('companies.id', $userCompanyIds);
                                        } else {
                                            // If user has no assigned companies, return no results
                                            $query->whereRaw('1 = 0');
                                        }
                                    }
                                }
                            )
                            ->default(function () {
                                $selectedCompanyId = session('selected_company_id');
                                return $selectedCompanyId && $selectedCompanyId !== 'all'
                                    ? $selectedCompanyId
                                    : null;
                            })
                            ->hidden(function () {
                                $selectedCompanyId = session('selected_company_id');
                                return $selectedCompanyId && $selectedCompanyId !== 'all';
                            })
                            ->searchable()
                            ->preload()
                            ->nullable()
                            ->reactive()
                            ->afterStateUpdated(function ($state, callable $set) {
                                // Clear customer and sales order when company changes
                                $set('customer_id', null);
                                $set('sales_order_id', null);
                            })
                            ->columnSpanFull(),
                        Select::make('customer_id')
                            ->label('Customer')
                            ->disabled(fn ($record) => (bool) ($record?->is_locked))
                            ->relationship(
                                name: 'customer',
                                titleAttribute: 'name',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $companyId = self::resolveCompanyId($get);
                                    if ($companyId) {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    return $query->where('is_customer', true)->orderBy('name');
                                }
                            )
                            ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->name} ({$record->contact_code})")
                            ->searchable(['name', 'contact_code'])
                            ->preload()
                            ->required()
                            ->live(onBlur: true)
                            ->afterStateUpdated(function ($state, callable $set) {
                                // Clear sales order when customer changes
                                $set('sales_order_id', null);
                            })
                            ->createOptionForm([
                                TextInput::make('name')
                                    ->label('Name')
                                    ->required(),
                                (new \App\Filament\Resources\Contacts\Schemas\ContactForm)->getCodeField('contact_code', 'Contact Code')
                                    ->unique(\App\Models\Contact::class, 'contact_code', ignoreRecord: true,
                                        modifyRuleUsing: function ($rule) {
                                            // Get the company_id from the session
                                            $companyId = session('selected_company_id');

                                            // If there's a selected company, scope the uniqueness check to that company
                                            if ($companyId && $companyId !== 'all') {
                                                $rule->where('company_id', $companyId);
                                            }
                                            // If no company is selected, the uniqueness check will apply to all records
                                            // This ensures records are unique within their company
                                            return $rule;
                                        },
                                    ),
                                TextInput::make('email')
                                    ->label('Email')
                                    ->email(),
                                TextInput::make('phone')
                                    ->label('Phone')
                                    ->tel(),
                                Hidden::make('is_customer')
                                    ->default(true),
                                Hidden::make('company_id')
                                    ->default(function (callable $get) {
                                        $companyId = $get('company_id') ?: session('selected_company_id');
                                        return ($companyId && $companyId !== 'all') ? $companyId : null;
                                    }),
                                Hidden::make('created_by_user_id')
                                    ->default(function () {
                                        return auth()->id();
                                    }),
                            ])
                            ->createOptionUsing(function (array $data) {
                                $contact = \App\Models\Contact::create($data);
                                return $contact->id;
                            }),
                        Select::make('sales_order_id')
                            ->label('Sales Order')
                            ->disabled(fn ($record) => (bool) ($record?->is_locked))
                            ->nullable()
                            ->relationship(
                                name: 'salesOrder',
                                titleAttribute: 'order_number',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $customerId = $get('customer_id');
                                    $companyId = self::resolveCompanyId($get);

                                    if ($customerId) {
                                        $query->where('customer_id', $customerId);
                                    }

                                    if ($companyId) {
                                        $query->where(function ($q) use ($companyId) {
                                            $q->where('company_id', $companyId)
                                              ->orWhereNull('company_id');
                                        });
                                    }

                                    // Only exclude sales orders that already have locked sales invoices when creating a new record
                                    // Sales order menu creates locked invoices automatically, so this prevents manual creation
                                    // if any invoice was created from sales order menu
                                    $currentRecordId = $get('../../record')?->id ?? null;
                                    if (!$currentRecordId) {
                                        $query->whereDoesntHave('salesInvoices', function ($invoiceQuery) {
                                            $invoiceQuery->where('is_locked', true)
                                                        ->whereNull('sales_invoices.deleted_at');
                                        });
                                    }

                                    return $query->with('customer')->orderBy('order_number');
                                }
                            )
                            ->getOptionLabelFromRecordUsing(fn ($record) => $record->order_number . ' - ' . $record->customer?->name)
                            ->searchable()
                            ->preload()
                            ->reactive()
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                // When sales order is selected, auto-fill customer and items
                                if ($state) {
                                    $salesOrder = \App\Models\SalesOrder::with(['items.product', 'customer'])->find($state);
                                    if ($salesOrder) {
                                        $set('customer_id', $salesOrder->customer_id);

                                        // Auto-fill items from sales order
                                        $items = [];
                                        foreach ($salesOrder->items as $item) {
                                            $items[] = [
                                                'sales_order_item_id' => $item->id,
                                                'product_id' => $item->product_id,
                                                'quantity' => $item->quantity,
                                                'quantity_display' => NumberInput::formatRoundedIntegerDisplay($item->quantity),
                                                'unit_price' => $item->unit_price,
                                                'unit_price_display' => NumberInput::formatRoundedIntegerDisplay($item->unit_price),
                                                'tax_id' => $item->tax_id,
                                                'unit_id' => $item->unit_id,
                                                'description' => $item->description,
                                                'total' => $item->total,
                                                'conversion_factor' => $item->conversion_factor ?? 1,
                                                'base_quantity' => $item->base_quantity ?? $item->quantity,
                                            ];
                                        }
                                        $set('items', $items);

                                        // Set discount and other charges from sales order
                                        $subtotal = collect($items)->sum('total');
                                        $discountAmount = $salesOrder->discount ?? 0;
                                        $chargeRows = AdditionalChargesHelper::rowsForCopy($salesOrder)
                                            ->map(fn (array $row) => array_merge($row, [
                                                'amount_display' => NumberInput::formatRoundedIntegerDisplay($row['amount']),
                                            ]))
                                            ->all();
                                        $otherCharges = AdditionalChargesHelper::sumFromRows($chargeRows);
                                        
                                        // Calculate discount percentage from sales order discount amount
                                        $discountPercentage = $subtotal > 0 ? ($discountAmount / $subtotal) * 100 : 0;
                                        
                                        $set('otherCharges', $chargeRows);
                                        $set('other_charges', $otherCharges);
                                        $set('discount_percentage', $discountPercentage);

                                        // Calculate and update all totals
                                        $dataForCalculation = function($key) use ($items, $discountPercentage, $otherCharges, $chargeRows) {
                                            if ($key === 'items') return $items;
                                            if ($key === 'discount_percentage') return $discountPercentage;
                                            if ($key === 'other_charges') return $otherCharges;
                                            if ($key === 'otherCharges') return $chargeRows;
                                            return null;
                                        };

                                        $c = self::calculateTotals($dataForCalculation);
                                        $set('subtotal', $c['subtotal']);
                                        $set('discount', $c['discount']);
                                        $set('tax_amount', $c['tax']);
                                        $set('total_amount', $c['total']);
                                        $set('outstanding_amount', $c['outstanding']);
                                    }
                                } else if (!$state) {
                                    // Clear items if no sales order selected
                                    $set('items', []);
                                    $set('otherCharges', []);
                                    $set('other_charges', 0);
                                    $set('discount_percentage', 0);
                                    $set('total_amount', 0);
                                }
                            }),
                        (new static)->getCodeField('invoice_number', 'Invoice No.')
                            ->unique('sales_invoices', 'invoice_number', ignoreRecord: true,
                                modifyRuleUsing: fn ($rule) => $rule->where(function ($query) {
                                    $companyId = session('selected_company_id');
                                    if ($companyId && $companyId !== 'all') {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    $query->whereNull('deleted_at');
                                    return $query;
                                })
                            ),
                        DatePicker::make('date')
                            ->label('Invoice Date')
                            ->required()
                            ->default(now())
                            ->live()
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                // Recalculate due date when invoice date changes
                                $paymentTermId = $get('payment_term_id');
                                if ($paymentTermId) {
                                    $paymentTerm = \App\Models\PaymentTerm::find($paymentTermId);
                                    if ($paymentTerm && $state) {
                                        $dueDate = \Carbon\Carbon::parse($state)->addDays($paymentTerm->due_days);
                                        $set('due_date', $dueDate->format('Y-m-d'));
                                    }
                                }
                            }),
                        Select::make('payment_term_id')
                            ->label('Payment Term')
                            ->nullable()
                            ->relationship(
                                name: 'paymentTerm',
                                titleAttribute: 'name',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $companyId = self::resolveCompanyId($get);
                                    if ($companyId) {
                                        $query->where('company_id', $companyId);
                                    }
                                    return $query->where('is_active', true)->orderBy('due_days');
                                }
                            )
                            ->searchable()
                            ->preload()
                            ->live()
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                if ($state) {
                                    $paymentTerm = \App\Models\PaymentTerm::find($state);
                                    if ($paymentTerm) {
                                        $invoiceDate = $get('date') ?? now()->format('Y-m-d');
                                        $dueDate = \Carbon\Carbon::parse($invoiceDate)->addDays($paymentTerm->due_days);
                                        $set('due_date', $dueDate->format('Y-m-d'));
                                    }
                                } else {
                                    $set('due_date', null);
                                }
                            }),
                        DatePicker::make('due_date')
                            ->nullable()
                            ->label('Due Date')
                            ->disabled()
                            ->dehydrated(),
                        TextInput::make('reference_no')
                            ->maxLength(255)
                            ->label('Reference No'),
                        Textarea::make('description')
                            ->rows(1)
                            ->maxLength(65535)
                            ->label('Description'),
                        Select::make('status')
                            ->label('Status')
                            ->options(function ($get, $record) {
                                // If the record doesn't exist (creating new) or status is draft, show only draft/posted
                                if (!$record || $get('status') === 'draft') {
                                    return [
                                        'draft' => 'Draft',
                                    ];
                                }
                                // Otherwise, show all options
                                return [
                                    'draft' => 'Draft',
                                    'posted' => 'Posted',
                                    'sent' => 'Sent',
                                    'overdue' => 'Overdue',
                                    'paid' => 'Paid',
                                    'partially_paid' => 'Partially Paid',
                                    'written_off' => 'Written Off',
                                    'cancelled' => 'Cancelled',
                                ];
                            })
                            ->default('draft')
                            ->required()
                            ->native(false)
                            ->live()
                            ->disabled(function ($get, $record) {
                                // Disable the field if the record exists and status is not draft
                                return $record && $record->status !== 'draft';
                            }),
                        FileUpload::make('attachments')
                            ->label('Attachments')
                            ->multiple()
                            ->directory('invoices')
                            ->maxFiles(20)
                            ->columnSpanFull()
                            ->disabled(fn ($record) => (bool) ($record?->is_locked)),
                        \Filament\Forms\Components\Hidden::make('total_amount')
                            ->default(0)
                            ->dehydrated(),
                        \Filament\Forms\Components\Hidden::make('outstanding_amount')
                            ->default(0)
                            ->dehydrated(),
                        \Filament\Forms\Components\Hidden::make('subtotal')
                            ->default(0)
                            ->dehydrated(),
                        \Filament\Forms\Components\Hidden::make('discount')
                            ->default(0)
                            ->dehydrated(),
                        \Filament\Forms\Components\Hidden::make('tax_amount')
                            ->default(0)
                            ->dehydrated(),
                        \Filament\Forms\Components\Hidden::make('paid_amount')
                            ->default(0)
                            ->dehydrated(),
                    ])
                    ->columns(3)
                    ->columnSpanFull(),

                // Invoice Items
                Repeater::make('items')
                    ->relationship()
                    ->hiddenLabel()
                    ->addActionLabel('Add New Item')
                    ->required()
                    ->addable(fn (callable $get) => !(bool) $get('is_locked'))
                    ->table([
                        TableColumn::make('Product')->width('20%')->alignment(Alignment::Start),
                        TableColumn::make('Quantity')->width('10%')->alignment(Alignment::End),
                        TableColumn::make('Unit Price')->width('14%')->alignment(Alignment::End),
                        TableColumn::make('Tax')->width('11%')->alignment(Alignment::Start),
                        TableColumn::make('Unit')->width('11%')->alignment(Alignment::Start),
                        TableColumn::make('Description')->width('16%')->alignment(Alignment::Start),
                        TableColumn::make('Total')->width('10%')->alignment(Alignment::End),
                    ])
                    ->schema([
                        Hidden::make('sales_order_item_id'),
                        Select::make('product_id')
                            ->required()
                            ->searchable(['name', 'code'])
                            ->label('Product')
                            ->disabled(fn (callable $get) => (bool) $get('../../is_locked'))
                            ->relationship(
                                name: 'product',
                                titleAttribute: 'name',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $companyId = self::resolveCompanyId($get);
                                    if ($companyId) {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    return $query->orderBy('name');
                                }
                            )
                            ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->name} ({$record->code})")
                            ->preload()
                            ->live()
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                $product = \App\Models\Product::find($state);
                                if ($product) {
                                    if ($product->selling_price) {
                                        $set('unit_price', $product->selling_price);
                                        $set('unit_price_display', NumberInput::formatRoundedIntegerDisplay($product->selling_price));
                                    }
                                    if ($product->unit_id) {
                                        $set('unit_id', $product->unit_id);
                                        $set('conversion_factor', 1);
                                        $set('base_quantity', NumberInput::parseToFloat($get('quantity') ?? 0));
                                    }
                                    if ($product->description) {
                                        $set('description', $product->description);
                                    }
                                    // Set tax from product if available
                                    if ($product->tax_id) {
                                        $set('tax_id', $product->tax_id);
                                    }

                                    // Calculate line total and invoice totals
                                    $quantity = NumberInput::parseToFloat($get('quantity') ?? 0) ?: 1; // Default to 1 if 0
                                    $unitPrice = $product->selling_price ?? 0;
                                    $lineTotal = $quantity * $unitPrice;
                                    $set('total', $lineTotal);

                                    // Recalculate invoice totals
                                    $c = self::calculateTotals($get);
                                    $set('../../subtotal', $c['subtotal']);
                                    $set('../../discount', $c['discount']);
                                    $set('../../tax_amount', $c['tax']);
                                    $set('../../total_amount', $c['total']);
                                    $set('../../outstanding_amount', $c['outstanding']);
                                }
                            })
                            ->createOptionForm([
                                TextInput::make('name')
                                    ->label('Name')
                                    ->required(),
                                (new \App\Filament\Resources\Products\Schemas\ProductForm)->getCodeField('code', 'Product Code')
                                    ->unique(
                                        \App\Models\Product::class,
                                        'code',
                                        ignoreRecord: true,
                                        modifyRuleUsing: function ($rule) {
                                            // Get the company_id from the session
                                            $companyId = session('selected_company_id');

                                            // If there's a selected company, scope the uniqueness check to that company
                                            if ($companyId && $companyId !== 'all') {
                                                $rule->where('company_id', $companyId);
                                            }
                                            // If no company is selected, the uniqueness check will apply to all records
                                            // This ensures records are unique within their company
                                            return $rule;
                                        },
                                    ),
                                Select::make('product_group_id')
                                    ->label('Product Group')
                                    ->relationship(
                                        "productGroup",
                                        "name",
                                        modifyQueryUsing: function ($query) {
                                            $selectedCompanyId = session('selected_company_id');
                                            if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                                                $query->where('company_id', $selectedCompanyId);
                                            }
                                            return $query;
                                        }
                                    )
                                    ->searchable()
                                    ->preload()
                                    ->required(),
                                ...RoundedIntegerMoneyInput::schema(
                                    name: 'selling_price',
                                    label: 'Selling Price',
                                    required: false,
                                    defaultDecimal: '0.00',
                                ),
                                Select::make('unit_id')
                                    ->label('Unit')
                                    ->searchable()
                                    ->options(function () {
                                        $selectedCompanyId = session('selected_company_id');
                                        $q = \App\Models\Unit::query();
                                        if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                                            $q->where('company_id', $selectedCompanyId);
                                        } else {
                                            $q->whereNull('company_id');
                                        }
                                        return $q->orderBy('name')->pluck('name', 'id')->toArray();
                                    }),
                                Textarea::make('description')
                                    ->label('Description')
                                    ->rows(2),
                                Hidden::make('company_id')
                                    ->default(function () {
                                        $selectedCompanyId = session('selected_company_id');
                                        return ($selectedCompanyId && $selectedCompanyId !== 'all') ? $selectedCompanyId : null;
                                    }),
                                Hidden::make('created_by_user_id')
                                    ->default(function () {
                                        return auth()->id();
                                    }),
                            ])
                            ->createOptionUsing(function (array $data) {
                                $product = \App\Models\Product::create($data);
                                return $product->id;
                            }),
                        ...RoundedIntegerMoneyInput::schema(
                            name: 'quantity',
                            label: 'Quantity',
                            required: true,
                            defaultDecimal: '1.00',
                            afterUpdated: function ($decimal, callable $set, callable $get) {
                                $quantity = NumberInput::parseToFloat($decimal);
                                $unitPrice = NumberInput::parseToFloat($get('unit_price') ?? 0);
                                $set('total', $quantity * $unitPrice);

                                $c = self::calculateTotals($get);
                                $set('subtotal', $c['subtotal']);
                                $set('discount', $c['discount']);
                                $set('tax_amount', $c['tax']);
                                $set('total_amount', $c['total']);
                                $set('outstanding_amount', $c['outstanding']);
                            },
                        ),
                        ...RoundedIntegerMoneyInput::schema(
                            name: 'unit_price',
                            label: 'Unit Price',
                            required: true,
                            afterUpdated: function ($decimal, callable $set, callable $get) {
                                $quantity = NumberInput::parseToFloat($get('quantity') ?? 0);
                                $unitPrice = NumberInput::parseToFloat($decimal);
                                $set('total', $quantity * $unitPrice);

                                $c = self::calculateTotals($get);
                                $set('subtotal', $c['subtotal']);
                                $set('discount', $c['discount']);
                                $set('tax_amount', $c['tax']);
                                $set('total_amount', $c['total']);
                                $set('outstanding_amount', $c['outstanding']);
                            },
                        ),
                        Select::make('tax_id')
                            ->searchable()
                            ->label('Tax')
                            ->relationship(
                                'tax',
                                'name',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $companyId = self::resolveCompanyId($get);
                                    if ($companyId) {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    return $query->orderBy('name');
                                }
                            )
                            ->getOptionLabelFromRecordUsing(fn ($record) => $record->name)
                            ->preload()
                            ->live(onBlur: true)
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                $c = self::calculateTotals($get);
                                $set('subtotal', $c['subtotal']);
                                $set('discount', $c['discount']);
                                $set('tax_amount', $c['tax']);
                                $set('total_amount', $c['total']);
                                $set('outstanding_amount', $c['outstanding']);
                            }),
                        Select::make('unit_id')
                            ->searchable()
                            ->label('Unit')
                            ->options(function (callable $get) {
                                $productId = $get('product_id');
                                if (!$productId) {
                                    return [];
                                }
                                $product = \App\Models\Product::find($productId);
                                if (!$product) {
                                    return [];
                                }
                                return app(\App\Services\UnitConversionService::class)->getUnitOptions($product, 'sales');
                            })
                            ->live()
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                // Unit only records UOM; do not overwrite Unit Price.
                                $productId = $get('product_id');
                                $quantity = NumberInput::parseToFloat($get('quantity') ?? 0);
                                if ($productId && $state) {
                                    $product = \App\Models\Product::find($productId);
                                    if ($product) {
                                        $service = app(\App\Services\UnitConversionService::class);
                                        $factor = $service->getConversionFactor((int) $state, $product->unit_id);
                                        $set('conversion_factor', $factor);
                                        $set('base_quantity', $quantity * $factor);
                                    }
                                }
                            }),

                        Textarea::make('description')
                            ->label('Description')
                            ->rows(1),
                        \Filament\Forms\Components\Hidden::make('base_quantity')
                            ->default(0),
                        \Filament\Forms\Components\Hidden::make('conversion_factor')
                            ->default(1),
                        \Filament\Forms\Components\Hidden::make('total')
                            ->default(0)
                            ->dehydrated(),
                        Placeholder::make('total_display')
                            ->label('Total')
                            ->content(function ($get) {
                                $quantity = NumberInput::parseToFloat($get('quantity') ?? 0);
                                $unitPrice = NumberInput::parseToFloat($get('unit_price') ?? 0);
                                $total = $quantity * $unitPrice;
                                return number_format($total, 0, ',', '.');
                            })
                            ->extraAttributes([
                                'class' => 'font-semibold text-green-600 py-2 px-3 bg-gray-50 rounded-md border border-gray-200'
                            ]),
                    ])
                    ->defaultItems(0)
                    ->live()
                    ->reorderable()
                    ->collapsible()
                    ->compact()
                    ->columnSpan('full')
                    ->afterStateUpdated(function ($state, callable $set, callable $get) {
                        // Trigger total recalculation when items change
                        $c = self::calculateTotals($get);
                        $set('subtotal', $c['subtotal']);
                        $set('discount', $c['discount']);
                        $set('tax_amount', $c['tax']);
                        $set('total_amount', $c['total']);
                        $set('outstanding_amount', $c['outstanding']);
                    }),

                Section::make()
                    ->schema([
                        Placeholder::make('empty_col_1')
                            ->hiddenLabel()
                            ->columnSpan(1),
                        Placeholder::make('subtotal_display')
                            ->inlineLabel()
                            ->label('Subtotal')
                            ->content(function (callable $get) {
                                $c = self::calculateTotals($get);
                                return 'Rp ' . number_format($c['subtotal'], 0, ',', '.');
                            })
                            ->live()
                            ->reactive()
                            ->extraAttributes(['style' => 'text-align:right'])
                            ->columnSpan(1),
                        AdditionalChargesSection::make('sales', function (callable $set, callable $get): void {
                            $c = self::calculateTotals($get);
                            $set('subtotal', $c['subtotal']);
                            $set('discount', $c['discount']);
                            $set('tax_amount', $c['tax']);
                            $set('total_amount', $c['total']);
                            $set('outstanding_amount', $c['outstanding']);
                        }),
                        Placeholder::make('empty_col_3')
                            ->hiddenLabel()
                            ->columnSpan(1),
                        TextInput::make('discount_percentage')
                            ->default(0)
                            ->numeric()
                            ->inlineLabel()
                            ->label('Discount')
                            ->suffix('%')
                            ->live()
                            ->reactive()
                            ->afterStateHydrated(function ($component, $state, $record) {
                                if ($record && $record->subtotal > 0 && $record->discount > 0) {
                                    $discountPercentage = ($record->discount / $record->subtotal) * 100;
                                    $component->state($discountPercentage);
                                } else {
                                    $component->state(0);
                                }
                            })
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                $c = self::calculateTotals($get);
                                $set('subtotal', $c['subtotal']);
                                $set('discount', $c['discount']);
                                $set('tax_amount', $c['tax']);
                                $set('total_amount', $c['total']);
                                $set('outstanding_amount', $c['outstanding']);
                            })
                            ->extraInputAttributes(['style' => 'text-align:right'])
                            ->columnSpan(1),
                        Placeholder::make('empty_col_4')
                            ->hiddenLabel()
                            ->columnSpan(1),
                        Placeholder::make('discount_amount_display')
                            ->inlineLabel()
                            ->label('Discount Amount')
                            ->content(function (callable $get) {
                                $c = self::calculateTotals($get);
                                return 'Rp ' . number_format($c['discount'], 0, ',', '.');
                            })
                            ->live()
                            ->reactive()
                            ->alignEnd()
                            ->columnSpan(1),
                        Placeholder::make('empty_col_5')
                            ->hiddenLabel()
                            ->columnSpan(1),
                        Placeholder::make('tax_amount')
                            ->inlineLabel()
                            ->label('Tax Amount')
                            ->content(function (callable $get) {
                                $c = self::calculateTotals($get);
                                return 'Rp ' . number_format($c['tax'], 0, ',', '.');
                            })
                            ->live()
                            ->reactive()
                            ->alignEnd()
                            ->columnSpan(1),
                        Placeholder::make('empty_col_6')
                            ->hiddenLabel()
                            ->columnSpan(1),
                        Placeholder::make('total_amount_display')
                            ->inlineLabel()
                            ->label('Total Amount')
                            ->live()
                            ->reactive()
                            ->content(function (callable $get) {
                                $c = self::calculateTotals($get);
                                return 'Rp ' . number_format($c['total'], 0, ',', '.');
                            })
                            ->extraAttributes([
                                'class' => 'font-bold text-lg text-green-600'
                            ])
                            ->alignEnd()
                            ->columnSpan(1),
                    ])
                    ->columns(2)
                    ->columnSpanFull(),

            ]);
    }
}
