<?php

namespace App\Filament\Resources\BankAccounts\Schemas;

use App\Filament\Forms\Components\NumberInput;
use App\Traits\HasAutoGeneratedCode;
use Filament\Actions\Action;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Filament\Support\RawJs;

class BankAccountForm
{
    use HasAutoGeneratedCode;

    /**
     * Get the document type for bank accounts
     */
    protected function getDocumentType(): string
    {
        return 'bank_account';
    }

    /**
     * Get the code field name for bank accounts
     */
    protected function getCodeFieldName(): string
    {
        return 'account_number';
    }
    public static function configure(Schema $schema): Schema
    {
        return $schema->components([
            Section::make(__("Account Information"))
                ->schema([
                    ((new static)->getCodeField('account_number', __("Account Number")))
                        ->required(false)
                        ->columnSpanFull()
                        ->unique(
                            \App\Models\BankAccount::class,
                            'account_number',
                            ignoreRecord: true,
                            modifyRuleUsing: function ($rule) {
                                // Get the company_id from the form
                                $companyId = session('selected_company_id');
                                if ($companyId) {
                                    $rule->where('company_id', $companyId);
                                }
                                return $rule;
                            },
                        ),
                    TextInput::make("account_name")
                        ->label(__("Account Name"))
                        ->required()
                        ->maxLength(200)
                        ->columnSpanFull(),
                    Select::make("account_type")
                        ->label(__("Account Type"))
                        ->options([
                            "checking" => __("Checking"),
                            "savings" => __("Savings"),
                            "credit_card" => __("Credit Card"),
                            "investment" => __("Investment"),
                        ])
                        ->default("checking")
                        ->required(),
                    Select::make("bank_id")
                        ->label(__("Bank"))
                        ->relationship(
                            "bank",
                            "name",
                            modifyQueryUsing: function ($query) {
                                $selectedCompanyId = session('selected_company_id');
                                if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                                    $query->where('company_id', $selectedCompanyId);
                                }
                                return $query;
                            }
                        )
                        ->required()
                        ->searchable()
                        ->preload(),
                    Select::make("account_id")
                        ->label(__("GL Account"))
                        ->options(function ($record) {
                            $selectedCompanyId = session('selected_company_id');
                            $query = \App\Models\Account::where('is_header', false)
                                ->where('is_active', true)
                                ->where('is_cash_bank', true); // Only cash/bank accounts

                            if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                                $query->where(function ($q) use ($selectedCompanyId) {
                                    $q->where('company_id', $selectedCompanyId)
                                        ->orWhereNull('company_id'); // allow global accounts
                                });
                            }

                            $options = $query->orderBy('code')
                                ->limit(100)
                                ->get()
                                ->mapWithKeys(fn ($account) => [
                                    $account->id => "{$account->code} - {$account->name}",
                                ])->toArray();

                            // If editing and current account_id is not in options, add it
                            if ($record && $record->account_id && !isset($options[$record->account_id])) {
                                $currentAccount = \App\Models\Account::find($record->account_id);
                                if ($currentAccount) {
                                    $options[$currentAccount->id] = "{$currentAccount->code} - {$currentAccount->name}";
                                }
                            }

                            return $options;
                        })
                        ->getSearchResultsUsing(function (string $search) {
                            $selectedCompanyId = session('selected_company_id');
                            $query = \App\Models\Account::where('is_header', false)
                                ->where('is_active', true)
                                ->where('is_cash_bank', true)
                                ->where(function ($query) use ($search) {
                                    $query->where('code', 'like', "%{$search}%")
                                        ->orWhere('name', 'like', "%{$search}%");
                                });

                            if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                                $query->where(function ($q) use ($selectedCompanyId) {
                                    $q->where('company_id', $selectedCompanyId)
                                        ->orWhereNull('company_id');
                                });
                            }

                            return $query->orderBy('code')
                                ->limit(50)
                                ->get()
                                ->mapWithKeys(fn ($account) => [
                                    $account->id => "{$account->code} - {$account->name}",
                                ]);
                        })
                        ->getOptionLabelUsing(function ($value) {
                            if (!$value) return null;
                            $account = \App\Models\Account::find($value);
                            return $account ? "{$account->code} - {$account->name}" : $value;
                        })
                        ->searchable()
                        ->preload()
                        ->required()
                        ->helperText(__('Pilih akun dari Chart of Accounts yang digunakan untuk transaksi kas/bank ini.')),
                ])
                ->columns(2),

            Section::make(__("Financial Information"))
                ->schema([
                    NumberInput::make("balance")
                        ->label(__("Balance"))
                        ->decimal(true)
                        ->prefix('Rp')
                        ->default(0)
                        ->required()
                        ->mask(RawJs::make('$money($input, \',\', \'.\')'))
                        ->stripCharacters('.'),
                ])
                ->columns(2),

            Section::make(__("Company & Status"))
                ->schema([
                    Select::make("company_id")
                        ->label(__("Company"))
                        ->relationship(
                            name: 'company',
                            titleAttribute: 'name',
                            modifyQueryUsing: function ($query) {
                                $user = auth()->user();
                                if ($user) {
                                    $userCompanyIds = $user->companies()->pluck('companies.id');
                                    if ($userCompanyIds->isNotEmpty()) {
                                        $query->whereIn('companies.id', $userCompanyIds);
                                    } else {
                                        // If user has no assigned companies, return no results
                                        $query->whereRaw('1 = 0');
                                    }
                                }
                            }
                        )
                        ->default(function () {
                            $selectedCompanyId = session("selected_company_id");
                            $user = auth()->user();
                            if ($selectedCompanyId) {
                                // Verify user has access to this company
                                if ($user && $user->companies()->where('companies.id', $selectedCompanyId)->exists()) {
                                    return $selectedCompanyId;
                                }
                            }
                            return null;
                        })
                        ->hidden()
                        ->searchable()
                        ->preload()
                        ->required(),
                    Toggle::make("is_active")
                        ->label(__("Active"))
                        ->required()
                        ->default(true),
                ])
                ->columns(2),

            Section::make(__("Additional Information"))
                ->schema([
                    Select::make("created_by_user_id")
                        ->relationship("createdByUser", "name")
                        ->default(function () {
                            return auth()->id();
                        })
                        ->disabled()
                        ->required()
                        ->label(__("Created By")),
                ])
                ->columns(2),
        ]);
    }
}
