<?php

namespace Database\Seeders;

use App\Models\DocumentNumbering;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DocumentNumberingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $documentTypes = [
            [
                'document_type' => 'advance_disbursement',
                'prefix' => 'AD',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'monthly',
                'is_active' => true,
            ],
            [
                'document_type' => 'advance_receipt',
                'prefix' => 'AR',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'monthly',
                'is_active' => true,
            ],
            [
                'document_type' => 'cash_disbursement',
                'prefix' => 'CD',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'monthly',
                'is_active' => true,
            ],
            [
                'document_type' => 'cash_receipt',
                'prefix' => 'CR',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'monthly',
                'is_active' => true,
            ],
            [
                'document_type' => 'cash_transfer',
                'prefix' => 'CT',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'monthly',
                'is_active' => true,
            ],
            [
                'document_type' => 'check_disbursement',
                'prefix' => 'CKD',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'monthly',
                'is_active' => true,
            ],
            [
                'document_type' => 'delivery_document',
                'prefix' => 'DO',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'monthly',
                'is_active' => true,
            ],
            [
                'document_type' => 'fixed_asset_transaction',
                'prefix' => 'FAT',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'monthly',
                'is_active' => true,
            ],
            [
                'document_type' => 'goods_receipt',
                'prefix' => 'GR',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'monthly',
                'is_active' => true,
            ],
            [
                'document_type' => 'inventory_adjustment',
                'prefix' => 'IA',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'monthly',
                'is_active' => true,
            ],
            [
                'document_type' => 'journal_entry',
                'prefix' => 'JE',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'monthly',
                'is_active' => true,
            ],
            [
                'document_type' => 'overpayment_receipt',
                'prefix' => 'OR',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'monthly',
                'is_active' => true,
            ],
            [
                'document_type' => 'overpayment_refund',
                'prefix' => 'ORF',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'monthly',
                'is_active' => true,
            ],
            [
                'document_type' => 'payable_payment',
                'prefix' => 'PP',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'monthly',
                'is_active' => true,
            ],
            [
                'document_type' => 'purchase_invoice',
                'prefix' => 'PINV',
                'format' => '{prefix}{year}{month}{number}',
                'format_components' => ['prefix', 'year_full', 'month_short', 'number'],
                'next_number' => 0,
                'reset_period' => 'monthly',
                'is_active' => true,
            ],
            [
                'document_type' => 'purchase_order',
                'prefix' => 'PO',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'monthly',
                'is_active' => true,
            ],
            [
                'document_type' => 'purchase_return',
                'prefix' => 'PR',
                'format' => '{prefix}{year}{month}{number}',
                'format_components' => ['prefix', 'year_full', 'month_short', 'number'],
                'next_number' => 0,
                'reset_period' => 'monthly',
                'is_active' => true,
            ],
            [
                'document_type' => 'receivable_payment',
                'prefix' => 'RP',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'monthly',
                'is_active' => true,
            ],
            [
                'document_type' => 'sales_invoice',
                'prefix' => 'INV',
                'format' => '{prefix}{year}{month}{number}',
                'format_components' => ['prefix', 'year_full', 'month_short', 'number'],
                'next_number' => 0,
                'reset_period' => 'monthly',
                'is_active' => true,
            ],
            [
                'document_type' => 'payment_term',
                'prefix' => 'PT',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'yearly',
                'is_active' => true,
            ],
            [
                'document_type' => 'sales_order',
                'prefix' => 'SO',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'monthly',
                'is_active' => true,
            ],
            [
                'document_type' => 'sales_return',
                'prefix' => 'SR',
                'format' => '{prefix}{year}{month}{number}',
                'format_components' => ['prefix', 'year_full', 'month_short', 'number'],
                'next_number' => 0,
                'reset_period' => 'monthly',
                'is_active' => true,
            ],
            [
                'document_type' => 'stock_opname',
                'prefix' => 'STK',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'monthly',
                'is_active' => true,
            ],
            [
                'document_type' => 'warehouse_transfer',
                'prefix' => 'WT',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'monthly',
                'is_active' => true,
            ],
            [
                'document_type' => 'product',
                'prefix' => 'PRD',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'never',
                'is_active' => true,
            ],
            [
                'document_type' => 'fixed_asset',
                'prefix' => 'FA',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'never',
                'is_active' => true,
            ],
            [
                'document_type' => 'unit_measurement',
                'prefix' => 'UM',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'never',
                'is_active' => true,
            ],
            [
                'document_type' => 'bank_account',
                'prefix' => 'BA',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'never',
                'is_active' => true,
            ],
            [
                'document_type' => 'warehouse',
                'prefix' => 'WH',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'never',
                'is_active' => true,
            ],
            [
                'document_type' => 'department',
                'prefix' => 'DPT',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'never',
                'is_active' => true,
            ],
            [
                'document_type' => 'tax',
                'prefix' => 'TAX',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'never',
                'is_active' => true,
            ],
            [
                'document_type' => 'expedition',
                'prefix' => 'EXP',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'never',
                'is_active' => true,
            ],
            [
                'document_type' => 'contact',
                'prefix' => 'CT',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'never',
                'is_active' => true,
            ],
            [
                'document_type' => 'bank',
                'prefix' => 'BK',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'never',
                'is_active' => true,
            ],
            [
                'document_type' => 'business_type',
                'prefix' => 'BT',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'never',
                'is_active' => true,
            ],
            [
                'document_type' => 'payment_term',
                'prefix' => 'PT',
                'format' => '{prefix}{year}{number}',
                'format_components' => ['prefix', 'year_full', 'number'],
                'next_number' => 0,
                'reset_period' => 'never',
                'is_active' => true,
            ],
            [
                'document_type' => 'project',
                'prefix' => 'PRJ',
                'format' => '{prefix}{year}{month}',
                'format_components' => ['prefix', 'year_full', 'month_short', 'day', 'sequence'],
                'next_number' => 1,
                'reset_period' => 'daily',
                'is_active' => true,
            ],
            [
                'document_type' => 'fixed_asset_category',
                'prefix' => 'FAC',
                'format' => '{prefix}{number}',
                'format_components' => ['prefix', 'number'],
                'next_number' => 1,
                'reset_period' => 'never',
                'is_active' => true,
            ],
        ];

        foreach ($documentTypes as $documentType) {
            DocumentNumbering::updateOrCreate(
                [
                    'document_type' => $documentType['document_type'],
                    'company_id' => null, // Global setting
                ],
                [
                    'prefix' => $documentType['prefix'],
                    'format' => $documentType['format'],
                    'format_components' => $documentType['format_components'],
                    'next_number' => $documentType['next_number'],
                    'reset_period' => $documentType['reset_period'],
                    'is_active' => $documentType['is_active'],
                    'created_by_user_id' => 1, // Default user
                ]
            );
        }
    }
}
