<?php

namespace App\Filament\Resources\CashDisbursements\Schemas;

use App\Traits\HasAutoGeneratedCode;
use App\Forms\Components\SelectWithModal;
use App\Filament\Forms\Components\NumberInput;
use App\Filament\Forms\Components\RoundedIntegerMoneyInput;
use Filament\Forms\Components\Section as FormSection;
use Filament\Forms\Components\Select as FormSelect;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\Placeholder;
use Filament\Forms\Components\Repeater;
use Filament\Forms\Components\Repeater\TableColumn;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Filament\Support\Enums\Alignment;

class CashDisbursementForm
{
    use HasAutoGeneratedCode;

    /**
     * Parse number from Indonesian format (removes thousand separators)
     */
    protected static function parseNumber($value): float
    {
        if ($value === null || $value === '') {
            return 0.0;
        }
        
        $v = (string) $value;
        
        $v = preg_replace('/Rp\s*/i', '', $v);
        
        $v = str_replace([',', '.'], '', $v);
        
        return is_numeric($v) ? (float) $v : 0.0;
    }

    /**
     * Get the document type for cash disbursements
     */
    protected function getDocumentType(): string
    {
        return 'cash_disbursement';
    }

    /**
     * Get the code field name for cash disbursements
     */
    protected function getCodeFieldName(): string
    {
        return 'disbursement_number';
    }
    public static function configure(Schema $schema): Schema
    {
        return $schema->components([
            Section::make()
                ->schema([
                    Select::make("company_id")
                        ->label(__("Company"))
                        ->relationship("company", "name")
                        ->default(function () {
                            $selectedCompanyId = session("selected_company_id");
                            if (
                                $selectedCompanyId &&
                                $selectedCompanyId !== "all"
                            ) {
                                return $selectedCompanyId;
                            }
                            return null; 
                        })
                        ->hidden(function () {
                            $selectedCompanyId = session("selected_company_id");
                            return $selectedCompanyId &&
                                $selectedCompanyId !== "all";
                        })
                        ->required(function () {
                            $selectedCompanyId = session("selected_company_id");
                            return !(
                                $selectedCompanyId &&
                                $selectedCompanyId === "all"
                            );
                        })
                        ->searchable()
                        ->preload()
                        ->columnSpanFull(),
                    DatePicker::make("date")
                        ->label(__("Disbursement Date"))
                        ->required()
                        ->default(now()),
                    TextInput::make("reference_no")
                        ->maxLength(255)
                        ->label(__("Reference Number")),
                    (new static)->getCodeField("disbursement_number", __("Disbursement Number"))
                        ->unique(
                            \App\Models\CashDisbursement::class,
                            'disbursement_number',
                            ignoreRecord: true,
                            modifyRuleUsing: function ($rule) {
                                return $rule->whereNull('deleted_at');
                            },
                        ),
                    Select::make("from_account_id")
                        ->label(__("From Cash / Bank"))
                        ->relationship("fromAccount", "name")
                        ->options(function () {
                            $selectedCompanyId = session('selected_company_id');
                            $query = \App\Models\Account::where('is_header', false)
                                ->where('is_active', true)
                                ->where('is_cash_bank', true); 

                            if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                                $query->where(function ($q) use ($selectedCompanyId) {
                                    $q->where('company_id', $selectedCompanyId); 
                                });
                            }

                            return $query->orderBy('code')
                                ->limit(100)
                                ->get()
                                ->mapWithKeys(fn ($account) => [
                                    $account->id => "{$account->code} - {$account->name}",
                                ]);
                        })
                        ->getSearchResultsUsing(function (string $search) {
                            $selectedCompanyId = session('selected_company_id');
                            $query = \App\Models\Account::where('is_header', false)
                                ->where('is_active', true)
                                ->where('is_cash_bank', true)
                                ->where(function ($query) use ($search) {
                                    $query->whereRaw('LOWER(code) LIKE ?', ['%' . strtolower($search) . '%'])
                                        ->orWhereRaw('LOWER(name) LIKE ?', ['%' . strtolower($search) . '%']);
                                });

                            if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                                $query->where(function ($q) use ($selectedCompanyId) {
                                    $q->where('company_id', $selectedCompanyId)
                                        ->orWhereNull('company_id');
                                });
                            }

                            return $query->orderBy('code')
                                ->limit(50)
                                ->get()
                                ->mapWithKeys(fn ($account) => [
                                    $account->id => "{$account->code} - {$account->name}",
                                ]);
                        })
                        ->getOptionLabelUsing(function ($value) {
                            $account = \App\Models\Account::find($value);
                            return $account ? "{$account->code} - {$account->name}" : $value;
                        })
                        ->searchable()
                        ->preload()
                        ->required()
                        ->helperText(__('Select a cash/bank account from the Chart of Accounts.')),
                    Textarea::make("description")
                        ->rows(1)
                        ->maxLength(65535)
                        ->label(__("Description")),
                ])
                ->columns(3)
                ->columnSpanFull(),

            Repeater::make("items")
                ->hiddenLabel()
                ->dehydrated(true) 
                ->addActionLabel(__("Add New Item"))
                ->defaultItems(1)
                ->reactive()
                ->afterStateUpdated(function (callable $set, callable $get) {
                    $items = $get('items') ?? [];
                    $total = 0;
                    foreach ($items as $item) {
                        $itemTotal = NumberInput::parseToFloat($item['amount'] ?? 0);
                        $total += $itemTotal;
                    }
                    $set('total', $total);
                })
                ->table([
                    TableColumn::make(__("Account"))
                        ->width("30%")
                        ->alignment(Alignment::Start),
                    TableColumn::make(__("Description"))
                        ->width("40%")
                        ->alignment(Alignment::Start),
                    TableColumn::make(__("Total"))
                        ->width("30%")
                        ->alignment(Alignment::End),
                ])
                ->schema([
                    Select::make("account_id")
                        ->required()
                        ->searchable()
                        ->preload()
                        ->label(__("Account"))
                        ->dehydrated(true)
                        ->getSearchResultsUsing(function (string $search) {
                            $globalCompanyId = session('selected_company_id');

                            $query = \App\Models\Account::where('is_header', false)
                                ->where('is_active', true)
                                ->where(function ($query) use ($search) {
                                    $query->whereRaw('LOWER(code) LIKE ?', ['%' . strtolower($search) . '%'])
                                        ->orWhereRaw('LOWER(name) LIKE ?', ['%' . strtolower($search) . '%']);
                                });

                            if ($globalCompanyId && $globalCompanyId !== 'all') {
                                $query->where('company_id', $globalCompanyId);
                            }

                            return $query->orderBy('code')->limit(50)->get()->mapWithKeys(fn ($account) => [
                                $account->id => "{$account->code} - {$account->name}",
                            ]);
                        })
                        ->options(function () {
                            $globalCompanyId = session('selected_company_id');
                            
                            $query = \App\Models\Account::where('is_header', false)
                                ->where('is_active', true);

                            if ($globalCompanyId && $globalCompanyId !== 'all') {
                                $query->where('company_id', $globalCompanyId);
                            }

                            return $query->orderBy('code')->limit(50)->get()->mapWithKeys(fn ($account) => [
                                $account->id => "{$account->code} - {$account->name}",
                            ]);
                        })
                        ->getOptionLabelUsing(function ($value) {
                            $account = \App\Models\Account::find($value);
                            return $account ? "{$account->code} - {$account->name}" : $value;
                        }),
                    Textarea::make("description")
                        ->label(__("Description"))
                        ->rows(1)
                        ->maxLength(65535)
                        ->dehydrated(true),
                    ...RoundedIntegerMoneyInput::schema(
                        name: 'amount',
                        label: __('Total'),
                        required: true,
                        scale: 0,
                        defaultDecimal: '0',
                        afterUpdated: function ($decimal, callable $set, callable $get) {
                            $items = $get('../../items') ?? [];
                            $grandTotal = 0;
                            foreach ($items as $item) {
                                $itemTotal = NumberInput::parseToFloat($item['amount'] ?? 0);
                                $grandTotal += $itemTotal;
                            }
                            $set('../../total', $grandTotal);
                        },
                    ),
                ])
                ->reorderable()
                ->cloneable()
                ->collapsible()
                ->compact()
                ->columnSpan("full"),

            Section::make()
                ->schema([
                    Placeholder::make("empty_col_1")
                        ->hiddenLabel()
                        ->columnSpan(1),
                    Placeholder::make("total_disbursement_display")
                        ->label(__("Total Disbursement"))
                        ->inlineLabel()
                        ->live()
                        ->content(function ($get) {
                            $total = $get("total") ?? 0;
                            if (is_string($total)) {
                                $total = str_replace(['.', ','], ['', '.'], $total);
                            }
                            $total = is_numeric($total) ? (float) $total : 0;
                            return 'Rp. ' . number_format($total, 0, ',', '.');
                        })
                        ->extraAttributes([
                            "class" => "font-semibold text-lg py-2 px-3 bg-gray-50 rounded-md border border-gray-200",
                            "style" => "text-align:right",
                        ])
                        ->columnSpan(2),
                    NumberInput::make("total")
                        ->hidden()
                        ->dehydrated(true)
                        ->reactive()
                        ->default(0)
                        ->afterStateHydrated(function (callable $set, callable $get) {
                            $items = $get('items') ?? [];
                            $total = 0;
                            foreach ($items as $item) {
                                $itemTotal = static::parseNumber($item['amount'] ?? $item['total'] ?? 0);
                                $total += $itemTotal;
                            }
                            if ($total > 0) {
                                $set('total', $total);
                            }
                        })
                        ->formatStateUsing(function ($state, callable $get) {
                            $items = $get('items') ?? [];
                            $total = 0;
                            foreach ($items as $item) {
                                $itemTotal = static::parseNumber($item['amount'] ?? $item['total'] ?? 0);
                                $total += $itemTotal;
                            }
                            return $total > 0 ? $total : ($state ?? 0);
                        })
                        ->columnSpan(2),
                    Placeholder::make("empty_col_2")
                        ->hiddenLabel()
                        ->columnSpan(1),
                    Toggle::make("is_posted")
                        ->label(__("Posted"))
                        ->helperText(__("Mark this entry as posted to the general ledger"))
                        ->default(false)
                        ->dehydrated(true)
                        ->afterStateHydrated(function (callable $set, $state, $record) {
                            if ($record) {
                                $isPosted = $record->status === 'posted';
                                $set('is_posted', $isPosted);
                            }
                        })
                        ->columnSpan(2),
                ])
                ->columns(2)
                ->columnSpanFull(),
        ]);
    }
}
