<?php

namespace App\Models;

use App\Traits\HasAutoGeneratedCode;
use App\Traits\HasDependencyValidation;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class BankAccount extends Model
{
    use HasFactory, SoftDeletes, HasAutoGeneratedCode, HasDependencyValidation;

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            if (Auth::check() && !$model->created_by_user_id) {
                $model->created_by_user_id = Auth::id();
            }

            // Set company_id from global selector if not explicitly set
            if (!$model->company_id) {
                $selectedCompanyId = session('selected_company_id');
                if ($selectedCompanyId) {
                    $model->company_id = $selectedCompanyId;
                }
            }
        });
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'account_number',
        'account_name',
        'account_type',
        'balance',
        'is_active',
        'bank_id',
        'company_id',
        'created_by_user_id',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'id' => 'integer',
            'balance' => 'decimal:2',
            'is_active' => 'boolean',
            'bank_id' => 'integer',
            'company_id' => 'integer',
            'created_by_user_id' => 'integer',
        ];
    }

    protected function getDocumentType(): string
    {
        return 'bank_account';
    }

    protected function getCodeFieldName(): string
    {
        return 'account_number';
    }

    public function bank(): BelongsTo
    {
        return $this->belongsTo(Bank::class);
    }

    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    public function createdByUser(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function getDependencyChecks(): array
    {
        return [
            ['table' => 'receivable_payments', 'foreignKey' => 'bank_account_id', 'label' => 'receivable payments'],
            ['table' => 'payable_payments', 'foreignKey' => 'bank_account_id', 'label' => 'payable payments'],
        ];
    }
}
