<?php

namespace App\Models;

use App\Traits\HasAutoGeneratedCode;
use App\Traits\HasDependencyValidation;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Contact extends Model
{
    use HasFactory, SoftDeletes, HasAutoGeneratedCode, HasDependencyValidation;

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($contact) {
            if (Auth::check() && !$contact->created_by_user_id) {
                $contact->created_by_user_id = Auth::id();
            }

            // Set company_id from global selector if not explicitly set
            if (!$contact->company_id) {
                $selectedCompanyId = session('selected_company_id');
                if ($selectedCompanyId) {
                    $contact->company_id = $selectedCompanyId;
                }
            }
        });
    }

    protected function getDocumentType(): string
    {
        if ($this->is_supplier) {
            return 'supplier';
        }
        if ($this->is_customer) {
            return 'customer';
        }
        return 'contact';
    }

    protected function getCodeFieldName(): string
    {
        return 'contact_code';
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'phone',
        'tax',
        'is_pkp',
        'contact_code',
        'contact_person',
        'is_customer',
        'is_supplier',
        'is_employee',
        'is_sales',
        'credit_limit',
        'is_active',
        'billing_address_line_1',
        'billing_address_line_2',
        'billing_city',
        'billing_state',
        'billing_postal_code',
        'billing_country',
        'delivery_address_line_1',
        'delivery_address_line_2',
        'delivery_city',
        'delivery_state',
        'delivery_postal_code',
        'delivery_country',
        'supporting_document',
        'payment_term_id',
        'company_id',
        'created_by_user_id',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'id' => 'integer',
            'is_customer' => 'boolean',
            'is_supplier' => 'boolean',
            'is_employee' => 'boolean',
            'is_sales' => 'boolean',
            'is_pkp' => 'boolean',
            'credit_limit' => 'decimal:2',
            'is_active' => 'boolean',
            'payment_term_id' => 'integer',
            'company_id' => 'integer',
            'created_by_user_id' => 'integer',
        ];
    }

    public function paymentTerm(): BelongsTo
    {
        return $this->belongsTo(PaymentTerm::class);
    }

    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    public function createdByUser(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function getDependencyChecks(): array
    {
        return [
            ['table' => 'sales_orders', 'foreignKey' => 'customer_id', 'label' => 'sales orders'],
            ['table' => 'purchase_orders', 'foreignKey' => 'supplier_id', 'label' => 'purchase orders'],
            ['table' => 'delivery_documents', 'foreignKey' => 'customer_id', 'label' => 'delivery documents'],
            ['table' => 'goods_receipts', 'foreignKey' => 'supplier_id', 'label' => 'goods receipts'],
            ['table' => 'sales_invoices', 'foreignKey' => 'customer_id', 'label' => 'sales invoices'],
            ['table' => 'purchase_invoices', 'foreignKey' => 'supplier_id', 'label' => 'purchase invoices'],
            ['table' => 'sales_returns', 'foreignKey' => 'customer_id', 'label' => 'sales returns'],
            ['table' => 'purchase_returns', 'foreignKey' => 'supplier_id', 'label' => 'purchase returns'],
            ['table' => 'receivable_payments', 'foreignKey' => 'customer_id', 'label' => 'receivable payments'],
            ['table' => 'payable_payments', 'foreignKey' => 'supplier_id', 'label' => 'payable payments'],
            ['table' => 'projects', 'foreignKey' => 'contact_id', 'label' => 'projects'],
        ];
    }
}
