<?php

namespace App\Models;

use App\Traits\HasAutoGeneratedCode;
use App\Traits\HasDependencyValidation;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class DeferredRevenue extends Model
{
    use HasFactory, SoftDeletes, HasAutoGeneratedCode, HasDependencyValidation;

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            if (Auth::check() && !$model->created_by_user_id) {
                $model->created_by_user_id = Auth::id();
            }

            if (!$model->company_id) {
                $selectedCompanyId = session('selected_company_id');
                if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                    $model->company_id = $selectedCompanyId;
                }
            }
        });
    }

    protected function getDocumentType(): string
    {
        return 'deferred_revenue';
    }

    protected function getCodeFieldName(): string
    {
        return 'contract_number';
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'contract_number',
        'date',
        'description',
        'customer_name',
        'total_amount',
        'total_periods',
        'recognition_method',
        'period_start',
        'period_end',
        'recognized_amount',
        'remaining_amount',
        'status',
        'customer_id',
        'sales_invoice_id',
        'deferred_revenue_account_id',
        'revenue_account_id',
        'company_id',
        'created_by_user_id',
        'updated_by_user_id',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'id' => 'integer',
            'date' => 'date',
            'period_start' => 'date',
            'period_end' => 'date',
            'total_amount' => 'decimal:2',
            'recognized_amount' => 'decimal:2',
            'remaining_amount' => 'decimal:2',
            'customer_id' => 'integer',
            'sales_invoice_id' => 'integer',
            'deferred_revenue_account_id' => 'integer',
            'revenue_account_id' => 'integer',
            'company_id' => 'integer',
            'created_by_user_id' => 'integer',
            'updated_by_user_id' => 'integer',
        ];
    }

    public function customer(): BelongsTo
    {
        return $this->belongsTo(Contact::class, 'customer_id');
    }

    public function salesInvoice(): BelongsTo
    {
        return $this->belongsTo(SalesInvoice::class);
    }

    public function deferredRevenueAccount(): BelongsTo
    {
        return $this->belongsTo(Account::class, 'deferred_revenue_account_id');
    }

    public function revenueAccount(): BelongsTo
    {
        return $this->belongsTo(Account::class, 'revenue_account_id');
    }

    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    public function createdByUser(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by_user_id');
    }

    public function updatedByUser(): BelongsTo
    {
        return $this->belongsTo(User::class, 'updated_by_user_id');
    }

    public function schedules(): HasMany
    {
        return $this->hasMany(DeferredRevenueSchedule::class)->orderBy('period_number');
    }

    public function journalEntries(): HasMany
    {
        return $this->hasMany(JournalEntry::class, 'reference_id')
            ->where('reference_type', self::class);
    }

    /**
     * Refresh the recognized/remaining totals from schedule lines.
     */
    public function refreshTotals(): void
    {
        $this->recognized_amount = $this->schedules()
            ->where('status', 'recognized')
            ->sum('recognized_amount');

        $this->remaining_amount = $this->total_amount - $this->recognized_amount;

        if ($this->remaining_amount <= 0) {
            $this->status = 'completed';
        } elseif ($this->recognized_amount > 0) {
            $this->status = 'active';
        }

        $this->saveQuietly();
    }

    public function getDependencyChecks(): array
    {
        return [
            ['table' => 'deferred_revenue_schedules', 'foreignKey' => 'deferred_revenue_id', 'label' => 'amortization schedules'],
        ];
    }
}
