<?php

namespace App\Models;

use App\Traits\EnforcesOpenPeriod;
use App\Traits\HasAutoGeneratedCode;
use App\Traits\Journalable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class DeliveryDocument extends Model
{
    use HasFactory, SoftDeletes, HasAutoGeneratedCode, Journalable, EnforcesOpenPeriod;

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            if (Auth::check() && !$model->created_by_user_id) {
                $model->created_by_user_id = Auth::id();
            }

            // Set company_id from global selector if not explicitly set
            if (!$model->company_id) {
                $selectedCompanyId = session('selected_company_id');
                if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                    $model->company_id = $selectedCompanyId;
                }
            }
        });

        static::updating(function (self $model) {
            if (!$model->getOriginal('is_locked')) {
                return;
            }

            $model->customer_id = $model->getOriginal('customer_id');
            $model->sales_order_id = $model->getOriginal('sales_order_id');
            $model->company_id = $model->getOriginal('company_id');
            $model->job_id = $model->getOriginal('job_id');
            $model->is_locked = true;
        });

        static::saved(function (self $model) {
            if ($model->is_locked && $model->sales_order_id) {
                $model->salesOrder?->refreshDeliveryTracking();
            }
        });

        static::deleted(function (self $model) {
            if ($model->is_locked && $model->sales_order_id) {
                $model->salesOrder?->refreshDeliveryTracking();
            }
        });

        static::deleting(function (self $model) {
            $hasLockedReturns = $model->salesReturns()->where('is_locked', true)->exists();
            if ($hasLockedReturns) {
                \Filament\Notifications\Notification::make()
                    ->danger()
                    ->title('Cannot delete')
                    ->body('This delivery has locked returns.')
                    ->send();
                return false;
            }
        });

        static::restored(function (self $model) {
            if ($model->is_locked && $model->sales_order_id) {
                $model->salesOrder?->refreshDeliveryTracking();
            }
        });
    }

    /**
     * Get the document type for code generation
     *
     * @return string
     */
    protected function getDocumentType(): string
    {
        return 'delivery_document';
    }

    /**
     * Get code field name
     *
     * @return string
     */
    protected function getCodeFieldName(): string
    {
        return 'delivery_number';
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'delivery_number',
        'date',
        'is_closed',
        'reference_no',
        'description',
        'delivery_status',
        'status',
        'tracking_number',
        'bast_document',
        'tpb_document',
        'dispatch_time',
        'completion_time',
        'customer_id',
        'sales_order_id',
        'is_locked',
        'return_meta',
        'job_id',
        'expedition_id',
        'company_id',
        'created_by_user_id',
        'updated_by_user_id',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'id' => 'integer',
            'date' => 'date',
            'is_closed' => 'boolean',
            'dispatch_time' => 'timestamp',
            'completion_time' => 'timestamp',
            'customer_id' => 'integer',
            'sales_order_id' => 'integer',
            'is_locked' => 'boolean',
            'return_meta' => 'array',
            'job_id' => 'integer',
            'expedition_id' => 'integer',
            'company_id' => 'integer',
            'created_by_user_id' => 'integer',
            'updated_by_user_id' => 'integer',
            'status' => 'string',
        ];
    }

    public function computeReturnMeta(): array
    {
        $items = $this->items()->get(['quantity', 'returned_quantity']);
        $totalQty = (float) $items->sum('quantity');
        $returnedQty = (float) $items->sum('returned_quantity');
        $remainingQty = max(0.0, $totalQty - $returnedQty);

        return [
            'total' => round($totalQty, 2),
            'returned' => round($returnedQty, 2),
            'remaining' => round($remainingQty, 2),
        ];
    }

    public function refreshReturnTracking(): void
    {
        $returnQuantities = DB::table('sales_returns')
            ->join('sales_return_items', 'sales_return_items.sales_return_id', '=', 'sales_returns.id')
            ->whereNull('sales_returns.deleted_at')
            ->whereNull('sales_return_items.deleted_at')
            ->where('sales_returns.is_locked', true)
            ->where('sales_returns.delivery_document_id', $this->id)
            ->whereNotNull('sales_return_items.delivery_document_item_id')
            ->groupBy('sales_return_items.delivery_document_item_id')
            ->select([
                'sales_return_items.delivery_document_item_id',
                DB::raw('COALESCE(SUM(sales_return_items.quantity), 0) as returned_quantity'),
            ])
            ->pluck('returned_quantity', 'delivery_document_item_id');

        $items = $this->items()->get(['id', 'quantity', 'returned_quantity']);

        foreach ($items as $item) {
            $returned = (float) ($returnQuantities[$item->id] ?? 0);
            $item->returned_quantity = round($returned, 2);
            $item->saveQuietly();
        }

        $this->return_meta = $this->computeReturnMeta();
        $this->saveQuietly();
    }

    public function customer(): BelongsTo
    {
        return $this->belongsTo(Contact::class);
    }

    public function salesOrder(): BelongsTo
    {
        return $this->belongsTo(SalesOrder::class);
    }

    public function job(): BelongsTo
    {
        return $this->belongsTo(Project::class);
    }

    public function expedition(): BelongsTo
    {
        return $this->belongsTo(Expedition::class);
    }

    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    public function createdByUser(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function updatedByUser(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function items(): HasMany
    {
        return $this->hasMany(DeliveryDocumentItem::class);
    }

    public function salesReturns(): HasMany
    {
        return $this->hasMany(SalesReturn::class);
    }

    public function journalEntries()
    {
        return $this->hasMany(\App\Models\JournalEntry::class, 'reference_id')
            ->where('reference_type', DeliveryDocument::class);
    }

    public function journalEntry(): \Illuminate\Database\Eloquent\Relations\HasOne
    {
        return $this->hasOne(\App\Models\JournalEntry::class, 'reference_id')
            ->where('reference_type', self::class);
    }
}
