<?php

namespace App\Models;

use App\Traits\HasAutoGeneratedCode;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class FixedAsset extends Model
{
    use HasFactory, SoftDeletes, HasAutoGeneratedCode;

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            if (Auth::check() && !$model->created_by_user_id) {
                $model->created_by_user_id = Auth::id();
            }
            
            // Set company_id from global selector if not explicitly set
            if (!$model->company_id) {
                $selectedCompanyId = session('selected_company_id');
                if ($selectedCompanyId) {
                    $model->company_id = $selectedCompanyId;
                }
            }
        });
    }

    protected function getDocumentType(): string
    {
        return 'fixed_asset';
    }

    protected function getCodeFieldName(): string
    {
        return 'code';
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'code',
        'acquisition_date',
        'description',
        'acquisition_value',
        'book_value',
        'is_active',
        'category_id',
        'company_id',
        'created_by_user_id',
        'location',
        'depreciation_method',
        'useful_life',
        'monthly_depreciation',
        'accumulated_depreciation',
        'department_id',
        'transaction_in_id',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'id' => 'integer',
            'acquisition_date' => 'date',
            'acquisition_value' => 'decimal:2',
            'monthly_depreciation' => 'decimal:2',
            'accumulated_depreciation' => 'decimal:2',
            'book_value' => 'decimal:2',
            'is_active' => 'boolean',
            'category_id' => 'integer',
            'department_id' => 'integer',
            'transaction_in_id' => 'integer',
            'company_id' => 'integer',
            'created_by_user_id' => 'integer',
        ];
    }

    public function category(): BelongsTo
    {
        return $this->belongsTo(FixedAssetCategory::class);
    }

    public function department(): BelongsTo
    {
        return $this->belongsTo(Department::class);
    }

    public function transactionIn(): BelongsTo
    {
        return $this->belongsTo(JournalEntry::class);
    }

    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    public function createdByUser(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function transactions(): HasMany
    {
        return $this->hasMany(FixedAssetTransaction::class);
    }
}
