<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use App\Traits\HasAutoGeneratedCode;
use App\Traits\Journalable;

class GoodsReceipt extends Model
{
    use HasFactory, SoftDeletes, HasAutoGeneratedCode, Journalable;

    protected function getDocumentType(): string
    {
        return 'goods_receipt';
    }

    protected function getCodeFieldName(): string
    {
        return 'receipt_number';
    }

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            if (Auth::check() && !$model->created_by_user_id) {
                $model->created_by_user_id = Auth::id();
            }
            
            // Set company_id from global selector if not explicitly set
            if (!$model->company_id) {
                $selectedCompanyId = session('selected_company_id');
                if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                    $model->company_id = $selectedCompanyId;
                }
            }
        });

        static::updating(function (self $model) {
            if (!$model->getOriginal('is_locked')) {
                return;
            }

            $model->supplier_id = $model->getOriginal('supplier_id');
            $model->purchase_order_id = $model->getOriginal('purchase_order_id');
            $model->company_id = $model->getOriginal('company_id');
            $model->job_id = $model->getOriginal('job_id');
            $model->is_locked = true;
        });

        static::saved(function (self $model) {
            if ($model->is_locked && $model->purchase_order_id) {
                $model->purchaseOrder?->refreshReceiptTracking();
            }
        });

        static::deleted(function (self $model) {
            if ($model->is_locked && $model->purchase_order_id) {
                $model->purchaseOrder?->refreshReceiptTracking();
            }
        });

        static::deleting(function (self $model) {
            $hasLockedReturns = $model->purchaseReturns()->where('is_locked', true)->exists();
            if ($hasLockedReturns) {
                \Filament\Notifications\Notification::make()
                    ->danger()
                    ->title('Tidak dapat menghapus')
                    ->body('Penerimaan memiliki retur yang terkunci.')
                    ->send();
                return false;
            }
        });

        static::restored(function (self $model) {
            if ($model->is_locked && $model->purchase_order_id) {
                $model->purchaseOrder?->refreshReceiptTracking();
            }
        });
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'receipt_number',
        'date',
        'is_closed',
        'is_locked',
        'return_meta',
        'reference_no',
        'description',
        'status',
        'supplier_id',
        'purchase_order_id',
        'job_id',
        'company_id',
        'created_by_user_id',
        'updated_by_user_id',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'id' => 'integer',
            'date' => 'date',
            'is_closed' => 'boolean',
            'is_locked' => 'boolean',
            'return_meta' => 'array',
            'supplier_id' => 'integer',
            'purchase_order_id' => 'integer',
            'job_id' => 'integer',
            'company_id' => 'integer',
            'created_by_user_id' => 'integer',
            'updated_by_user_id' => 'integer',
            'status' => 'string',
        ];
    }

    public function computeReturnMeta(): array
    {
        $items = $this->items()->get(['quantity', 'returned_quantity']);
        $totalQty = (float) $items->sum('quantity');
        $returnedQty = (float) $items->sum('returned_quantity');
        $remainingQty = max(0.0, $totalQty - $returnedQty);

        return [
            'total' => round($totalQty, 2),
            'returned' => round($returnedQty, 2),
            'remaining' => round($remainingQty, 2),
        ];
    }

    public function refreshReturnTracking(): void
    {
        $returnQuantities = DB::table('purchase_returns')
            ->join('purchase_return_items', 'purchase_return_items.purchase_return_id', '=', 'purchase_returns.id')
            ->whereNull('purchase_returns.deleted_at')
            ->whereNull('purchase_return_items.deleted_at')
            ->where('purchase_returns.is_locked', true)
            ->where('purchase_returns.goods_receipt_id', $this->id)
            ->whereNotNull('purchase_return_items.goods_receipt_item_id')
            ->groupBy('purchase_return_items.goods_receipt_item_id')
            ->select([
                'purchase_return_items.goods_receipt_item_id',
                DB::raw('COALESCE(SUM(purchase_return_items.quantity), 0) as returned_quantity'),
            ])
            ->pluck('returned_quantity', 'goods_receipt_item_id');

        $items = $this->items()->get(['id', 'quantity', 'returned_quantity']);

        foreach ($items as $item) {
            $returned = (float) ($returnQuantities[$item->id] ?? 0);
            $item->returned_quantity = round($returned, 2);
            $item->saveQuietly();
        }

        $this->return_meta = $this->computeReturnMeta();
        $this->saveQuietly();
    }

    public function supplier(): BelongsTo
    {
        return $this->belongsTo(Contact::class);
    }

    public function purchaseOrder(): BelongsTo
    {
        return $this->belongsTo(PurchaseOrder::class);
    }

    public function job(): BelongsTo
    {
        return $this->belongsTo(Project::class);
    }

    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    public function createdByUser(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function updatedByUser(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function items(): HasMany
    {
        return $this->hasMany(GoodsReceiptItem::class);
    }

    public function purchaseReturns(): HasMany
    {
        return $this->hasMany(PurchaseReturn::class);
    }

    public function journalEntries()
    {
        return $this->hasMany(\App\Models\JournalEntry::class, 'reference_id')
            ->where('reference_type', GoodsReceipt::class);
    }
}
