<?php

namespace App\Models;

use App\Traits\HasAutoGeneratedCode;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Product extends Model
{
    use HasFactory, SoftDeletes, HasAutoGeneratedCode;

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            if (Auth::check() && !$model->created_by_user_id) {
                $model->created_by_user_id = Auth::id();
            }
            
            // Set company_id from global selector if not explicitly set
            if (!$model->company_id) {
                $selectedCompanyId = session('selected_company_id');
                if ($selectedCompanyId) {
                    $model->company_id = $selectedCompanyId;
                }
            }

            if (!$model->unit_id) {
                $unit = Unit::whereRaw('LOWER(code) = ?', ['pcs'])
                    ->orWhereRaw('LOWER(name) = ?', ['pcs'])
                    ->first();
                if (!$unit) {
                    $unit = Unit::orderBy('id')->first();
                }
                if ($unit) {
                    $model->unit_id = $unit->id;
                }
            }

            if (!$model->product_group_id) {
                $query = ProductGroup::query();
                if ($model->company_id) {
                    $query->where('company_id', $model->company_id);
                } else {
                    $selectedCompanyId = session('selected_company_id');
                    if ($selectedCompanyId) {
                        $query->where('company_id', $selectedCompanyId);
                    }
                }
                $pg = $query->orderBy('id')->first();
                if (!$pg) {
                    $pg = ProductGroup::orderBy('id')->first();
                }
                if ($pg) {
                    $model->product_group_id = $pg->id;
                }
            }
        });
    }

    protected function getDocumentType(): string
    {
        return 'product';
    }

    protected function getCodeFieldName(): string
    {
        return 'code';
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'code',
        'description',
        'cost_price',
        'selling_price',
        'reorder_level',
        'max_stock',
        'weight',
        'product_type',
        'is_active',
        'image',
        'unit_id',
        'product_group_id',
        'company_id',
        'created_by_user_id',
        'supplier_id',
        'min_order_qty',
        'tax_id',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'id' => 'integer',
            'cost_price' => 'decimal:2',
            'selling_price' => 'decimal:2',
            'reorder_level' => 'decimal:2',
            'max_stock' => 'decimal:2',
            'weight' => 'decimal:3',
            'min_order_qty' => 'decimal:2',
            'is_active' => 'boolean',
            'unit_id' => 'integer',
            'product_group_id' => 'integer',
            'company_id' => 'integer',
            'created_by_user_id' => 'integer',
            'supplier_id' => 'integer',
            'tax_id' => 'integer',
        ];
    }

    public function unit(): BelongsTo
    {
        return $this->belongsTo(Unit::class);
    }

    public function productGroup(): BelongsTo
    {
        return $this->belongsTo(ProductGroup::class);
    }

    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    public function createdByUser(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function supplier(): BelongsTo
    {
        return $this->belongsTo(Contact::class);
    }

    public function tax(): BelongsTo
    {
        return $this->belongsTo(Tax::class);
    }
}
