<?php

namespace App\Models;

use App\Traits\HasAutoGeneratedCode;
use App\Traits\HasDependencyValidation;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

class Project extends Model
{
    use HasFactory, SoftDeletes, HasAutoGeneratedCode, HasDependencyValidation;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'job_number',
        'status',
        'customer_po_number',
        'title',
        'description',
        'total_value',
        'total_invoiced',
        'total_paid',
        'total_delivered',
        'customer_id',
        'company_id',
        'created_by_user_id',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'id' => 'integer',
            'total_value' => 'decimal:2',
            'total_invoiced' => 'decimal:2',
            'total_paid' => 'decimal:2',
            'total_delivered' => 'decimal:2',
            'customer_id' => 'integer',
            'company_id' => 'integer',
            'created_by_user_id' => 'integer',
        ];
    }

    protected function getDocumentType(): string
    {
        return 'project';
    }

    protected function getCodeFieldName(): string
    {
        return 'job_number';
    }

    /**
     * For projects, always auto-generate the job number during creation
     */
    protected static function bootHasAutoGeneratedCode(): void
    {
        static::creating(function ($model) {
            if (method_exists($model, 'generateAndSaveCode') &&
                $model->getCodeFieldName() &&
                $model->isAutoGenerateEnabled()) {
                $field = $model->getCodeFieldName();
                $model->{$field} = $model->generateAndSaveCode();
            }
        });
    }

    public function customer(): BelongsTo
    {
        return $this->belongsTo(Contact::class);
    }

    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    public function createdByUser(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function getDependencyChecks(): array
    {
        return [
            ['table' => 'delivery_documents', 'foreignKey' => 'project_id', 'label' => 'delivery documents'],
            ['table' => 'sales_invoices', 'foreignKey' => 'job_id', 'label' => 'sales invoices'],
            ['table' => 'purchase_invoices', 'foreignKey' => 'job_id', 'label' => 'purchase invoices'],
            ['table' => 'goods_receipts', 'foreignKey' => 'project_id', 'label' => 'goods receipts'],
            ['table' => 'sales_returns', 'foreignKey' => 'project_id', 'label' => 'sales returns'],
            ['table' => 'purchase_returns', 'foreignKey' => 'project_id', 'label' => 'purchase returns'],
            ['table' => 'receivable_payments', 'foreignKey' => 'project_id', 'label' => 'receivable payments'],
            ['table' => 'payable_payments', 'foreignKey' => 'project_id', 'label' => 'payable payments'],
        ];
    }
}
