<?php

namespace App\Models;

use App\Traits\HasAutoGeneratedCode;
use App\Traits\Journalable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class PurchaseReturn extends Model
{
    use HasFactory, SoftDeletes, HasAutoGeneratedCode, Journalable;

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            if (Auth::check() && !$model->created_by_user_id) {
                $model->created_by_user_id = Auth::id();
            }

            if (Auth::check() && !$model->updated_by_user_id) {
                $model->updated_by_user_id = Auth::id();
            }
            
            // Set company_id from global selector if not explicitly set
            if (!$model->company_id) {
                $selectedCompanyId = session('selected_company_id');
                if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                    $model->company_id = $selectedCompanyId;
                }
            }

            // Set default status if not explicitly set
            if (!$model->status) {
                $model->status = 'requested';
            }
        });

        static::updating(function (self $model) {
            if (!$model->getOriginal('is_locked')) {
                return;
            }

            $model->supplier_id = $model->getOriginal('supplier_id');
            $model->goods_receipt_id = $model->getOriginal('goods_receipt_id');
            $model->company_id = $model->getOriginal('company_id');
            $model->job_id = $model->getOriginal('job_id');
            $model->is_locked = true;
        });

        static::saved(function (self $model) {
            if ($model->is_locked && $model->goods_receipt_id) {
                $model->goodsReceipt?->refreshReturnTracking();
            }
        });

        static::deleted(function (self $model) {
            if ($model->is_locked && $model->goods_receipt_id) {
                $model->goodsReceipt?->refreshReturnTracking();
            }
        });

        static::restored(function (self $model) {
            if ($model->is_locked && $model->goods_receipt_id) {
                $model->goodsReceipt?->refreshReturnTracking();
            }
        });
    }

    protected function getDocumentType(): string
    {
        return 'purchase_return';
    }

    protected function getCodeFieldName(): string
    {
        return 'return_number';
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'date',
        'reference_no',
        'return_number',
        'description',
        'status',
        'is_locked',
        'supplier_id',
        'purchase_invoice_id',
        'goods_receipt_id',
        'job_id',
        'company_id',
        'created_by_user_id',
        'updated_by_user_id',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'id' => 'integer',
            'date' => 'date',
            'is_locked' => 'boolean',
            'supplier_id' => 'integer',
            'purchase_invoice_id' => 'integer',
            'goods_receipt_id' => 'integer',
            'job_id' => 'integer',
            'company_id' => 'integer',
            'created_by_user_id' => 'integer',
            'updated_by_user_id' => 'integer',
            'status' => 'string',
        ];
    }

    public function supplier(): BelongsTo
    {
        return $this->belongsTo(Contact::class);
    }

    public function purchaseInvoice(): BelongsTo
    {
        return $this->belongsTo(PurchaseInvoice::class);
    }

    public function goodsReceipt(): BelongsTo
    {
        return $this->belongsTo(GoodsReceipt::class);
    }

    public function job(): BelongsTo
    {
        return $this->belongsTo(Project::class);
    }

    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    public function createdByUser(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function updatedByUser(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function items(): HasMany
    {
        return $this->hasMany(PurchaseReturnItem::class);
    }


    public function journalEntries()
    {
        return $this->hasMany(\App\Models\JournalEntry::class, 'reference_id')
            ->where('reference_type', PurchaseReturn::class);
    }
}
