<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

use App\Traits\HasAutoGeneratedCode;

class ReceivablePayment extends Model
{
    use HasFactory, SoftDeletes, HasAutoGeneratedCode;

    protected function getDocumentType(): string
    {
        return 'receivable_payment';
    }

    protected function getCodeFieldName(): string
    {
        return 'payment_number';
    }

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            if (Auth::check() && !$model->created_by_user_id) {
                $model->created_by_user_id = Auth::id();
            }

            if (!$model->company_id) {
                $selectedCompanyId = session('selected_company_id');
                if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                    $model->company_id = $selectedCompanyId;
                }
            }
        });

        static::updating(function ($model) {
            if (Auth::check() && !$model->isDirty('updated_by_user_id')) {
                $model->updated_by_user_id = Auth::id();
            }
        });

        static::deleting(function ($model) {
            $model->items()->get()->each(function ($item) {
                $invoice = \App\Models\SalesInvoice::find($item->sales_invoice_id);
                if ($invoice) {
                    $newPaidAmount = max(0, (float) $invoice->paid_amount - (float) $item->set_payment);
                    $newOutstandingAmount = (float) $invoice->total_amount - $newPaidAmount;

                    $invoice->paid_amount = $newPaidAmount;
                    $invoice->outstanding_amount = max(0, $newOutstandingAmount);
                    $invoice->is_paid = $newOutstandingAmount <= 0;

                    if ($invoice->is_paid) {
                        $invoice->status = 'paid';
                    } elseif ($newPaidAmount > 0) {
                        $invoice->status = 'partially_paid';
                    } else {
                        $invoice->status = 'sent';
                    }

                    $invoice->save();

                    try {
                        $service = app(\App\Services\ReceivablePayableService::class);
                        $service->updateOutstandingJournalEntryForSalesInvoice($invoice);
                    } catch (\Exception $e) {
                        \Log::error('Error updating outstanding journal entry for SalesInvoice on payment deletion: ' . $e->getMessage());
                    }
                }
                $item->delete();
            });

            $journalEntry = \App\Models\JournalEntry::where('reference_type', self::class)
                ->where('reference_id', $model->id)
                ->first();

            if ($journalEntry) {
                $journalEntry->items()->delete();
                $journalEntry->delete();
            }
        });
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'payment_number',
        'payment_date',
        'reference_no',
        'description',
        'transaction_notes',
        'total_payment',
        'payment_method',
        'status',
        'customer_id',
        'bank_account_id',
        'job_id',
        'company_id',
        'created_by_user_id',
        'updated_by_user_id',
        'other_costs',
        'other_costs_account_id',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'id' => 'integer',
            'payment_date' => 'date',
            'total_payment' => 'decimal:2',
            'other_costs' => 'decimal:2',
            'other_costs_account_id' => 'integer',
            'customer_id' => 'integer',
            'bank_account_id' => 'integer',
            'job_id' => 'integer',
            'company_id' => 'integer',
            'created_by_user_id' => 'integer',
            'updated_by_user_id' => 'integer',
        ];
    }

    public function otherCostsAccount(): BelongsTo
    {
        return $this->belongsTo(Account::class, 'other_costs_account_id');
    }

    public function customer(): BelongsTo
    {
        return $this->belongsTo(Contact::class);
    }

    public function bankAccount(): BelongsTo
    {
        return $this->belongsTo(BankAccount::class);
    }

    public function account(): BelongsTo
    {
        return $this->belongsTo(Account::class, 'bank_account_id');
    }

    public function job(): BelongsTo
    {
        return $this->belongsTo(Project::class);
    }

    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    public function createdByUser(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function updatedByUser(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function items(): HasMany
    {
        return $this->hasMany(ReceivablePaymentItem::class);
    }

    public function journalEntry(): \Illuminate\Database\Eloquent\Relations\MorphOne
    {
        return $this->morphOne(JournalEntry::class, 'reference');
    }
}
