<?php

namespace App\Models;

use App\Traits\HasAutoGeneratedCode;
use App\Traits\HasDependencyValidation;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class SalaryComponent extends Model
{
    use HasFactory, SoftDeletes, HasAutoGeneratedCode, HasDependencyValidation;

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            if (Auth::check() && !$model->created_by_user_id) {
                $model->created_by_user_id = Auth::id();
            }

            if (!$model->company_id) {
                $selectedCompanyId = session('selected_company_id');
                if ($selectedCompanyId) {
                    $model->company_id = $selectedCompanyId;
                }
            }
        });
    }

    protected function getDocumentType(): string
    {
        return 'salary_component';
    }

    protected function getCodeFieldName(): string
    {
        return 'code';
    }

    protected $fillable = [
        'code',
        'name',
        'type',
        'is_fixed',
        'is_taxable',
        'is_bpjs_base',
        'account_id',
        'is_active',
        'company_id',
        'created_by_user_id',
    ];

    protected function casts(): array
    {
        return [
            'is_fixed' => 'boolean',
            'is_taxable' => 'boolean',
            'is_bpjs_base' => 'boolean',
            'is_active' => 'boolean',
            'account_id' => 'integer',
            'company_id' => 'integer',
            'created_by_user_id' => 'integer',
        ];
    }

    public function employeeComponents(): HasMany
    {
        return $this->hasMany(EmployeeSalaryComponent::class);
    }

    public function payslipItems(): HasMany
    {
        return $this->hasMany(PayslipItem::class);
    }

    public function account(): BelongsTo
    {
        return $this->belongsTo(Account::class);
    }

    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    public function createdByUser(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by_user_id');
    }

    public function getDependencyChecks(): array
    {
        return [
            ['relation' => 'employeeComponents', 'label' => 'employee salary components'],
            ['relation' => 'payslipItems', 'label' => 'payslip items'],
        ];
    }
}
