<?php

namespace App\Models;

use App\Traits\HasAutoGeneratedCode;
use App\Traits\Journalable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class SalesOrder extends Model
{
    use HasFactory, SoftDeletes, HasAutoGeneratedCode, Journalable;

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            if (Auth::check() && !$model->created_by_user_id) {
                $model->created_by_user_id = Auth::id();
            }

            // Set company_id from global selector if not explicitly set
            if (!$model->company_id) {
                $selectedCompanyId = session('selected_company_id');
                if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                    $model->company_id = $selectedCompanyId;
                }
            }
        });

        static::deleting(function ($model) {
            $hasLockedDeliveries = $model->deliveryDocuments()->where('is_locked', true)->exists();
            $hasLockedInvoices = DB::table('sales_invoices')
                ->where('sales_order_id', $model->id)
                ->where('is_locked', true)
                ->whereNull('deleted_at')
                ->exists();
            
            if ($hasLockedDeliveries || $hasLockedInvoices) {
                \Filament\Notifications\Notification::make()
                    ->danger()
                    ->title('Tidak dapat menghapus')
                    ->body('Pesanan memiliki dokumen pengiriman atau invoice yang terkunci.')
                    ->send();
                return false;
            }
        });
    }

    protected function getDocumentType(): string
    {
        return 'sales_order';
    }

    protected function getCodeFieldName(): string
    {
        return 'order_number';
    }


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'order_number',
        'order_type',
        'date',
        'is_closed',
        'reference_no',
        'client_po_number',
        'jb_job_number',
        'description',
        'discount_percentage',
        'other_charges',
        'discount',
        'subtotal',
        'tax_amount',
        'total_amount',
        'status',
        'delivery_meta',
        'invoice_meta',
        'job_id',
        'job_number',
        'related_order_id',
        'customer_id',
        'advance_payment_id',
        'other_charges_account_id',
        'discount_account_id',
        'company_id',
        'created_by_user_id',
        'updated_by_user_id',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'id' => 'integer',
            'date' => 'date',
            'order_type' => 'string',
            'is_closed' => 'boolean',
            'discount_percentage' => 'decimal:2',
            'other_charges' => 'decimal:2',
            'discount' => 'decimal:2',
            'subtotal' => 'decimal:2',
            'tax_amount' => 'decimal:2',
            'total_amount' => 'decimal:2',
            'status' => 'string',
            'delivery_meta' => 'array',
            'invoice_meta' => 'array',
            'job_id' => 'integer',
            'job_number' => 'string',
            'jb_job_number' => 'string',
            'related_order_id' => 'integer',
            'customer_id' => 'integer',
            'advance_payment_id' => 'integer',
            'other_charges_account_id' => 'integer',
            'discount_account_id' => 'integer',
            'company_id' => 'integer',
            'created_by_user_id' => 'integer',
            'updated_by_user_id' => 'integer',
        ];
    }

    public function items(): HasMany
    {
        return $this->hasMany(SalesOrderItem::class);
    }

    public function deliveryDocuments(): HasMany
    {
        return $this->hasMany(DeliveryDocument::class);
    }

    public function salesInvoices(): HasMany
    {
        return $this->hasMany(SalesInvoice::class);
    }

    public function journalEntries()
    {
        return $this->hasMany(\App\Models\JournalEntry::class, 'reference_id')
            ->where('reference_type', SalesOrder::class);
    }

    public function computeDeliveryMeta(): array
    {
        $items = $this->items()
            ->with(['product.productGroup'])
            ->get();

        $meta = [
            'goods' => ['total' => 0.0, 'delivered' => 0.0, 'remaining' => 0.0],
            'document' => ['total' => 0.0, 'delivered' => 0.0, 'remaining' => 0.0],
        ];

        foreach ($items as $item) {
            $shippingType = $item->product?->productGroup?->shipping_type;
            $type = $shippingType === 'digital' ? 'document' : 'goods';

            $qty = (float) ($item->quantity ?? 0);
            $delivered = (float) ($item->delivered_quantity ?? 0);
            $remaining = max(0.0, $qty - $delivered);

            $meta[$type]['total'] += $qty;
            $meta[$type]['delivered'] += $delivered;
            $meta[$type]['remaining'] += $remaining;
        }

        foreach (['goods', 'document'] as $type) {
            foreach (['total', 'delivered', 'remaining'] as $key) {
                $meta[$type][$key] = round((float) $meta[$type][$key], 2);
            }
        }

        return $meta;
    }

    public function refreshDeliveryTracking(): void
    {
        $deliveryQuantities = DB::table('delivery_documents')
            ->join('delivery_document_items', 'delivery_document_items.delivery_document_id', '=', 'delivery_documents.id')
            ->whereNull('delivery_documents.deleted_at')
            ->whereNull('delivery_document_items.deleted_at')
            ->where('delivery_documents.is_locked', true)
            ->where('delivery_documents.sales_order_id', $this->id)
            ->whereNotNull('delivery_document_items.sales_order_item_id')
            ->groupBy('delivery_document_items.sales_order_item_id')
            ->select([
                'delivery_document_items.sales_order_item_id',
                DB::raw('COALESCE(SUM(delivery_document_items.quantity), 0) as delivered_quantity'),
            ])
            ->pluck('delivered_quantity', 'sales_order_item_id');

        $items = $this->items()->get(['id', 'quantity', 'delivered_quantity']);

        foreach ($items as $item) {
            $delivered = (float) ($deliveryQuantities[$item->id] ?? 0);
            $item->delivered_quantity = round($delivered, 2);
            $item->saveQuietly();
        }

        $this->delivery_meta = $this->computeDeliveryMeta();
        $this->saveQuietly();
    }

    public function computeInvoiceMeta(): array
    {
        $items = $this->items()->get(['quantity', 'invoiced_quantity']);
        $totalQty = (float) $items->sum('quantity');
        $invoicedQty = (float) $items->sum('invoiced_quantity');
        $remainingQty = max(0.0, $totalQty - $invoicedQty);

        return [
            'total' => round($totalQty, 2),
            'invoiced' => round($invoicedQty, 2),
            'remaining' => round($remainingQty, 2),
        ];
    }

    public function refreshInvoiceTracking(): void
    {
        $invoiceQuantities = DB::table('sales_invoices')
            ->join('sales_invoice_items', 'sales_invoice_items.sales_invoice_id', '=', 'sales_invoices.id')
            ->whereNull('sales_invoices.deleted_at')
            ->whereNull('sales_invoice_items.deleted_at')
            ->where('sales_invoices.sales_order_id', $this->id)
            ->whereNotNull('sales_invoice_items.sales_order_item_id')
            ->groupBy('sales_invoice_items.sales_order_item_id')
            ->select([
                'sales_invoice_items.sales_order_item_id',
                DB::raw('COALESCE(SUM(sales_invoice_items.quantity), 0) as invoiced_quantity'),
            ])
            ->pluck('invoiced_quantity', 'sales_order_item_id');

        $items = $this->items()->get(['id', 'quantity', 'invoiced_quantity']);

        foreach ($items as $item) {
            $invoiced = (float) ($invoiceQuantities[$item->id] ?? 0);
            $item->invoiced_quantity = round($invoiced, 2);
            $item->saveQuietly();
        }

        $this->invoice_meta = $this->computeInvoiceMeta();
        $this->saveQuietly();
    }

    public function recalculateTotalsFromItems(): void
    {
        $items = $this->items()->get(['total', 'tax_id']);
        $subtotal = (float) $items->sum('total');
        $discountPercentage = (float) ($this->discount_percentage ?? 0);
        $discount = (float) ($this->discount ?? 0);
        $otherCharges = (float) ($this->other_charges ?? 0);
        $taxAmount = 0.0;

        if ($discountPercentage > 0 && $subtotal > 0) {
            $discount = $subtotal * ($discountPercentage / 100);
        }

        $taxIds = $items->pluck('tax_id')->filter()->unique()->values();
        $taxesById = $taxIds->isEmpty()
            ? collect()
            : \App\Models\Tax::query()->whereIn('id', $taxIds)->get()->keyBy('id');

        foreach ($items as $item) {
            $lineTotal = (float) ($item->total ?? 0);
            $taxId = $item->tax_id;
            if (!$taxId) {
                continue;
            }

            $tax = $taxesById->get($taxId);
            $taxPercentage = (float) ($tax?->tax_percentage ?? 0);
            if ($taxPercentage <= 0) {
                continue;
            }

            $lineDiscount = $lineTotal * ($discountPercentage / 100);
            $taxBase = $lineTotal - $lineDiscount;
            $taxAmount += $taxBase * ($taxPercentage / 100);
        }

        $this->subtotal = $subtotal;
        $this->discount = $discount;
        $this->tax_amount = $taxAmount;
        $this->total_amount = $subtotal - $discount + $otherCharges + $taxAmount;
    }

    public function job(): BelongsTo
    {
        return $this->belongsTo(Project::class);
    }

    public function relatedOrder(): BelongsTo
    {
        return $this->belongsTo(SalesOrder::class, 'related_order_id');
    }

    public function customer(): BelongsTo
    {
        return $this->belongsTo(Contact::class);
    }

    public function advancePayment(): BelongsTo
    {
        return $this->belongsTo(AdvancePayment::class);
    }

    public function otherChargesAccount(): BelongsTo
    {
        return $this->belongsTo(Account::class);
    }

    public function discountAccount(): BelongsTo
    {
        return $this->belongsTo(Account::class);
    }

    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    public function createdByUser(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function updatedByUser(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function purchaseOrders(): HasMany
    {
        return $this->hasMany(PurchaseOrder::class);
    }

    /**
     * Get all orders linked via related_order_id (reverse relationship)
     */
    public function referencingOrders(): HasMany
    {
        return $this->hasMany(SalesOrder::class, 'related_order_id');
    }

    /**
     * Get all orders sharing the same job_number
     */
    public function ordersByJobNumber(): HasMany
    {
        return $this->hasMany(SalesOrder::class, 'job_number', 'job_number')
            ->where('id', '!=', $this->id);
    }

    /**
     * Get all related orders (by job_number or related_order_id)
     * This includes deposit, aktual, and other orders in the same group
     */
    public function allRelatedOrders(): \Illuminate\Database\Eloquent\Collection
    {
        $query = SalesOrder::where('id', '!=', $this->id);

        if ($this->job_number) {
            // Get all orders with same job_number
            $query->where(function ($q) {
                $q->where('job_number', $this->job_number)
                  ->orWhere('related_order_id', $this->id)
                  ->orWhere(function ($q2) {
                      if ($this->related_order_id) {
                          $q2->where('id', $this->related_order_id)
                              ->orWhere('related_order_id', $this->related_order_id);
                      }
                  });
            });
        } else {
            // Fall back to related_order_id only
            $query->where(function ($q) {
                $q->where('related_order_id', $this->id)
                  ->orWhere(function ($q2) {
                      if ($this->related_order_id) {
                          $q2->where('id', $this->related_order_id)
                              ->orWhere('related_order_id', $this->related_order_id);
                      }
                  });
            });
        }

        return $query->get();
    }

    /**
     * Get all deposit orders related to this order
     */
    public function relatedDepositOrders(): \Illuminate\Database\Eloquent\Collection
    {
        return $this->allRelatedOrders()->where('order_type', 'deposit')->values();
    }

    /**
     * Get all aktual orders related to this order
     */
    public function relatedAktualOrders(): \Illuminate\Database\Eloquent\Collection
    {
        return $this->allRelatedOrders()->where('order_type', 'aktual')->values();
    }

    /**
     * Check if this order has related orders (deposit, aktual, etc.)
     */
    public function hasRelatedOrders(): bool
    {
        return $this->allRelatedOrders()->count() > 0;
    }

    /**
     * Get the order group summary (for multi deposit/aktual)
     */
    public function getOrderGroupSummary(): array
    {
        $relatedOrders = $this->allRelatedOrders();
        $allOrders = $relatedOrders->push($this);

        $depositOrders = $allOrders->where('order_type', 'deposit');
        $aktualOrders = $allOrders->where('order_type', 'aktual');
        $standarOrders = $allOrders->where('order_type', 'standar');

        return [
            'total_orders' => $allOrders->count(),
            'deposit_count' => $depositOrders->count(),
            'deposit_total' => $depositOrders->sum('total_amount'),
            'aktual_count' => $aktualOrders->count(),
            'aktual_total' => $aktualOrders->sum('total_amount'),
            'standar_count' => $standarOrders->count(),
            'standar_total' => $standarOrders->sum('total_amount'),
            'grand_total' => $allOrders->sum('total_amount'),
        ];
    }
}
