<?php

namespace App\Filament\Resources\PurchaseInvoices\Schemas;

use App\Filament\Forms\Components\RoundedIntegerMoneyInput;
use App\Forms\Components\SelectWithModal;
use App\Traits\HasAutoGeneratedCode;
use Filament\Actions\Action;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\Placeholder;
use Filament\Forms\Components\Repeater;
use Filament\Forms\Components\Repeater\TableColumn;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Hidden;
use Filament\Forms\Components\Toggle;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Filament\Support\Enums\Alignment;
use App\Filament\Forms\Components\NumberInput;


class PurchaseInvoiceForm
{
    use HasAutoGeneratedCode;

    protected static function resolveCompanyId(callable $get): ?int
    {
        $companyId = $get('company_id');
        if ($companyId && $companyId !== 'all') {
            return (int) $companyId;
        }
        $selectedCompanyId = session('selected_company_id');
        if ($selectedCompanyId && $selectedCompanyId !== 'all') {
            return (int) $selectedCompanyId;
        }
        return null;
    }

    /**
     * Get the document type for purchase invoices
     */
    protected function getDocumentType(): string
    {
        return 'purchase_invoice';
    }

    /**
     * Get the code field name for purchase invoices
     */
    protected function getCodeFieldName(): string
    {
        return 'invoice_number';
    }
    protected static function calculateTotals(callable $get): array
    {
        $items = $get('items') ?? [];
        $discountPercentage = (float) ($get('discount_percentage') ?? 0);
        $otherCharges = \App\Filament\Forms\Components\NumberInput::parseToFloat($get('other_charges') ?? 0);
        $subtotal = 0.0;
        $taxTotal = 0.0;

        foreach ($items as $item) {
            $qty = \App\Filament\Forms\Components\NumberInput::parseToFloat($item['quantity'] ?? 0);
            $price = \App\Filament\Forms\Components\NumberInput::parseToFloat($item['unit_price'] ?? 0);
            $line = $qty * $price;
            $subtotal += $line;
            $taxId = $item['tax_id'] ?? null;
            if ($taxId) {
                $tax = \App\Models\Tax::find($taxId);
                if ($tax && $tax->tax_percentage) {
                    $lineDiscount = $line * ($discountPercentage / 100);
                    $taxBase = $line - $lineDiscount;
                    $taxTotal += $taxBase * ((float) $tax->tax_percentage) / 100;
                }
            }
        }

        $discountAmount = $subtotal * ($discountPercentage / 100);
        $total = $subtotal - $discountAmount + $otherCharges + $taxTotal;
        $paidAmount = \App\Filament\Forms\Components\NumberInput::parseToFloat($get('paid_amount') ?? 0);
        $outstanding = $total - $paidAmount;
        return [
            'subtotal' => $subtotal,
            'discount' => $discountAmount,
            'tax' => $taxTotal,
            'total' => $total,
            'outstanding' => $outstanding,
        ];
    }

    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make()
                    ->schema([
                        Select::make('company_id')
                            ->relationship('company', 'name')
                            ->default(function () {
                                $selectedCompanyId = session('selected_company_id');
                                return $selectedCompanyId && $selectedCompanyId !== 'all'
                                    ? $selectedCompanyId
                                    : null;
                            })
                            ->hidden(function () {
                                $selectedCompanyId = session('selected_company_id');
                                return !$selectedCompanyId || $selectedCompanyId !== 'all';
                            })
                            ->searchable()
                            ->preload()
                            ->nullable()
                            ->columnSpanFull(),
                        Select::make('supplier_id')
                            ->label('Supplier')
                            ->disabled(fn ($record) => (bool) ($record?->is_locked))
                            ->relationship(
                                name: 'supplier',
                                titleAttribute: 'name',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $companyId = self::resolveCompanyId($get);
                                    if ($companyId) {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    return $query->where('is_supplier', true)->orderBy('name');
                                }
                            )
                            ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->name} ({$record->contact_code})")
                            ->searchable(['name', 'contact_code'])
                            ->preload()
                            ->live(onBlur: true)
                            ->required()
                            ->createOptionForm([
                                TextInput::make('name')
                                    ->label(__('Name'))
                                    ->required(),
                                (new \App\Filament\Resources\Contacts\Schemas\ContactForm)->getCodeField('contact_code', __('Contact Code'))
                                    ->unique(\App\Models\Contact::class, 'contact_code', ignoreRecord: true,
                                        modifyRuleUsing: function ($rule) {
                                            // Get the company_id from the session
                                            $companyId = session('selected_company_id');

                                            // If there's a selected company, scope the uniqueness check to that company
                                            if ($companyId && $companyId !== 'all') {
                                                $rule->where('company_id', $companyId);
                                            }
                                            // If no company is selected, the uniqueness check will apply to all records
                                            // This ensures records are unique within their company
                                            return $rule;
                                        },
                                    ),
                                TextInput::make('email')
                                    ->label(__('Email'))
                                    ->email(),
                                TextInput::make('phone')
                                    ->label(__('Phone'))
                                    ->tel(),
                                Hidden::make('is_supplier')
                                    ->default(true),
                                Hidden::make('company_id')
                                    ->default(function (callable $get) {
                                        $companyId = $get('company_id') ?: session('selected_company_id');
                                        return ($companyId && $companyId !== 'all') ? $companyId : null;
                                    }),
                                Hidden::make('created_by_user_id')
                                    ->default(function () {
                                        return auth()->id();
                                    }),
                            ])
                            ->createOptionUsing(function (array $data) {
                                $contact = \App\Models\Contact::create($data);
                                return $contact->id;
                            }),
                        Select::make('goods_receipt_id')
                            ->label('Goods Receipt')
                            ->disabled(fn ($record) => (bool) ($record?->is_locked))
                            ->relationship(
                                name: 'goodsReceipt',
                                titleAttribute: 'receipt_number',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $companyId = self::resolveCompanyId($get);
                                    if ($companyId) {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }

                                    // Filter by supplier if selected
                                    $supplierId = $get('supplier_id');
                                    if ($supplierId) {
                                        $query->where('supplier_id', $supplierId);
                                    }

                                    // Only show locked goods receipts
                                    $query->where('is_locked', true);

                                    return $query->orderBy('receipt_number', 'desc');
                                }
                            )
                            ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->receipt_number} - {$record->supplier->name}")
                            ->searchable(['receipt_number'])
                            ->preload()
                            ->live()
                            ->nullable()
                            ->placeholder('Select Goods Receipt')
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                if ($state) {
                                    $goodsReceipt = \App\Models\GoodsReceipt::with(['items.purchaseOrderItem'])->find($state);
                                    if ($goodsReceipt) {
                                        $set('supplier_id', $goodsReceipt->supplier_id);
                                        $set('purchase_order_id', $goodsReceipt->purchase_order_id);

                                        // Copy totals from PO if available
                                        $po = $goodsReceipt->purchaseOrder;
                                        if ($po) {
                                            if ($po->discount_percentage) {
                                                $set('discount_percentage', $po->discount_percentage);
                                            }
                                            if ($po->other_charges) {
                                                $set('other_charges', $po->other_charges);
                                                $set('other_charges_display', NumberInput::formatRoundedIntegerDisplay($po->other_charges));
                                            }
                                        }

                                        // Auto-populate items from GR received quantities
                                        if ($goodsReceipt->items) {
                                            $items = [];
                                            foreach ($goodsReceipt->items as $grItem) {
                                                $poItem = $grItem->purchaseOrderItem;
                                                $receivedQty = (float) ($grItem->quantity ?? 0) - (float) ($grItem->returned_quantity ?? 0);
                                                $unitPrice = $poItem ? (float) ($poItem->unit_price ?? 0) : 0;
                                                $itemTotal = $receivedQty * $unitPrice;
                                                $items[] = [
                                                    'goods_receipt_item_id' => $grItem->id,
                                                    'purchase_order_item_id' => $grItem->purchase_order_item_id,
                                                    'product_id' => $grItem->product_id,
                                                    'quantity' => $receivedQty,
                                                    'quantity_display' => NumberInput::formatRoundedIntegerDisplay($receivedQty),
                                                    'unit_price' => $unitPrice,
                                                    'unit_price_display' => NumberInput::formatRoundedIntegerDisplay($unitPrice),
                                                    'tax_id' => $poItem->tax_id ?? null,
                                                    'unit_id' => $grItem->unit_id ?? ($poItem->unit_id ?? null),
                                                    'description' => $grItem->description ?? ($poItem->description ?? null),
                                                    'total' => $itemTotal,
                                                ];
                                            }
                                            $set('items', $items);

                                            // Calculate and update all totals
                                            $discountPercentage = $po->discount_percentage ?? 0;
                                            $otherCharges = $po->other_charges ?? 0;
                                            $dataForCalculation = function($key) use ($items, $discountPercentage, $otherCharges) {
                                                if ($key === 'items') return $items;
                                                if ($key === 'discount_percentage') return $discountPercentage;
                                                if ($key === 'other_charges') return $otherCharges;
                                                return null;
                                            };

                                            $c = self::calculateTotals($dataForCalculation);
                                            $set('subtotal', $c['subtotal']);
                                            $set('discount', $c['discount']);
                                            $set('tax_amount', $c['tax']);
                                            $set('total', $c['total']);
                                            $set('outstanding_amount', $c['outstanding']);
                                        }
                                    }
                                } else if (!$state) {
                                    // Clear items if no goods receipt selected
                                    $set('items', []);
                                    $set('purchase_order_id', null);
                                    $set('other_charges', 0);
                                    $set('other_charges_display', NumberInput::formatRoundedIntegerDisplay(0));
                                    $set('discount_percentage', 0);
                                    $set('subtotal', 0);
                                    $set('discount', 0);
                                    $set('tax_amount', 0);
                                    $set('total', 0);
                                }
                            }),
                        Hidden::make('purchase_order_id'),
                        DatePicker::make('date')
                            ->label('Date')
                            ->required()
                            ->default(now())
                            ->live()
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                $paymentTermId = $get('payment_term_id');
                                if ($paymentTermId && $state) {
                                    $paymentTerm = \App\Models\PaymentTerm::find($paymentTermId);
                                    if ($paymentTerm) {
                                        $dueDate = \Carbon\Carbon::parse($state)->addDays($paymentTerm->due_days);
                                        $set('due_date', $dueDate->format('Y-m-d'));
                                    }
                                }
                            }),
                        Select::make('payment_term_id')
                            ->label('Payment Term')
                            ->relationship(
                                name: 'paymentTerm',
                                titleAttribute: 'name',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $companyId = self::resolveCompanyId($get);
                                    if ($companyId) {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    return $query->where('is_active', true)->orderBy('due_days');
                                }
                            )
                            ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->name} ({$record->due_days} days)")
                            ->searchable()
                            ->preload()
                            ->live()
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                $date = $get('date');
                                if ($state && $date) {
                                    $paymentTerm = \App\Models\PaymentTerm::find($state);
                                    if ($paymentTerm) {
                                        $dueDate = \Carbon\Carbon::parse($date)->addDays($paymentTerm->due_days);
                                        $set('due_date', $dueDate->format('Y-m-d'));
                                    }
                                }
                            }),
                        DatePicker::make('due_date')
                            ->label('Due Date')
                            ->required()
                            ->default(now()),
                        TextInput::make('reference_no')
                            ->maxLength(255)
                            ->label('Reference No.'),
                        (new static)->getCodeField('invoice_number', 'Invoice No.')
                            ->unique('purchase_invoices', 'invoice_number', ignoreRecord: true,
                                modifyRuleUsing: fn ($rule) => $rule->where(function ($query) {
                                    $companyId = session('selected_company_id');
                                    if ($companyId && $companyId !== 'all') {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    $query->whereNull('deleted_at');
                                    return $query;
                                })
                            ),
                        Textarea::make('description')
                            ->rows(1)
                            ->maxLength(65535)
                            ->label('Description'),
                        Select::make('status')
                            ->label('Status')
                            ->options(function ($get, $record) {
                                // If the record doesn't exist (creating new) or status is draft, show only draft/posted
                                if (!$record || $get('status') === 'draft') {
                                    return [
                                        'draft' => 'Draft',
                                        'posted' => 'Posted',
                                    ];
                                }
                                // Otherwise, show all options
                                return [
                                    'draft' => 'Draft',
                                    'posted' => 'Posted',
                                    'received' => 'Received',
                                    'approved' => 'Approved',
                                    'paid' => 'Paid',
                                    'partially_paid' => 'Partially Paid',
                                    'disputed' => 'Disputed',
                                    'cancelled' => 'Cancelled',
                                ];
                            })
                            ->default('posted')
                            ->required()
                            ->native(false)
                            ->live()
                            ->disabled(function ($get, $record) {
                                // Disable the field if the record exists and status is not draft
                                return $record && $record->status !== 'draft';
                            }),
                        Hidden::make('subtotal')
                            ->default(0)
                            ->dehydrated(),
                        Hidden::make('discount')
                            ->default(0)
                            ->dehydrated(),
                        Hidden::make('tax_amount')
                            ->default(0)
                            ->dehydrated(),
                        Hidden::make('total')
                            ->default(0)
                            ->dehydrated(),
                        Hidden::make('outstanding_amount')
                            ->default(0)
                            ->dehydrated(),
                    ])
                    ->columns(4)
                    ->columnSpanFull(),

                // Invoice Items
                Repeater::make('items')
                    ->relationship()
                    ->hiddenLabel()
                    ->addActionLabel(__('Add New Item'))
                    ->required()
                    ->addable(fn (callable $get) => !(bool) $get('is_locked'))
                    ->table([
                        TableColumn::make('Product')->width('20%')->alignment(Alignment::Start),
                        TableColumn::make('Quantity')->width('10%')->alignment(Alignment::End),
                        TableColumn::make('Unit Price')->width('14%')->alignment(Alignment::End),
                        TableColumn::make('Tax')->width('11%')->alignment(Alignment::Start),
                        TableColumn::make('Unit')->width('11%')->alignment(Alignment::Start),
                        TableColumn::make('Description')->width('16%')->alignment(Alignment::Start),
                        TableColumn::make('Total')->width('10%')->alignment(Alignment::End),
                    ])
                    ->schema([
                        Hidden::make('purchase_order_item_id'),
                        Hidden::make('goods_receipt_item_id'),
                        Select::make('product_id')
                            ->required()
                            ->searchable()
                            ->preload()
                            ->label('Product')
                            ->disabled(fn (callable $get) => (bool) $get('../../is_locked'))
                            ->relationship(
                                name: 'product',
                                titleAttribute: 'name',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $companyId = self::resolveCompanyId($get);
                                    if ($companyId) {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    return $query->orderBy('name');
                                }
                            )
                            ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->name} ({$record->code})")
                            ->searchable(['name', 'code'])
                            ->live()
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                $product = \App\Models\Product::find($state);
                                if ($product) {
                                    if ($product->cost_price) {
                                        $set('unit_price', $product->cost_price);
                                        $set('unit_price_display', NumberInput::formatRoundedIntegerDisplay($product->cost_price));
                                    }
                                    if ($product->unit_id) {
                                        $set('unit_id', $product->unit_id);
                                    }
                                    if ($product->description) {
                                        $set('description', $product->description);
                                    }
                                    // Set tax from product if available
                                    if ($product->tax_id) {
                                        $set('tax_id', $product->tax_id);
                                    }
                                }
                            })
                            ->createOptionForm([
                                TextInput::make('name')
                                    ->label('Name')
                                    ->required(),
                                (new \App\Filament\Resources\Products\Schemas\ProductForm)->getCodeField('code', 'Product Code')
                                    ->unique(
                                        \App\Models\Product::class,
                                        'code',
                                        ignoreRecord: true,
                                        modifyRuleUsing: function ($rule) {
                                            $companyId = session('selected_company_id');
                                            if ($companyId && $companyId !== 'all') {
                                                $rule->where('company_id', $companyId);
                                            }
                                            return $rule;
                                        },
                                    ),
                                Select::make('product_group_id')
                                    ->label('Product Group')
                                    ->relationship(
                                        "productGroup",
                                        "name",
                                        modifyQueryUsing: function ($query) {
                                            $selectedCompanyId = session('selected_company_id');
                                            if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                                                $query->where('company_id', $selectedCompanyId);
                                            }
                                            return $query;
                                        }
                                    )
                                    ->searchable()
                                    ->preload()
                                    ->required(),
                                ...RoundedIntegerMoneyInput::schema(
                                    name: 'cost_price',
                                    label: 'Cost Price',
                                    required: false,
                                    defaultDecimal: '0.00',
                                ),
                                Select::make('unit_id')
                                    ->label('Unit')
                                    ->searchable()
                                    ->options(function () {
                                        $selectedCompanyId = session('selected_company_id');
                                        $q = \App\Models\Unit::query();
                                        if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                                            $q->where('company_id', $selectedCompanyId);
                                        } else {
                                            $q->whereNull('company_id');
                                        }
                                        return $q->orderBy('name')->pluck('name', 'id')->toArray();
                                    }),
                                Textarea::make('description')
                                    ->label('Description')
                                    ->rows(2),
                                Hidden::make('company_id')
                                    ->default(function () {
                                        $selectedCompanyId = session('selected_company_id');
                                        return ($selectedCompanyId && $selectedCompanyId !== 'all') ? $selectedCompanyId : null;
                                    }),
                                Hidden::make('created_by_user_id')
                                    ->default(function () {
                                        return auth()->id();
                                    }),
                            ])
                            ->createOptionUsing(function (array $data) {
                                $product = \App\Models\Product::create($data);
                                return $product->id;
                            }),
                        ...RoundedIntegerMoneyInput::schema(
                            name: 'quantity',
                            label: 'Quantity',
                            required: true,
                            defaultDecimal: '1.00',
                            afterUpdated: function ($decimal, callable $set, callable $get) {
                                $quantity = NumberInput::parseToFloat($decimal);
                                $unitPrice = NumberInput::parseToFloat($get('unit_price') ?? 0);
                                $set('total', $quantity * $unitPrice);

                                $c = self::calculateTotals($get);
                                $set('subtotal', $c['subtotal']);
                                $set('discount', $c['discount']);
                                $set('tax_amount', $c['tax']);
                                $set('total', $c['total']);
                                $set('outstanding_amount', $c['outstanding']);
                            },
                        ),
                        ...RoundedIntegerMoneyInput::schema(
                            name: 'unit_price',
                            label: 'Unit Price',
                            required: true,
                            afterUpdated: function ($decimal, callable $set, callable $get) {
                                $quantity = NumberInput::parseToFloat($get('quantity') ?? 0);
                                $unitPrice = NumberInput::parseToFloat($decimal);
                                $set('total', $quantity * $unitPrice);

                                $c = self::calculateTotals($get);
                                $set('subtotal', $c['subtotal']);
                                $set('discount', $c['discount']);
                                $set('tax_amount', $c['tax']);
                                $set('total', $c['total']);
                                $set('outstanding_amount', $c['outstanding']);
                            },
                        ),
                        Select::make('tax_id')
                            ->searchable()
                            ->preload()
                            ->label('Tax')
                            ->relationship(
                                name: 'tax',
                                titleAttribute: 'name',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $companyId = self::resolveCompanyId($get);
                                    if ($companyId) {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    return $query->orderBy('name');
                                }
                            )
                            ->getOptionLabelFromRecordUsing(fn ($record) => $record->name)
                            ->live(onBlur: true)
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                $c = self::calculateTotals($get);
                                $set('subtotal', $c['subtotal']);
                                $set('discount', $c['discount']);
                                $set('tax_amount', $c['tax']);
                                $set('total', $c['total']);
                                $set('outstanding_amount', $c['outstanding']);
                            }),
                        Select::make('unit_id')
                            ->searchable()
                            ->preload()
                            ->label('Unit')
                            ->relationship(
                                name: 'unit',
                                titleAttribute: 'name',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $companyId = self::resolveCompanyId($get);
                                    if ($companyId) {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    return $query->orderBy('name');
                                }
                            )
                            ->getOptionLabelFromRecordUsing(fn ($record) => $record->name),

                        Textarea::make('description')
                            ->label('Description')
                            ->rows(1),
                        Hidden::make('total')
                            ->default(0),
                        Placeholder::make('total_amount_display')
                            ->label('Total')
                            ->content(function ($get) {
                                $quantity = NumberInput::parseToFloat($get('quantity') ?? 0);
                                $unitPrice = NumberInput::parseToFloat($get('unit_price') ?? 0);
                                $total = $quantity * $unitPrice;
                                return number_format($total, 0, ',', '.');
                            })
                            ->extraAttributes([
                                'class' => 'font-semibold text-green-600 py-2 px-3 bg-gray-50 rounded-md border border-gray-200'
                            ]),
                    ])
                    ->defaultItems(0)
                    ->live()
                    ->reorderable()
                    ->collapsible()
                    ->compact()
                    ->columnSpan('full')
                    ->afterStateUpdated(function ($state, callable $set, callable $get) {
                        // Trigger total recalculation when items change
                        $c = self::calculateTotals($get);
                        $set('subtotal', $c['subtotal']);
                        $set('discount', $c['discount']);
                        $set('tax_amount', $c['tax']);
                        $set('total_amount', $c['total']);
                    }),

                Section::make()
                    ->schema([
                        Placeholder::make('empty_col_1')
                            ->hiddenLabel()
                            ->columnSpan(1),
                        Placeholder::make('subtotal_display')
                            ->inlineLabel()
                            ->label('Subtotal')
                            ->content(function (callable $get) {
                                $c = self::calculateTotals($get);
                                return 'Rp ' . number_format($c['subtotal'], 0, ',', '.');
                            })
                            ->live()
                            ->reactive()
                            ->extraAttributes(['style' => 'text-align:right'])
                            ->columnSpan(1),
                        Placeholder::make('empty_col_2')
                            ->hiddenLabel()
                            ->columnSpan(1),
                        ...RoundedIntegerMoneyInput::schema(
                            name: 'other_charges',
                            label: 'Other Charges',
                            inlineLabel: true,
                            defaultDecimal: '0.00',
                            columnSpan: 1,
                            afterUpdated: function ($decimal, callable $set, callable $get) {
                                $c = self::calculateTotals($get);
                                $set('subtotal', $c['subtotal']);
                                $set('discount', $c['discount']);
                                $set('tax_amount', $c['tax']);
                                $set('total', $c['total']);
                                $set('outstanding_amount', $c['outstanding']);
                            },
                        ),
                        Placeholder::make('empty_col_3')
                            ->hiddenLabel()
                            ->columnSpan(1),
                        TextInput::make('discount_percentage')
                            ->default(0)
                            ->numeric()
                            ->suffix('%')
                            ->inlineLabel()
                            ->label('Discount')
                            ->live()
                            ->reactive()
                            ->afterStateHydrated(function ($component, $state, $record) {
                                if ($record && $record->subtotal > 0 && $record->discount > 0) {
                                    $discountPercentage = ($record->discount / $record->subtotal) * 100;
                                    $component->state($discountPercentage);
                                } else {
                                    $component->state(0);
                                }
                            })
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                $c = self::calculateTotals($get);
                                $set('subtotal', $c['subtotal']);
                                $set('discount', $c['discount']);
                                $set('tax_amount', $c['tax']);
                                $set('total', $c['total']);
                                $set('outstanding_amount', $c['outstanding']);
                            })
                            ->extraInputAttributes(['style' => 'text-align:right'])
                            ->columnSpan(1),
                        Placeholder::make('empty_col_4')
                            ->hiddenLabel()
                            ->columnSpan(1),
                        Placeholder::make('discount_amount_display')
                            ->inlineLabel()
                            ->label('Discount Amount')
                            ->content(function (callable $get) {
                                $c = self::calculateTotals($get);
                                return 'Rp ' . number_format($c['discount'], 0, ',', '.');
                            })
                            ->live()
                            ->reactive()
                            ->extraAttributes(['style' => 'text-align:right'])
                            ->columnSpan(1),
                        Placeholder::make('empty_col_5')
                            ->hiddenLabel()
                            ->columnSpan(1),
                        Placeholder::make('tax_amount')
                            ->inlineLabel()
                            ->label('Tax Amount')
                            ->content(function (callable $get) {
                                $c = self::calculateTotals($get);
                                return 'Rp ' . number_format($c['tax'], 0, ',', '.');
                            })
                            ->live()
                            ->reactive()
                            ->extraAttributes(['style' => 'text-align:right'])
                            ->columnSpan(1),
                        Placeholder::make('empty_col_6')
                            ->hiddenLabel()
                            ->columnSpan(1),
                        Placeholder::make('total_amount_display')
                            ->inlineLabel()
                            ->label('Total')
                            ->live()
                            ->reactive()
                            ->content(function (callable $get) {
                                $c = self::calculateTotals($get);
                                return 'Rp ' . number_format($c['total'], 0, ',', '.');
                            })
                            ->extraAttributes([
                                'class' => 'font-bold text-lg text-green-600'
                            ])
                            ->extraAttributes(['style' => 'text-align:right'])
                            ->columnSpan(1),
                    ])
                    ->columns(2)
                    ->columnSpanFull(),

            ]);
    }
}