<?php

namespace App\Filament\Resources\ProductGroups\Schemas;

use App\Traits\HasAutoGeneratedCode;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;

class ProductGroupForm
{
    use HasAutoGeneratedCode;

    protected function getDocumentType(): string
    {
        return 'product_group';
    }

    protected function getCodeFieldName(): string
    {
        return 'code';
    }

    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make(__('Product Group Information'))
                    ->schema([
                        TextInput::make('name')
                            ->required()
                            ->label(__('Product Group Name')),
                        (new static)->getCodeField('code', __('Product Group Code'))
                            ->rule('required')
                            ->rule(function (?\App\Models\ProductGroup $record) {
                                return function (string $attribute, $value, \Closure $fail) use ($record) {
                                    $query = \App\Models\ProductGroup::where('code', $value);

                                    if ($record && $record->id) {
                                        // Editing: exclude current record
                                        $query->where('id', '!=', $record->id);
                                    }

                                    // Scope to the same company
                                    if ($record && $record->company_id) {
                                        $query->where('company_id', $record->company_id);
                                    } else {
                                        $companyId = session('selected_company_id') ?? auth()->user()->companies()->first()?->id;
                                        $query->where('company_id', $companyId);
                                    }

                                    if ($query->exists()) {
                                        $fail(__('The :attribute has already been taken.'));
                                    }
                                };
                            }),
                        Select::make('shipping_type')
                            ->options([
                                'physical' => __('Produk Fisik'),
                                'digital' => __('Produk Digital'),
                            ])
                            ->default('physical')
                            ->required()
                            ->label(__('Jenis Produk')),
                        Toggle::make('is_active')
                            ->required()
                            ->default(true)
                            ->label(__('Active')),
                        Select::make('company_id')
                            ->relationship(
                                name: 'company',
                                titleAttribute: 'name',
                                modifyQueryUsing: function ($query) {
                                    $user = auth()->user();
                                    if ($user) {
                                        $userCompanyIds = $user->companies()->pluck('companies.id');
                                        if ($userCompanyIds->isNotEmpty()) {
                                            $query->whereIn('companies.id', $userCompanyIds);
                                        } else {
                                            // If user has no assigned companies, return no results
                                            $query->whereRaw('1 = 0');
                                        }
                                    }
                                }
                            )
                            ->default(function () {
                                $selectedCompanyId = session('selected_company_id');
                                $user = auth()->user();
                                if ($selectedCompanyId) {
                                    // Verify user has access to this company
                                    if ($user && $user->companies()->where('companies.id', $selectedCompanyId)->exists()) {
                                        return $selectedCompanyId;
                                    }
                                }
                                return null;
                            })
                            ->hidden()
                            ->searchable()
                            ->preload()
                            ->required()
                            ->label(__('Company')),

                        Select::make('created_by_user_id')
                            ->relationship('createdByUser', 'name')
                            ->default(function () {
                                return auth()->id();
                            })
                            ->disabled()
                            ->required()
                            ->label(__('Created By')),
                    ])
                    ->columns(2)
                    ->columnSpanFull(),
            ]);
    }
}
