<?php

namespace App\Filament\Resources\DeferredRevenues\Schemas;

use App\Filament\Forms\Components\NumberInput;
use App\Traits\HasAutoGeneratedCode;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;

class DeferredRevenueForm
{
    use HasAutoGeneratedCode;

    protected function getDocumentType(): string
    {
        return 'deferred_revenue';
    }

    protected function getCodeFieldName(): string
    {
        return 'contract_number';
    }

    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make(__('Contract Information'))
                    ->schema([
                        (new static)->getCodeField('contract_number', __('Contract Number'))
                            ->unique(ignoreRecord: true),
                        DatePicker::make('date')
                            ->required()
                            ->default(now())
                            ->label(__('Contract Date')),
                        Textarea::make('description')
                            ->columnSpanFull()
                            ->rows(2)
                            ->label(__('Description')),
                        TextInput::make('customer_name')
                            ->maxLength(255)
                            ->label(__('Customer Name')),
                        Select::make('customer_id')
                            ->relationship('customer', 'name', modifyQueryUsing: function ($query) {
                                $selectedCompanyId = session('selected_company_id');
                                if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                                    $query->where('company_id', $selectedCompanyId);
                                }
                                return $query->where('is_customer', true);
                            })
                            ->searchable()
                            ->preload()
                            ->live()
                            ->afterStateUpdated(fn ($state, $set) => $set('sales_invoice_id', null))
                            ->label(__('Customer (Contact)')),
                        Select::make('sales_invoice_id')
                            ->relationship('salesInvoice', 'invoice_number', modifyQueryUsing: function ($query, callable $get) {
                                $selectedCompanyId = session('selected_company_id');
                                if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                                    $query->where('company_id', $selectedCompanyId);
                                }
                                $query->where('status', 'posted');
                                $customerId = $get('customer_id');
                                if ($customerId) {
                                    $query->where('customer_id', $customerId);
                                }
                                return $query;
                            })
                            ->searchable()
                            ->preload()
                            ->label(__('Related Sales Invoice'))
                            ->nullable(),
                    ])
                    ->columns(2),

                Section::make(__('Revenue Recognition'))
                    ->schema([
                        NumberInput::make('total_amount')
                            ->prefix('Rp')
                            ->required()
                            ->decimal(false)
                            ->label(__('Total Contract Amount')),
                        TextInput::make('total_periods')
                            ->required()
                            ->numeric()
                            ->minValue(1)
                            ->label(__('Number of Periods (Months)'))
                            ->helperText(__('Number of months over which revenue will be recognized'))
                            ->afterStateUpdated(function ($state, $set, $get) {
                                $start = $get('period_start');
                                if ($start && $state) {
                                    $end = \Carbon\Carbon::parse($start)->addMonths((int) $state)->subDay();
                                    $set('period_end', $end);
                                }
                            }),
                        Select::make('recognition_method')
                            ->options([
                                'straight_line' => __('Straight Line (Equal Monthly)'),
                            ])
                            ->default('straight_line')
                            ->required()
                            ->label(__('Recognition Method')),
                        DatePicker::make('period_start')
                            ->required()
                            ->label(__('Period Start Date'))
                            ->afterStateUpdated(function ($state, $set, $get) {
                                $start = $state;
                                $periods = $get('total_periods');
                                if ($start && $periods) {
                                    $end = \Carbon\Carbon::parse($start)->addMonths((int) $periods)->subDay();
                                    $set('period_end', $end);
                                }
                            }),
                        DatePicker::make('period_end')
                            ->required()
                            ->label(__('Period End Date')),
                    ])
                    ->columns(2),

                Section::make(__('Account Configuration'))
                    ->schema([
                        Select::make('deferred_revenue_account_id')
                            ->relationship('deferredRevenueAccount', 'name', modifyQueryUsing: function ($query) {
                                $selectedCompanyId = session('selected_company_id');
                                $query->where('is_header', false)->where('is_active', true)->where('account_type', 'current_liability');
                                if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                                    $query->where('company_id', $selectedCompanyId);
                                }
                                return $query;
                            })
                            ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->code} - {$record->name}")
                            ->searchable()
                            ->preload()
                            ->label(__('Deferred Revenue Account (Liability)'))
                            ->helperText(__('Leave empty to use account mapping default')),
                        Select::make('revenue_account_id')
                            ->relationship('revenueAccount', 'name', modifyQueryUsing: function ($query) {
                                $selectedCompanyId = session('selected_company_id');
                                $query->where('is_header', false)->where('is_active', true)->where('account_type', 'revenue');
                                if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                                    $query->where('company_id', $selectedCompanyId);
                                }
                                return $query;
                            })
                            ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->code} - {$record->name}")
                            ->searchable()
                            ->preload()
                            ->label(__('Revenue Account'))
                            ->helperText(__('Leave empty to use account mapping default')),
                        Select::make('company_id')
                            ->relationship(
                                name: 'company',
                                titleAttribute: 'name',
                                modifyQueryUsing: function ($query) {
                                    $user = auth()->user();
                                    if ($user) {
                                        $userCompanyIds = $user->companies()->pluck('companies.id');
                                        if ($userCompanyIds->isNotEmpty()) {
                                            $query->whereIn('companies.id', $userCompanyIds);
                                        } else {
                                            $query->whereRaw('1 = 0');
                                        }
                                    }
                                }
                            )
                            ->default(function () {
                                $selectedCompanyId = session('selected_company_id');
                                $user = auth()->user();
                                if ($selectedCompanyId) {
                                    if ($user && $user->companies()->where('companies.id', $selectedCompanyId)->exists()) {
                                        return $selectedCompanyId;
                                    }
                                }
                                return null;
                            })
                            ->hidden()
                            ->searchable()
                            ->preload()
                            ->required()
                            ->label(__('Company')),
                    ])
                    ->columns(2),
            ]);
    }
}
