<?php

namespace App\Filament\Resources\SalesOrders\Schemas;

use App\Filament\Forms\Components\NumberInput;
use App\Filament\Forms\Components\RoundedIntegerMoneyInput;
use App\Traits\HasAutoGeneratedCode;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\Placeholder;
use Filament\Forms\Components\Repeater;
use Filament\Forms\Components\Repeater\TableColumn;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Filament\Support\Enums\Alignment;
use Filament\Forms\Components\Hidden;


class SalesOrderForm
{
    use HasAutoGeneratedCode;

    protected static function calculateTotals(callable $get): array
    {
        $items = $get('items') ?? [];
        $discountPercentage = (float) ($get('discount_percentage') ?? 0);
        $otherCharges = NumberInput::parseToFloat($get('other_charges') ?? 0);
        $subtotal = 0.0;
        $taxTotal = 0.0;
        foreach ($items as $item) {
            $qty = NumberInput::parseToFloat($item['quantity'] ?? 0);
            $price = NumberInput::parseToFloat($item['unit_price'] ?? 0);
            $line = $qty * $price;
            $subtotal += $line;
            $taxId = $item['tax_id'] ?? null;
            if ($taxId) {
                $tax = \App\Models\Tax::find($taxId);
                if ($tax && $tax->tax_percentage) {
                    $lineDiscount = $line * ($discountPercentage / 100);
                    $taxBase = $line - $lineDiscount;
                    $taxTotal += $taxBase * ((float) $tax->tax_percentage) / 100;
                }
            }
        }
        $discountAmount = $subtotal * ($discountPercentage / 100);
        $total = $subtotal - $discountAmount + $otherCharges + $taxTotal;
        return [
            'subtotal' => $subtotal,
            'discount' => $discountAmount,
            'tax' => $taxTotal,
            'total' => $total,
        ];
    }

    protected static function resolveCompanyId(callable $get): ?int
    {
        $companyId = $get('company_id');
        if ($companyId && $companyId !== 'all') {
            return (int) $companyId;
        }
        $selectedCompanyId = session('selected_company_id');
        if ($selectedCompanyId && $selectedCompanyId !== 'all') {
            return (int) $selectedCompanyId;
        }
        return null;
    }

    protected function getDocumentType(): string
    {
        return 'sales_order';
    }

    protected function getCodeFieldName(): string
    {
        return 'order_number';
    }

    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make()
                    ->schema([
                        Select::make('company_id')
                            ->relationship(
                                name: 'company',
                                titleAttribute: 'name',
                                modifyQueryUsing: function ($query) {
                                    $user = auth()->user();
                                    if ($user) {
                                        $userCompanyIds = $user->companies()->pluck('companies.id');
                                        if ($userCompanyIds->isNotEmpty()) {
                                            $query->whereIn('companies.id', $userCompanyIds);
                                        } else {
                                            $query->whereRaw('1 = 0');
                                        }
                                    }
                                }
                            )
                            ->default(function () {
                                $selectedCompanyId = session('selected_company_id');
                                return $selectedCompanyId && $selectedCompanyId !== 'all'
                                    ? $selectedCompanyId
                                    : null;
                            })
                            ->hidden(function () {
                                $selectedCompanyId = session('selected_company_id');
                                return $selectedCompanyId && $selectedCompanyId !== 'all';
                            })
                            ->searchable()
                            ->preload()
                            ->nullable()
                            ->columnSpanFull(),
                        Select::make('customer_id')
                            ->label('Customer')
                            ->relationship(
                                name: 'customer',
                                titleAttribute: 'name',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $companyId = self::resolveCompanyId($get);
                                    if ($companyId) {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    return $query->where('is_customer', true)->orderBy('name');
                                }
                            )
                            ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->name} ({$record->contact_code})")
                            ->searchable(['name', 'contact_code'])
                            ->preload()
                            ->live(onBlur: true)
                            ->required()
                            ->createOptionForm([
                                TextInput::make('name')
                                    ->label('Name')
                                    ->required(),
                                (new \App\Filament\Resources\Contacts\Schemas\ContactForm)->getCodeField('contact_code', 'Contact Code')
                                    ->unique(\App\Models\Contact::class, 'contact_code', ignoreRecord: true,
                                        modifyRuleUsing: function ($rule) {
                                            $companyId = session('selected_company_id');
                                            if ($companyId && $companyId !== 'all') {
                                                $rule->where('company_id', $companyId);
                                            }
                                            return $rule;
                                        },
                                    ),
                                TextInput::make('email')
                                    ->label('Email')
                                    ->email(),
                                TextInput::make('phone')
                                    ->label('Phone')
                                    ->tel(),
                                Hidden::make('is_customer')
                                    ->default(true),
                                Hidden::make('company_id')
                                    ->default(function (callable $get) {
                                        $companyId = $get('company_id') ?: session('selected_company_id');
                                        return ($companyId && $companyId !== 'all') ? $companyId : null;
                                    }),
                                Hidden::make('created_by_user_id')
                                    ->default(function () {
                                        return auth()->id();
                                    }),
                            ])
                            ->createOptionUsing(function (array $data) {
                                $contact = \App\Models\Contact::create($data);
                                return $contact->id;
                            }),
                        DatePicker::make('date')
                            ->label('Order Date')
                            ->required()
                            ->default(now()),
                        Textarea::make('description')
                            ->label('Description')
                            ->rows(1)
                            ->maxLength(65535),
                        Select::make('status')
                            ->label('Status')
                            ->options([
                                'draft' => 'Draft',
                                'posted' => 'Posted',
                            ])
                            ->default('posted')
                            ->required()
                            ->native(false)
                            ->disabled(fn ($record) => $record && ($record->deliveryDocuments()->exists() || $record->salesInvoices()->exists()))
                            ->live(),
                        TextInput::make('reference_no')
                            ->maxLength(255)
                            ->label('Reference No.'),
                        (new static)->getCodeField('order_number', 'Order Number')
                            ->unique('sales_orders', 'order_number', ignoreRecord: true,
                                modifyRuleUsing: fn ($rule) => $rule->where(function ($query) {
                                    $companyId = session('selected_company_id');
                                    if ($companyId && $companyId !== 'all') {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    $query->whereNull('deleted_at');
                                    return $query;
                                })
                            ),
                        Hidden::make('subtotal'),
                        Hidden::make('discount'),
                        Hidden::make('tax_amount'),
                        Hidden::make('total_amount'),
                    ])
                    ->columns(3)
                    ->columnSpanFull(),

                Repeater::make('items')
                    ->relationship()
                    ->hiddenLabel()
                    ->addActionLabel('Add Item')
                    ->required()
                    ->table([
                        TableColumn::make('Product')->width('20%')->alignment(Alignment::Start),
                        TableColumn::make('Quantity')->width('10%')->alignment(Alignment::End),
                        TableColumn::make('Unit Price')->width('15%')->alignment(Alignment::End),
                        TableColumn::make('Tax')->width('10%')->alignment(Alignment::Start),
                        TableColumn::make('Unit')->width('10%')->alignment(Alignment::Start),
                        TableColumn::make('Description')->width('20%')->alignment(Alignment::Start),
                        TableColumn::make('Total')->width('15%')->alignment(Alignment::End),
                    ])
                    ->schema([
                        Select::make('product_id')
                            ->required()
                            ->searchable()
                            ->label('Product')
                            ->relationship(
                                name: 'product',
                                titleAttribute: 'name',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $companyId = self::resolveCompanyId($get);
                                    if ($companyId) {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    return $query->orderBy('name');
                                }
                            )
                            ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->name} ({$record->code})")
                            ->searchable(['name', 'code'])
                            ->preload()
                            ->live()
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                $product = \App\Models\Product::find($state);
                                if ($product) {
                                    if ($product->selling_price) {
                                        $set('unit_price', $product->selling_price);
                                        $set('unit_price_display', NumberInput::formatRoundedIntegerDisplay($product->selling_price));
                                    }
                                    if ($product->unit_id) {
                                        $set('unit_id', $product->unit_id);
                                        $set('conversion_factor', 1);
                                        $set('base_quantity', NumberInput::parseToFloat($get('quantity') ?? 0));
                                    }
                                    if ($product->description) {
                                        $set('description', $product->description);
                                    }
                                    if ($product->tax_id) {
                                        $set('tax_id', $product->tax_id);
                                    } else {
                                        $selectedCompanyId = $get('company_id');
                                        if (!$selectedCompanyId || $selectedCompanyId === 'all') {
                                            $selectedCompanyId = $product->company_id ?: (session('selected_company_id') && session('selected_company_id') !== 'all' ? session('selected_company_id') : null);
                                        }
                                        if ($selectedCompanyId) {
                                            $companyTaxId = \App\Models\Company::where('id', $selectedCompanyId)->value('tax_id');
                                            if ($companyTaxId) {
                                                $set('tax_id', $companyTaxId);
                                            }
                                        }
                                    }
                                }
                            })
                            ->createOptionForm([
                                TextInput::make('name')
                                    ->label('Name')
                                    ->required(),
                                (new \App\Filament\Resources\Products\Schemas\ProductForm)->getCodeField('code', 'Product Code')
                                    ->unique(
                                        \App\Models\Product::class,
                                        'code',
                                        ignoreRecord: true,
                                        modifyRuleUsing: function ($rule) {
                                            $companyId = session('selected_company_id');
                                            if ($companyId && $companyId !== 'all') {
                                                $rule->where('company_id', $companyId);
                                            }
                                            return $rule;
                                        },
                                    ),
                                Select::make('product_group_id')
                                    ->label('Product Group')
                                    ->relationship(
                                        "productGroup",
                                        "name",
                                        modifyQueryUsing: function ($query) {
                                            $selectedCompanyId = session('selected_company_id');
                                            if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                                                $query->where('company_id', $selectedCompanyId);
                                            }
                                            return $query;
                                        }
                                    )
                                    ->searchable()
                                    ->preload()
                                    ->required(),
                                ...RoundedIntegerMoneyInput::schema(
                                    name: 'selling_price',
                                    label: 'Selling Price',
                                    required: false,
                                    defaultDecimal: '0.00',
                                ),
                                Select::make('unit_id')
                                    ->label('Unit')
                                    ->searchable()
                                    ->options(function () {
                                        $selectedCompanyId = session('selected_company_id');
                                        $q = \App\Models\Unit::query();
                                        if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                                            $q->where('company_id', $selectedCompanyId);
                                        } else {
                                            $q->whereNull('company_id');
                                        }
                                        return $q->orderBy('name')->pluck('name', 'id')->toArray();
                                    }),
                                Textarea::make('description')
                                    ->label('Description')
                                    ->rows(2),
                                Hidden::make('company_id')
                                    ->default(function () {
                                        $selectedCompanyId = session('selected_company_id');
                                        return ($selectedCompanyId && $selectedCompanyId !== 'all') ? $selectedCompanyId : null;
                                    }),
                                Hidden::make('created_by_user_id')
                                    ->default(function () {
                                        return auth()->id();
                                    }),
                            ])
                            ->createOptionUsing(function (array $data) {
                                $product = \App\Models\Product::create($data);
                                return $product->id;
                            }),
                        ...RoundedIntegerMoneyInput::schema(
                            name: 'quantity',
                            label: 'Quantity',
                            required: true,
                            defaultDecimal: '1.00',
                            afterUpdated: function ($decimal, callable $set, callable $get) {
                                $quantity = NumberInput::parseToFloat($decimal);
                                $unitPrice = NumberInput::parseToFloat($get('unit_price') ?? 0);

                                if ($quantity > 999999999 || $unitPrice > 999999999) {
                                    $quantity = min($quantity, 999999999);
                                    $unitPrice = min($unitPrice, 999999999);
                                }

                                $itemTotal = $quantity * $unitPrice;

                                if ($itemTotal > 999999999999.99) {
                                    $itemTotal = 999999999999.99;
                                }

                                $set('total', $itemTotal);

                                $conversionFactor = (float) ($get('conversion_factor') ?? 1);
                                $set('base_quantity', $quantity * $conversionFactor);

                                $c = self::calculateTotals($get);
                                $set('subtotal', $c['subtotal']);
                                $set('discount', $c['discount']);
                                $set('tax_amount', $c['tax']);
                                $set('total_amount', $c['total']);
                            },
                        ),
                        ...RoundedIntegerMoneyInput::schema(
                            name: 'unit_price',
                            label: 'Unit Price',
                            required: true,
                            afterUpdated: function ($decimal, callable $set, callable $get) {
                                $quantity = NumberInput::parseToFloat($get('quantity') ?? 0);
                                $unitPrice = NumberInput::parseToFloat($decimal);

                                if ($quantity > 999999999 || $unitPrice > 999999999) {
                                    $quantity = min($quantity, 999999999);
                                    $unitPrice = min($unitPrice, 999999999);
                                }

                                $itemTotal = $quantity * $unitPrice;

                                if ($itemTotal > 999999999999.99) {
                                    $itemTotal = 999999999999.99;
                                }

                                $set('total', $itemTotal);

                                $c = self::calculateTotals($get);
                                $set('subtotal', $c['subtotal']);
                                $set('discount', $c['discount']);
                                $set('tax_amount', $c['tax']);
                                $set('total_amount', $c['total']);
                            },
                        ),
                        Select::make('tax_id')
                            ->searchable()
                            ->label('Tax')
                            ->relationship(
                                'tax',
                                'name',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $companyId = self::resolveCompanyId($get);
                                    if ($companyId) {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    return $query->orderBy('name');
                                }
                            )
                            ->getOptionLabelFromRecordUsing(fn ($record) => $record->name)
                            ->preload()
                            ->live(onBlur: true)
                            ->required()
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                $c = self::calculateTotals($get);
                                $set('subtotal', $c['subtotal']);
                                $set('discount', $c['discount']);
                                $set('tax_amount', $c['tax']);
                                $set('total_amount', $c['total']);
                            }),
                        Select::make('unit_id')
                            ->searchable()
                            ->label('Unit')
                            ->options(function (callable $get) {
                                $productId = $get('product_id');
                                if (!$productId) {
                                    return [];
                                }
                                $product = \App\Models\Product::find($productId);
                                if (!$product) {
                                    return [];
                                }
                                return app(\App\Services\UnitConversionService::class)->getUnitOptions($product, 'sales');
                            })
                            ->live()
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                $productId = $get('product_id');
                                $quantity = NumberInput::parseToFloat($get('quantity') ?? 0);
                                if ($productId && $state) {
                                    $product = \App\Models\Product::find($productId);
                                    if ($product) {
                                        $service = app(\App\Services\UnitConversionService::class);
                                        $factor = $service->getConversionFactor($product, (int) $state);
                                        $set('conversion_factor', $factor);
                                        $set('base_quantity', $quantity * $factor);

                                        // Update unit price based on conversion factor
                                        $basePrice = (float) ($product->selling_price ?? 0);
                                        $newPrice = $basePrice * $factor;
                                        $set('unit_price', $newPrice);
                                        $set('unit_price_display', NumberInput::formatRoundedIntegerDisplay($newPrice));

                                        // Recalculate item total and document totals
                                        $itemTotal = $quantity * $newPrice;
                                        $set('total', $itemTotal);

                                        $c = self::calculateTotals($get);
                                        $set('subtotal', $c['subtotal']);
                                        $set('discount', $c['discount']);
                                        $set('tax_amount', $c['tax']);
                                        $set('total_amount', $c['total']);
                                    }
                                }
                            }),

                        Textarea::make('description')
                            ->label('Description')
                            ->rows(1),
                        Hidden::make('base_quantity')
                            ->default(0),
                        Hidden::make('conversion_factor')
                            ->default(1),
                        Hidden::make('total')
                            ->default(0)
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                $quantity = NumberInput::parseToFloat($get('quantity') ?? 0);
                                $unitPrice = NumberInput::parseToFloat($get('unit_price') ?? 0);
                                $total = $quantity * $unitPrice;
                                $set('total', $total);
                            }),
                        Placeholder::make('total_display')
                            ->label('Total')
                            ->content(function ($get) {
                                $quantity = NumberInput::parseToFloat($get('quantity') ?? 0);
                                $unitPrice = NumberInput::parseToFloat($get('unit_price') ?? 0);
                                $total = $quantity * $unitPrice;
                                return number_format($total, 0, ',', '.');
                            })
                            ->extraAttributes([
                                'class' => 'font-semibold text-green-600 py-2 px-3 bg-gray-50 rounded-md border border-gray-200'
                            ]),
                    ])
                    ->defaultItems(0)
                    ->reorderable()
                    ->collapsible()
                    ->compact()
                    ->columnSpan('full'),

                Section::make()
                    ->schema([
                        Placeholder::make('empty_col_1')
                            ->hiddenLabel()
                            ->columnSpan(1),
                        Placeholder::make('subtotal_display')
                            ->inlineLabel()
                            ->label('Subtotal')
                            ->content(function (callable $get) {
                                $c = self::calculateTotals($get);
                                return 'Rp ' . number_format($c['subtotal'], 0, ',', '.');
                            })
                            ->extraAttributes(['style' => 'text-align:right'])
                            ->columnSpan(1),
                        Placeholder::make('empty_col_2')
                            ->hiddenLabel()
                            ->columnSpan(1),
                        ...RoundedIntegerMoneyInput::schema(
                            name: 'other_charges',
                            label: 'Other Charges',
                            inlineLabel: true,
                            defaultDecimal: '0.00',
                            columnSpan: 1,
                            afterUpdated: function ($decimal, callable $set, callable $get) {
                                $c = self::calculateTotals($get);
                                $set('subtotal', $c['subtotal']);
                                $set('discount', $c['discount']);
                                $set('tax_amount', $c['tax']);
                                $set('total_amount', $c['total']);
                            },
                        ),
                        Placeholder::make('empty_col_3')
                            ->hiddenLabel()
                            ->columnSpan(1),
                        TextInput::make('discount_percentage')
                            ->default(0)
                            ->numeric()
                            ->suffix('%')
                            ->inlineLabel()
                            ->label('Discount')
                            ->extraInputAttributes(['style' => 'text-align:right'])
                            ->live(onBlur: true)
                            ->afterStateHydrated(function ($component, $state, $record) {
                                if ($record && $record->discount_percentage !== null) {
                                    $component->state((float) $record->discount_percentage);
                                    return;
                                }

                                if ($record && $record->subtotal > 0 && $record->discount > 0) {
                                    $discountPercentage = ($record->discount / $record->subtotal) * 100;
                                    $component->state($discountPercentage);
                                    return;
                                }

                                $component->state(0);
                            })
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                $c = self::calculateTotals($get);
                                $set('subtotal', $c['subtotal']);
                                $set('discount', $c['discount']);
                                $set('tax_amount', $c['tax']);
                                $set('total_amount', $c['total']);
                            })
                            ->columnSpan(1),
                        Placeholder::make('empty_col_4')
                            ->hiddenLabel()
                            ->columnSpan(1),
                        Placeholder::make('discount_amount_display')
                            ->inlineLabel()
                            ->label('Discount Amount')
                            ->content(function (callable $get) {
                                $c = self::calculateTotals($get);
                                return 'Rp ' . number_format($c['discount'], 0, ',', '.');
                            })
                            ->extraAttributes(['style' => 'text-align:right'])
                            ->columnSpan(1),
                        Placeholder::make('empty_col_5')
                            ->hiddenLabel()
                            ->columnSpan(1),
                        Placeholder::make('tax_display')
                            ->inlineLabel()
                            ->label('Tax')
                            ->content(function (callable $get) {
                                $c = self::calculateTotals($get);
                                return 'Rp ' . number_format($c['tax'], 0, ',', '.');
                            })
                            ->extraAttributes(['style' => 'text-align:right'])
                            ->columnSpan(1),
                        Placeholder::make('empty_col_6')
                            ->hiddenLabel()
                            ->columnSpan(1),
                        Placeholder::make('total_display_footer')
                            ->inlineLabel()
                            ->label('Total')
                            ->content(function (callable $get) {
                                $c = self::calculateTotals($get);
                                return 'Rp ' . number_format($c['total'], 0, ',', '.');
                            })
                            ->extraAttributes(['style' => 'text-align:right', 'class' => 'font-bold text-lg text-green-600'])
                            ->columnSpan(1),
                    ])
                    ->columns(2)
                    ->columnSpanFull(),

            ]);
    }
}
