<?php

namespace App\Filament\Resources\SalesOrders\Schemas;

use App\Filament\Forms\Components\NumberInput;
use App\Filament\Forms\Components\RoundedIntegerMoneyInput;
use App\Forms\Components\SelectWithModal;
use App\Traits\HasAutoGeneratedCode;
use Filament\Actions\Action;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\Placeholder;
use Filament\Forms\Components\Repeater;
use Filament\Forms\Components\Repeater\TableColumn;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Filament\Support\Enums\Alignment;
use Filament\Forms\Components\Hidden;


class SalesOrderForm
{
    use HasAutoGeneratedCode;

    protected static function calculateTotals(callable $get): array
    {
        $items = $get('items') ?? [];
        $discountPercentage = (float) ($get('discount_percentage') ?? 0);
        $otherCharges = NumberInput::parseToFloat($get('other_charges') ?? 0);
        $subtotal = 0.0;
        $taxTotal = 0.0;
        foreach ($items as $item) {
            $qty = NumberInput::parseToFloat($item['quantity'] ?? 0);
            $price = NumberInput::parseToFloat($item['unit_price'] ?? 0);
            $line = $qty * $price;
            $subtotal += $line;
            $taxId = $item['tax_id'] ?? null;
            if ($taxId) {
                $tax = \App\Models\Tax::find($taxId);
                if ($tax && $tax->tax_percentage) {
                    $lineDiscount = $line * ($discountPercentage / 100);
                    $taxBase = $line - $lineDiscount;
                    $taxTotal += $taxBase * ((float) $tax->tax_percentage) / 100;
                }
            }
        }
        $discountAmount = $subtotal * ($discountPercentage / 100);
        $total = $subtotal - $discountAmount + $otherCharges + $taxTotal;
        return [
            'subtotal' => $subtotal,
            'discount' => $discountAmount,
            'tax' => $taxTotal,
            'total' => $total,
        ];
    }

    protected static function resolveCompanyId(callable $get): ?int
    {
        $companyId = $get('company_id');
        if ($companyId && $companyId !== 'all') {
            return (int) $companyId;
        }
        $selectedCompanyId = session('selected_company_id');
        if ($selectedCompanyId && $selectedCompanyId !== 'all') {
            return (int) $selectedCompanyId;
        }
        return null;
    }

    /**
     * Get the document type for sales orders
     */
    protected function getDocumentType(): string
    {
        return 'sales_order';
    }

    /**
     * Get the code field name for sales orders
     */
    protected function getCodeFieldName(): string
    {
        return 'order_number';
    }
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make()
                    ->schema([
                        Select::make('company_id')
                            ->relationship(
                                name: 'company',
                                titleAttribute: 'name',
                                modifyQueryUsing: function ($query) {
                                    $user = auth()->user();
                                    if ($user) {
                                        $userCompanyIds = $user->companies()->pluck('companies.id');
                                        if ($userCompanyIds->isNotEmpty()) {
                                            $query->whereIn('companies.id', $userCompanyIds);
                                        } else {
                                            // If user has no assigned companies, return no results
                                            $query->whereRaw('1 = 0');
                                        }
                                    }
                                }
                            )
                            ->default(function () {
                                $selectedCompanyId = session('selected_company_id');
                                return $selectedCompanyId && $selectedCompanyId !== 'all'
                                    ? $selectedCompanyId
                                    : null;
                            })
                            ->hidden(function () {
                                $selectedCompanyId = session('selected_company_id');
                                return $selectedCompanyId && $selectedCompanyId !== 'all';
                            })
                            ->searchable()
                            ->preload()
                            ->nullable()
                            ->columnSpanFull(),
                        Select::make('customer_id')
                            ->label('Pelanggan')
                            ->relationship(
                                name: 'customer',
                                titleAttribute: 'name',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $companyId = self::resolveCompanyId($get);
                                    if ($companyId) {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    return $query->where('is_customer', true)->orderBy('name');
                                }
                            )
                            ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->name} ({$record->contact_code})")
                            ->searchable(['name', 'contact_code'])
                            ->preload()
                            ->live(onBlur: true)
                            ->required()
                            ->createOptionForm([
                                TextInput::make('name')
                                    ->label('Nama')
                                    ->required(),
                                (new \App\Filament\Resources\Contacts\Schemas\ContactForm)->getCodeField('contact_code', 'Kode Kontak')
                                    ->unique(\App\Models\Contact::class, 'contact_code', ignoreRecord: true,
                                        modifyRuleUsing: function ($rule) {
                                            // Get the company_id from the session
                                            $companyId = session('selected_company_id');

                                            // If there's a selected company, scope the uniqueness check to that company
                                            if ($companyId && $companyId !== 'all') {
                                                $rule->where('company_id', $companyId);
                                            }
                                            // If no company is selected, the uniqueness check will apply to all records
                                            // This ensures records are unique within their company
                                            return $rule;
                                        },
                                    ),
                                TextInput::make('email')
                                    ->label('Email')
                                    ->email(),
                                TextInput::make('phone')
                                    ->label('Telepon')
                                    ->tel(),
                                Hidden::make('is_customer')
                                    ->default(true),
                                Hidden::make('company_id')
                                    ->default(function (callable $get) {
                                        $companyId = $get('company_id') ?: session('selected_company_id');
                                        return ($companyId && $companyId !== 'all') ? $companyId : null;
                                    }),
                                Hidden::make('created_by_user_id')
                                    ->default(function () {
                                        return auth()->id();
                                    }),
                            ])
                            ->createOptionUsing(function (array $data) {
                                $contact = \App\Models\Contact::create($data);
                                return $contact->id;
                            }),
                        TextInput::make('jb_job_number')
                            ->label('Nomor Job JB')
                            ->maxLength(100)
                            ->placeholder('Masukkan nomor job JB'),
                        TextInput::make('client_po_number')
                            ->label('Nomor PO Pelanggan')
                            ->maxLength(100)
                            ->placeholder('Masukkan nomor PO pelanggan'),
                        DatePicker::make('date')
                            ->label('Tanggal Pesanan')
                            ->required()
                            ->default(now()),
                        Textarea::make('description')
                            ->label('Description')
                            ->rows(1)
                            ->maxLength(65535),
                        Select::make('status')
                            ->label('Status')
                            ->options([
                                'draft' => 'Draft',
                                'posted' => 'Posted',
                            ])
                            ->default('posted')
                            ->required()
                            ->native(false)
                            ->disabled(fn ($record) => $record && ($record->deliveryDocuments()->exists() || $record->salesInvoices()->exists()))
                            ->live(),
                        TextInput::make('job_number')
                            ->label('Nomor Pekerjaan')
                            ->maxLength(50)
                            ->placeholder('Masukkan nomor pekerjaan')
                            ->disabled(fn ($record) => $record !== null),
                        Select::make('order_type')
                            ->label('Tipe Pesanan')
                            ->options([
                                'deposit' => 'Deposit',
                                'standar' => 'Standar',
                                'aktual' => 'Aktual',
                            ])
                            ->default('standar')
                            ->live()
                            ->required(),
                        Select::make('job_id')
                            ->label('Proyek/Pekerjaan')
                            ->hidden()
                            ->relationship(
                                name: 'job',
                                titleAttribute: 'title',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $customerId = $get('customer_id');
                                    $companyId = self::resolveCompanyId($get);

                                    if ($customerId) {
                                        $query->where('customer_id', $customerId);
                                    }
                                    if ($companyId) {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    return $query->orderBy('job_number');
                                }
                            )
                            ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->job_number} - {$record->title}")
                            ->searchable(['title', 'job_number'])
                            ->preload()
                            ->createOptionForm([
                                TextInput::make('job_number')
                                    ->label('Nomor Pekerjaan')
                                    ->default(function (callable $get) {
                                        $selectedCompanyId = $get('company_id') ?: session('selected_company_id');
                                        $companyId = ($selectedCompanyId && $selectedCompanyId !== 'all') ? $selectedCompanyId : null;
                                        $service = app(\App\Services\CodeGeneratorService::class);
                                        return $service->generateCodeManual('project', $companyId);
                                    })
                                    ->unique('projects', 'job_number', ignoreRecord: true,
                                        modifyRuleUsing: fn ($rule) => $rule->where(function ($query) {
                                            $companyId = session('selected_company_id');
                                            if ($companyId && $companyId !== 'all') {
                                                $query->where('company_id', $companyId);
                                            } else {
                                                $query->whereNull('company_id');
                                            }
                                            return $query;
                                        })
                                    )
                                    ->required()
                                    ->maxLength(50),
                                TextInput::make('title')
                                    ->label('Judul Proyek')
                                    ->required()
                                    ->maxLength(255),
                                TextInput::make('customer_po_number')
                                    ->label('Nomor PO Pelanggan')
                                    ->maxLength(255),

                                Hidden::make('company_id')
                                    ->default(function () {
                                        $selectedCompanyId = session('selected_company_id');
                                        return ($selectedCompanyId && $selectedCompanyId !== 'all') ? $selectedCompanyId : null;
                                    }),
                                Hidden::make('created_by_user_id')
                                    ->default(function () {
                                        return auth()->id();
                                    }),
                            ])
                            ->createOptionUsing(function (array $data, callable $get) {
                                // Add customer_id from parent form
                                $data['customer_id'] = $get('customer_id');

                                // Get company ID for code generation
                                $selectedCompanyId = $get('company_id') ?: session('selected_company_id');
                                $companyId = ($selectedCompanyId && $selectedCompanyId !== 'all') ? $selectedCompanyId : null;

                                // Generate proper job number with company awareness
                                $service = app(\App\Services\CodeGeneratorService::class);
                                $data['job_number'] = $service->generateCode('project', $companyId);

                                // Set company_id in project data
                                $data['company_id'] = $companyId;

                                $project = \App\Models\Project::create($data);
                                return $project->id;
                            }),
                        Select::make('related_order_id')
                            ->label('Pilih Deposit')
                            ->options(function (callable $get) {
                                $companyId = $get('company_id') ?: session('selected_company_id');
                                $customerId = $get('customer_id');

                                $query = \App\Models\SalesOrder::query()
                                    ->where('order_type', 'deposit');

                                if ($companyId && $companyId !== 'all') {
                                    $query->where('company_id', $companyId);
                                } else {
                                    $query->whereNull('company_id');
                                }

                                if ($customerId) {
                                    $query->where('customer_id', $customerId);
                                }

                                return $query->limit(50)->pluck('order_number', 'id');
                            })
                            ->searchable()
                            ->preload()
                            ->visible(function (callable $get) {
                                return $get('order_type') === 'aktual';
                            })
                            ->helperText('Pilih deposit yang terkait'),
                        TextInput::make('reference_no')
                            ->maxLength(255)
                            ->label('Nomor Referensi'),
                        (new static)->getCodeField('order_number', 'Nomor Pesanan')
                            ->unique('sales_orders', 'order_number', ignoreRecord: true,
                                modifyRuleUsing: fn ($rule) => $rule->where(function ($query) {
                                    $companyId = session('selected_company_id');
                                    if ($companyId && $companyId !== 'all') {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    $query->whereNull('deleted_at');
                                    return $query;
                                })
                            ),
                        Hidden::make('subtotal'),
                        Hidden::make('discount'),
                        Hidden::make('tax_amount'),
                        Hidden::make('total_amount'),
                    ])
                    ->columns(3)
                    ->columnSpanFull(),

                // First-party Filament TableRepeater for comparison
                Repeater::make('items')
                    ->relationship()
                    ->hiddenLabel()
                    ->addActionLabel('Tambah Item Baru')
                    ->required()
                    ->table([
                        TableColumn::make('Produk')->width('15%')->alignment(Alignment::Start),
                        TableColumn::make('Nama Barang')->width('15%')->alignment(Alignment::Start),
                        TableColumn::make('Jumlah')->width('8%')->alignment(Alignment::End),
                        TableColumn::make('Harga Satuan')->width('12%')->alignment(Alignment::End),
                        TableColumn::make('Pajak')->width('9%')->alignment(Alignment::Start),
                        TableColumn::make('Satuan')->width('8%')->alignment(Alignment::Start),
                        TableColumn::make('Produksi')->width('7%')->alignment(Alignment::Center),
                        TableColumn::make('Deskripsi')->width('16%')->alignment(Alignment::Start),
                        TableColumn::make('Total')->width('10%')->alignment(Alignment::End),
                    ])
                    ->schema([
                        Select::make('product_id')
                            ->required()
                            ->searchable()
                            ->label('Produk')
                            ->relationship(
                                name: 'product',
                                titleAttribute: 'name',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $companyId = self::resolveCompanyId($get);
                                    if ($companyId) {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    return $query->orderBy('name');
                                }
                            )
                            ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->name} ({$record->code})")
                            ->searchable(['name', 'code'])
                            ->preload()
                            ->live()
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                $product = \App\Models\Product::find($state);
                                if ($product) {
                                    // Auto-fill item_name from product name
                                    $set('item_name', $product->name);
                                    if ($product->selling_price) {
                                        $set('unit_price', $product->selling_price);
                                        $set('unit_price_display', NumberInput::formatRoundedIntegerDisplay($product->selling_price));
                                    }
                                    if ($product->unit_id) {
                                        $set('unit_id', $product->unit_id);
                                    }
                                    if ($product->description) {
                                        $set('description', $product->description);
                                    }
                                    // Set tax from product if available, otherwise fall back to company tax
                                    if ($product->tax_id) {
                                        $set('tax_id', $product->tax_id);
                                    } else {
                                        $selectedCompanyId = $get('company_id');
                                        if (!$selectedCompanyId || $selectedCompanyId === 'all') {
                                            $selectedCompanyId = $product->company_id ?: (session('selected_company_id') && session('selected_company_id') !== 'all' ? session('selected_company_id') : null);
                                        }
                                        if ($selectedCompanyId) {
                                            $companyTaxId = \App\Models\Company::where('id', $selectedCompanyId)->value('tax_id');
                                            if ($companyTaxId) {
                                                $set('tax_id', $companyTaxId);
                                            }
                                        }
                                    }
                                }
                            })
                            ->createOptionForm([
                                TextInput::make('name')
                                    ->label('Nama')
                                    ->required(),
                                (new \App\Filament\Resources\Products\Schemas\ProductForm)->getCodeField('code', 'Kode Produk')
                                    ->unique(
                                        \App\Models\Product::class,
                                        'code',
                                        ignoreRecord: true,
                                        modifyRuleUsing: function ($rule) {
                                            // Get the company_id from the session
                                            $companyId = session('selected_company_id');

                                            // If there's a selected company, scope the uniqueness check to that company
                                            if ($companyId && $companyId !== 'all') {
                                                $rule->where('company_id', $companyId);
                                            }
                                            // If no company is selected, the uniqueness check will apply to all records
                                            // This ensures records are unique within their company
                                            return $rule;
                                        },
                                    ),
                                Select::make('product_group_id')
                                    ->label('Kelompok Produk')
                                    ->relationship(
                                        "productGroup",
                                        "name",
                                        modifyQueryUsing: function ($query) {
                                            $selectedCompanyId = session('selected_company_id');
                                            if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                                                $query->where('company_id', $selectedCompanyId);
                                            }
                                            return $query;
                                        }
                                    )
                                    ->searchable()
                                    ->preload()
                                    ->required(),
                                ...RoundedIntegerMoneyInput::schema(
                                    name: 'selling_price',
                                    label: 'Harga Jual',
                                    required: false,
                                    defaultDecimal: '0.00',
                                ),
                                Select::make('unit_id')
                                    ->label('Satuan')
                                    ->searchable()
                                    ->options(function () {
                                        $selectedCompanyId = session('selected_company_id');
                                        $q = \App\Models\Unit::query();
                                        if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                                            $q->where('company_id', $selectedCompanyId);
                                        } else {
                                            $q->whereNull('company_id');
                                        }
                                        return $q->orderBy('name')->pluck('name', 'id')->toArray();
                                    }),
                                Textarea::make('description')
                                    ->label('Deskripsi')
                                    ->rows(2),
                                Hidden::make('company_id')
                                    ->default(function () {
                                        $selectedCompanyId = session('selected_company_id');
                                        return ($selectedCompanyId && $selectedCompanyId !== 'all') ? $selectedCompanyId : null;
                                    }),
                                Hidden::make('created_by_user_id')
                                    ->default(function () {
                                        return auth()->id();
                                    }),
                            ])
                            ->createOptionUsing(function (array $data) {
                                $product = \App\Models\Product::create($data);
                                return $product->id;
                            }),
                        TextInput::make('item_name')
                            ->label('Nama Barang')
                            ->required()
                            ->maxLength(255),
                        ...RoundedIntegerMoneyInput::schema(
                            name: 'quantity',
                            label: 'Jumlah',
                            required: true,
                            defaultDecimal: '1.00',
                            afterUpdated: function ($decimal, callable $set, callable $get) {
                                $quantity = NumberInput::parseToFloat($decimal);
                                $unitPrice = NumberInput::parseToFloat($get('unit_price') ?? 0);

                                if ($quantity > 999999999 || $unitPrice > 999999999) {
                                    $quantity = min($quantity, 999999999);
                                    $unitPrice = min($unitPrice, 999999999);
                                }

                                $itemTotal = $quantity * $unitPrice;

                                if ($itemTotal > 999999999999.99) {
                                    $itemTotal = 999999999999.99;
                                }

                                $set('total', $itemTotal);

                                $c = self::calculateTotals($get);
                                $set('subtotal', $c['subtotal']);
                                $set('discount', $c['discount']);
                                $set('tax_amount', $c['tax']);
                                $set('total_amount', $c['total']);
                            },
                        ),
                        ...RoundedIntegerMoneyInput::schema(
                            name: 'unit_price',
                            label: 'Harga Satuan',
                            required: true,
                            afterUpdated: function ($decimal, callable $set, callable $get) {
                                $quantity = NumberInput::parseToFloat($get('quantity') ?? 0);
                                $unitPrice = NumberInput::parseToFloat($decimal);

                                if ($quantity > 999999999 || $unitPrice > 999999999) {
                                    $quantity = min($quantity, 999999999);
                                    $unitPrice = min($unitPrice, 999999999);
                                }

                                $itemTotal = $quantity * $unitPrice;

                                if ($itemTotal > 999999999999.99) {
                                    $itemTotal = 999999999999.99;
                                }

                                $set('total', $itemTotal);

                                $c = self::calculateTotals($get);
                                $set('subtotal', $c['subtotal']);
                                $set('discount', $c['discount']);
                                $set('tax_amount', $c['tax']);
                                $set('total_amount', $c['total']);
                            },
                        ),
                        Select::make('tax_id')
                            ->searchable()
                            ->label('Pajak')
                            ->relationship(
                                'tax',
                                'name',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $companyId = self::resolveCompanyId($get);
                                    if ($companyId) {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    return $query->orderBy('name');
                                }
                            )
                            ->getOptionLabelFromRecordUsing(fn ($record) => $record->name)
                            ->preload()
                            ->live(onBlur: true)
                            ->required()
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                $c = self::calculateTotals($get);
                                $set('subtotal', $c['subtotal']);
                                $set('discount', $c['discount']);
                                $set('tax_amount', $c['tax']);
                                $set('total_amount', $c['total']);
                            }),
                        Select::make('unit_id')
                            ->searchable()
                            ->label('Satuan')
                            ->relationship(
                                name: 'unit',
                                titleAttribute: 'name',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $companyId = self::resolveCompanyId($get);
                                    if ($companyId) {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    return $query->orderBy('name');
                                }
                            )
                            ->preload()
                            ->getOptionLabelFromRecordUsing(fn ($record) => $record->name),

                        Toggle::make('is_production')
                            ->label('Produksi')
                            ->default(false),
                        Textarea::make('description')
                            ->label('Deskripsi')
                            ->rows(1),
                        Hidden::make('total')
                            ->default(0)
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                $quantity = NumberInput::parseToFloat($get('quantity') ?? 0);
                                $unitPrice = NumberInput::parseToFloat($get('unit_price') ?? 0);
                                $total = $quantity * $unitPrice;
                                $set('total', $total);
                            }),
                        Placeholder::make('total_display')
                            ->label('Total')
                            ->content(function ($get) {
                                $quantity = NumberInput::parseToFloat($get('quantity') ?? 0);
                                $unitPrice = NumberInput::parseToFloat($get('unit_price') ?? 0);
                                $total = $quantity * $unitPrice;
                                return number_format($total, 0, ',', '.');
                            })
                            ->extraAttributes([
                                'class' => 'font-semibold text-green-600 py-2 px-3 bg-gray-50 rounded-md border border-gray-200'
                            ]),
                    ])
                    ->defaultItems(0)
                    ->reorderable()
                    ->collapsible()
                    ->compact()
                    ->columnSpan('full'),

                Section::make()
                    ->schema([
                        Placeholder::make('empty_col_1')
                            ->hiddenLabel()
                            ->columnSpan(1),
                        Placeholder::make('subtotal_display')
                            ->inlineLabel()
                            ->label('Subtotal')
                            ->content(function (callable $get) {
                                $c = self::calculateTotals($get);
                                return 'Rp ' . number_format($c['subtotal'], 0, ',', '.');
                            })
                            ->extraAttributes(['style' => 'text-align:right'])
                            ->columnSpan(1),
                        Placeholder::make('empty_col_2')
                            ->hiddenLabel()
                            ->columnSpan(1),
                        ...RoundedIntegerMoneyInput::schema(
                            name: 'other_charges',
                            label: 'Biaya Lainnya',
                            inlineLabel: true,
                            defaultDecimal: '0.00',
                            columnSpan: 1,
                            afterUpdated: function ($decimal, callable $set, callable $get) {
                                $c = self::calculateTotals($get);
                                $set('subtotal', $c['subtotal']);
                                $set('discount', $c['discount']);
                                $set('tax_amount', $c['tax']);
                                $set('total_amount', $c['total']);
                            },
                        ),
                        Placeholder::make('empty_col_3')
                            ->hiddenLabel()
                            ->columnSpan(1),
                        TextInput::make('discount_percentage')
                            ->default(0)
                            ->numeric()
                            ->suffix('%')
                            ->inlineLabel()
                            ->label('Diskon')
                            ->extraInputAttributes(['style' => 'text-align:right'])
                            ->live(onBlur: true)
                            ->afterStateHydrated(function ($component, $state, $record) {
                                if ($record && $record->discount_percentage !== null) {
                                    $component->state((float) $record->discount_percentage);
                                    return;
                                }

                                if ($record && $record->subtotal > 0 && $record->discount > 0) {
                                    $discountPercentage = ($record->discount / $record->subtotal) * 100;
                                    $component->state($discountPercentage);
                                    return;
                                }

                                $component->state(0);
                            })
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                $c = self::calculateTotals($get);
                                $set('subtotal', $c['subtotal']);
                                $set('discount', $c['discount']);
                                $set('tax_amount', $c['tax']);
                                $set('total_amount', $c['total']);
                            })
                            ->columnSpan(1),
                        Placeholder::make('empty_col_4')
                            ->hiddenLabel()
                            ->columnSpan(1),
                        Placeholder::make('discount_amount_display')
                            ->inlineLabel()
                            ->label('Jumlah Diskon')
                            ->content(function (callable $get) {
                                $c = self::calculateTotals($get);
                                return 'Rp ' . number_format($c['discount'], 0, ',', '.');
                            })
                            ->extraAttributes(['style' => 'text-align:right'])
                            ->columnSpan(1),
                        Placeholder::make('empty_col_5')
                            ->hiddenLabel()
                            ->columnSpan(1),
                        Placeholder::make('tax_display')
                            ->inlineLabel()
                            ->label('Pajak')
                            ->content(function (callable $get) {
                                $c = self::calculateTotals($get);
                                return 'Rp ' . number_format($c['tax'], 0, ',', '.');
                            })
                            ->extraAttributes(['style' => 'text-align:right'])
                            ->columnSpan(1),
                        Placeholder::make('empty_col_6')
                            ->hiddenLabel()
                            ->columnSpan(1),
                        Placeholder::make('total_display_footer')
                            ->inlineLabel()
                            ->label('Total')
                            ->content(function (callable $get) {
                                $c = self::calculateTotals($get);
                                return 'Rp ' . number_format($c['total'], 0, ',', '.');
                            })
                            ->extraAttributes(['style' => 'text-align:right', 'class' => 'font-bold text-lg text-green-600'])
                            ->columnSpan(1),
                    ])
                    ->columns(2)
                    ->columnSpanFull(),

            ]);
    }
}
