<?php

namespace App\Filament\Resources\SalesDeliveries\Schemas;

use App\Filament\Forms\Components\NumberInput;
use App\Filament\Forms\Components\RoundedIntegerMoneyInput;
use App\Forms\Components\SelectWithModal;
use App\Traits\HasAutoGeneratedCode;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\Repeater;
use Filament\Forms\Components\Repeater\TableColumn;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Hidden;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Filament\Support\Enums\Alignment;


class SalesDeliveryForm
{
    use HasAutoGeneratedCode;

    protected static function resolveCompanyId(callable $get): ?int
    {
        $companyId = $get('company_id');
        // If not found in current scope, try parent scope (for fields inside repeaters)
        if (!$companyId) {
            $companyId = $get('../../company_id');
        }

        // If still not found, try going up more levels (for deeply nested fields)
        if (!$companyId) {
            $companyId = $get('../../../company_id');
        }
        
        if ($companyId && $companyId !== 'all') {
            return (int) $companyId;
        }
        $selectedCompanyId = session('selected_company_id');
        if ($selectedCompanyId && $selectedCompanyId !== 'all') {
            return (int) $selectedCompanyId;
        }
        return null;
    }

    /**
     * Get the document type for code generation
     *
     * @return string
     */
    protected function getDocumentType(): string
    {
        return 'delivery_document';
    }

    /**
     * Get code field name
     *
     * @return string
     */
    protected function getCodeFieldName(): string
    {
        return 'delivery_number';
    }

    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make()
                    ->schema([
                        Select::make('company_id')
                            ->relationship(
                                name: 'company',
                                titleAttribute: 'name',
                                modifyQueryUsing: function ($query) {
                                    $user = auth()->user();
                                    if ($user) {
                                        $userCompanyIds = $user->companies()->pluck('companies.id');
                                        if ($userCompanyIds->isNotEmpty()) {
                                            $query->whereIn('companies.id', $userCompanyIds);
                                        } else {
                                            // If user has no assigned companies, return no results
                                            $query->whereRaw('1 = 0');
                                        }
                                    }
                                }
                            )
                            ->default(function () {
                                $selectedCompanyId = session('selected_company_id');
                                return $selectedCompanyId && $selectedCompanyId !== 'all'
                                    ? $selectedCompanyId
                                    : null;
                            })
                            ->hidden(function () {
                                $selectedCompanyId = session('selected_company_id');
                                return $selectedCompanyId && $selectedCompanyId !== 'all';
                            })
                            ->searchable()
                            ->preload()
                            ->nullable()
                            ->reactive()
                            ->afterStateUpdated(function ($state, callable $set) {
                                // Clear customer and sales order when company changes
                                $set('customer_id', null);
                                $set('sales_order_id', null);
                            })
                            ->columnSpanFull(),
                        Select::make('customer_id')
                            ->label('Pelanggan')
                            ->disabled(fn ($record) => (bool) ($record?->is_locked))
                            ->relationship(
                                name: 'customer',
                                titleAttribute: 'name',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $companyId = self::resolveCompanyId($get);
                                    if ($companyId) {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    return $query->where('is_customer', true)->orderBy('name');
                                }
                            )
                            ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->name} ({$record->contact_code})")
                            ->searchable(['name', 'contact_code'])
                            ->preload()
                            ->required()
                            ->live(onBlur: true)
                            ->afterStateUpdated(function ($state, callable $set) {
                                // Clear sales order when customer changes
                                $set('sales_order_id', null);
                            })
                            ->createOptionForm([
                                TextInput::make('name')
                                    ->label('Nama')
                                    ->required(),
                                (new \App\Filament\Resources\Contacts\Schemas\ContactForm)->getCodeField('contact_code', 'Kode Kontak')
                                    ->unique(\App\Models\Contact::class, 'contact_code', ignoreRecord: true,
                                        modifyRuleUsing: function ($rule) {
                                            // Get the company_id from the session
                                            $companyId = session('selected_company_id');

                                            // If there's a selected company, scope the uniqueness check to that company
                                            if ($companyId && $companyId !== 'all') {
                                                $rule->where('company_id', $companyId);
                                            }
                                            // If no company is selected, the uniqueness check will apply to all records
                                            // This ensures records are unique within their company
                                            return $rule;
                                        },
                                    ),
                                TextInput::make('email')
                                    ->label('Email')
                                    ->email(),
                                TextInput::make('phone')
                                    ->label('Telepon')
                                    ->tel(),
                                Hidden::make('is_customer')
                                    ->default(true),
                                Hidden::make('company_id')
                                    ->default(function (callable $get) {
                                        $companyId = $get('company_id') ?: session('selected_company_id');
                                        return ($companyId && $companyId !== 'all') ? $companyId : null;
                                    }),
                                Hidden::make('created_by_user_id')
                                    ->default(function () {
                                        return auth()->id();
                                    }),
                            ])
                            ->createOptionUsing(function (array $data) {
                                $contact = \App\Models\Contact::create($data);
                                return $contact->id;
                            }),
                        Select::make('sales_order_id')
                            ->label('Pesanan Penjualan')
                            ->disabled(fn ($record) => (bool) ($record?->is_locked))
                            ->relationship(
                                name: 'salesOrder',
                                titleAttribute: 'order_number',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $customerId = $get('customer_id');
                                    $companyId = self::resolveCompanyId($get);

                                    if ($customerId) {
                                        $query->where('customer_id', $customerId);
                                    }

                                    if ($companyId) {
                                        $query->where(function ($q) use ($companyId) {
                                            $q->where('company_id', $companyId)
                                              ->orWhereNull('company_id');
                                        });
                                    }

                                    // Only show sales orders with 'posted' status
                                    $query->where('status', 'posted');

                                    // Only exclude sales orders that already have locked delivery documents when creating a new record
                                    // Sales order menu creates locked delivery documents automatically, so this prevents manual creation
                                    // if any delivery document was created from sales order menu
                                    $currentRecordId = $get('../../record')?->id ?? null;
                                    if (!$currentRecordId) {
                                        $query->whereDoesntHave('deliveryDocuments', function ($deliveryQuery) {
                                            $deliveryQuery->where('is_locked', true)
                                                        ->whereNull('delivery_documents.deleted_at');
                                        });
                                    }

                                    return $query->with('customer');
                                }
                            )
                            ->searchable()
                            ->preload()
                            ->reactive()
                            ->afterStateUpdated(function ($state, callable $set, callable $get) {
                                // When sales order is selected, auto-fill customer and items
                                if ($state) {
                                    $salesOrder = \App\Models\SalesOrder::with(['items.product'])->find($state);
                                    if ($salesOrder) {
                                        $set('customer_id', $salesOrder->customer_id);

                                        // Auto-fill items from sales order - show all items regardless of delivery status
                                        $deliveryType = $get('delivery_type');
                                        $items = [];

                                        foreach ($salesOrder->items as $item) {
                                            // Show all items without validation - use original quantity
                                            // Removed delivery type filtering to show all items
                                            $items[] = [
                                                'sales_order_item_id' => $item->id,
                                                'product_id' => $item->product_id,
                                                'quantity' => $item->quantity,
                                                'quantity_display' => NumberInput::formatRoundedIntegerDisplay($item->quantity),
                                                'unit_id' => $item->unit_id,
                                                'description' => $item->description,
                                            ];
                                        }

                                        $set('items', $items);
                                    }
                                } else {
                                    // Clear items if no sales order selected
                                    $set('items', []);
                                }
                            })
                            ->getOptionLabelFromRecordUsing(fn ($record) => $record->order_number . ' - ' . $record->customer?->name),
                        Select::make('delivery_type')
                            ->label(__('Jenis Pengiriman'))
                            ->options([
                                'goods' => 'Barang',
                                'document' => 'Dokumen',
                            ])
                            ->disabled(fn ($record) => (bool) ($record?->is_locked))
                            ->required()
                            ->reactive(),
                        DatePicker::make('date')
                            ->label(__('Tanggal'))
                            ->required()
                            ->default(now()),                       
                        TextInput::make('reference_no')
                            ->maxLength(255)
                            ->label('Nomor Referensi'),
                        (new static)->getCodeField()->label('Nomor Pengiriman')
                            ->unique(ignoreRecord: true,
                                modifyRuleUsing: fn ($rule, $record) => $rule->where(function ($query) use ($record) {
                                    $companyId = session('selected_company_id');
                                    if ($companyId && $companyId !== 'all') {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    if ($record && $record->exists) {
                                        $query->where('id', '!=', $record->getKey());
                                    }
                                    $query->whereNull('deleted_at');
                                    return $query;
                                })
                            ),
                        Textarea::make('description')
                            ->rows(1)
                            ->maxLength(65535)
                            ->label('Deskripsi'),
                        Select::make('status')
                            ->label('Status')
                            ->options([
                                'draft' => 'Draft',
                                'posted' => 'Posted',
                            ])
                            ->default('posted')
                            ->required()
                            ->native(false)
                            ->disabled(fn ($record) => $record && $record->salesReturns()->exists())
                            ->live(),
                    ])
                    ->columns(3)
                    ->columnSpanFull(),

                // Items repeater without price fields
                Repeater::make('items')
                    ->relationship()
                    ->hiddenLabel()
                    ->addActionLabel('Tambah Item Baru')
                    ->required()
                    ->addable(fn (callable $get) => !(bool) $get('is_locked'))
                    ->defaultItems(0) // No default items, will load from sales order
                    ->table([
                        TableColumn::make('Produk')->width('30%')->alignment(Alignment::Start),
                        TableColumn::make('Jumlah')->width('15%')->alignment(Alignment::End),
                        TableColumn::make('Satuan')->width('15%')->alignment(Alignment::Start),
                        TableColumn::make('Deskripsi')->width('40%')->alignment(Alignment::Start),
                    ])
                    ->schema([
                        Hidden::make('sales_order_item_id'),
                        Select::make('product_id')
                            ->required()
                            ->searchable(['name', 'code'])
                            ->label(__('Produk'))
                            ->disabled(fn (callable $get) => (bool) $get('../../is_locked'))
                            ->relationship(
                                name: 'product',
                                titleAttribute: 'name',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $companyId = self::resolveCompanyId($get);
                                    if ($companyId) {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    
                                    return $query->orderBy('name');
                                }
                            )
                            ->getOptionLabelFromRecordUsing(fn ($record) => "{$record->name} ({$record->code})")
                            ->preload()
                            ->reactive()
                            ->live(onBlur: true) // Make it reactive to form changes
                            ->createOptionForm([
                                TextInput::make('name')
                                    ->label('Nama')
                                    ->required(),
                                (new \App\Filament\Resources\Products\Schemas\ProductForm)->getCodeField('code', 'Kode Produk')
                                    ->unique(
                                        \App\Models\Product::class,
                                        'code',
                                        ignoreRecord: true,
                                        modifyRuleUsing: function ($rule) {
                                            // Get the company_id from the session
                                            $companyId = session('selected_company_id');

                                            // If there's a selected company, scope the uniqueness check to that company
                                            if ($companyId && $companyId !== 'all') {
                                                $rule->where('company_id', $companyId);
                                            }
                                            // If no company is selected, the uniqueness check will apply to all records
                                            // This ensures records are unique within their company
                                            return $rule;
                                        },
                                    ),
                                Select::make('product_group_id')
                                    ->label('Kelompok Produk')
                                    ->relationship(
                                        "productGroup",
                                        "name",
                                        modifyQueryUsing: function ($query) {
                                            $selectedCompanyId = session('selected_company_id');
                                            if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                                                $query->where('company_id', $selectedCompanyId);
                                            }
                                            return $query;
                                        }
                                    )
                                    ->searchable()
                                    ->preload()
                                    ->required(),
                                ...RoundedIntegerMoneyInput::schema(
                                    name: 'selling_price',
                                    label: 'Harga Jual',
                                    required: false,
                                    defaultDecimal: '0.00',
                                ),
                                Select::make('unit_id')
                                    ->label('Satuan')
                                    ->searchable()
                                    ->options(function () {
                                        $selectedCompanyId = session('selected_company_id');
                                        $q = \App\Models\Unit::query();
                                        if ($selectedCompanyId && $selectedCompanyId !== 'all') {
                                            $q->where(function ($inner) use ($selectedCompanyId) {
                                                $inner->where('company_id', $selectedCompanyId)->orWhereNull('company_id');
                                            });
                                        } else {
                                            $q->whereNull('company_id');
                                        }
                                        return $q->orderBy('name')->pluck('name', 'id')->toArray();
                                    }),
                                Textarea::make('description')
                                    ->label('Deskripsi')
                                    ->rows(2),
                                Hidden::make('company_id')
                                    ->default(function () {
                                        $selectedCompanyId = session('selected_company_id');
                                        return ($selectedCompanyId && $selectedCompanyId !== 'all') ? $selectedCompanyId : null;
                                    }),
                                Hidden::make('created_by_user_id')
                                    ->default(function () {
                                        return auth()->id();
                                    }),
                            ])
                            ->createOptionUsing(function (array $data) {
                                return \App\Models\Product::create($data);
                            }),
                        ...RoundedIntegerMoneyInput::schema(
                            name: 'quantity',
                            label: 'Jumlah',
                            required: true,
                            defaultDecimal: '1.00',
                        ),
                        Select::make('unit_id')
                            ->searchable()
                            ->label('Satuan')
                            ->disabled(fn (callable $get) => (bool) $get('../../is_locked'))
                            ->relationship(
                                name: 'unit',
                                modifyQueryUsing: function ($query, callable $get) {
                                    $companyId = self::resolveCompanyId($get);
                                    if ($companyId) {
                                        $query->where('company_id', $companyId);
                                    } else {
                                        $query->whereNull('company_id');
                                    }
                                    return $query->orderBy('name');
                                }
                            )
                            ->preload()
                            ->getOptionLabelFromRecordUsing(fn ($record) => $record->name),

                        Textarea::make('description')
                            ->label('Deskripsi')
                            ->disabled(fn (callable $get) => (bool) $get('../../is_locked'))
                            ->rows(1),
                    ])
                    ->reorderable()
                    ->collapsible()
                    ->compact()
                    ->columnSpan('full'),

                // Document Upload Section - Only show when delivery type is document
                Section::make('Lampiran Dokumen')
                    ->schema([
                        FileUpload::make('bast_document')
                            ->label('Dokumen BAST')
                            ->disk('public')
                            ->directory('delivery-documents/bast')
                            ->maxSize(10240) // 10MB
                            ->acceptedFileTypes(['application/pdf', 'image/*'])
                            ->downloadable(),
                        FileUpload::make('tpb_document')
                            ->label('Dokumen TPB')
                            ->disk('public')
                            ->directory('delivery-documents/tpb')
                            ->maxSize(10240) // 10MB
                            ->acceptedFileTypes(['application/pdf', 'image/*'])
                            ->downloadable(),
                        Textarea::make('internal_notes')
                            ->label('Catatan Internal')
                            ->rows(2)
                            ->maxLength(65535)
                            ->columnSpanFull(),
                    ])
                    ->columns(2)
                    ->columnSpanFull()
                    ->visible(fn (callable $get) => $get('delivery_type') === 'document'),

            ]);
    }
}
